/*
 * SplashForm.java
 *
 * Created on November 8, 2008, 10:37 PM
 */

package common2;

import bean.admin.AppConfig;
import java.awt.Dimension;
import javax.swing.ImageIcon;

/**
 *
 * @author  Entokwaa
 */
public class SplashForm extends javax.swing.JFrame {

    /** Creates new form SplashForm */
    public SplashForm() {
        initComponents();
        String image = AppConfig.extractLoadingImage();
        if (image==null || image.isEmpty()) return;
        image = image.toLowerCase();
        ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/icons/" + image));
        int height = icon.getIconHeight();
        int width = icon.getIconWidth();
        lblImage.setMaximumSize(new Dimension(width, height));
        lblImage.setMinimumSize(new Dimension(width, height));
        lblImage.setPreferredSize(new Dimension(width, height));
        lblImage.setIcon(icon);
        pack();
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdditionalInfo = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        lblAdditionalInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdditionalInfo.setName("lblAdditionalInfo"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setName("Form"); // NOI18N
        setResizable(false);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridLayout());

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/loading.gif"))); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(common2.Common2App.class).getContext().getResourceMap(SplashForm.class);
        lblImage.setText(resourceMap.getString("lblImage.text")); // NOI18N
        lblImage.setName("lblImage"); // NOI18N
        getContentPane().add(lblImage);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lblAdditionalInfo;
    private javax.swing.JLabel lblImage;
    // End of variables declaration//GEN-END:variables

}
