/*
 * AdmissionForm.java
 *
 * Created on June 4, 2009, 9:16 PM
 */

package ui;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;

import bean.Admission;
import bean.Patient;
import bean.reference.RoomHospital;

import constants.UserInfo;
import springbean.AAAConfig;
import template.report.AbstractReportTemplate;
import template.screen.TransactionPanel;
import util.DBClient;
import util.PanelUtil;

/**
 *
 * @author  alex
 */
public class AdmissionForm extends TransactionPanel {

    public static void main(String[] args) {
        java.awt.Color clr = new java.awt.Color(44, 117, 44);
        constants.Constants.panelBackground = clr;
        constants.Constants.labelColor = Color.WHITE;
        AAAConfig.getInstance();
        UserInfo.weblogin("AAA", "AAAXXXAAA");
        PanelUtil.displayToFrame(new AdmissionForm());
    }
    
    /** Creates new form AdmissionForm */
    public AdmissionForm() {
        initComponents();
        PanelUtil.updateColor(this);
        PanelUtil.updateColor(jPanel1);
        PanelUtil.updateColor(jPanel2);
        PanelUtil.updateColor(jPanel3);
        PanelUtil.updateColor(jPanel4);
        PanelUtil.updateColor(jPanel5);
        PanelUtil.updateColor(jPanel6);
        PanelUtil.updateColor(jPanel7);
        PanelUtil.updateColor(jLabel1);
        try {
        	btnShowAllRoomsActionPerformed(null);
        	List lst = DBClient.getList("SELECT a FROM Patient a WHERE a.lastName LIKE '"+txtPatient.getText()+"%' OR a.firstName LIKE '"+txtPatient.getText()+"%' ORDER BY a.lastName, a.firstName");
        	beanPatients.setList(lst);
        }
        catch (Exception e) {
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        beanRooms = new component.BeanPanelPallete();
        jPanel3 = new javax.swing.JPanel();
        cboRooms = new javax.swing.JComboBox();
        btnShowAllRooms = new javax.swing.JButton();
        btnShowAllVacant = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnAdmissionReport = new javax.swing.JButton();
        btnVacantRoomReport = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        beanPatients = new component.BeanPanelPallete();
        jPanel5 = new javax.swing.JPanel();
        btnAdmitPatient = new javax.swing.JButton();
        btnAddNewPatient = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPatient = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout(10, 10));

        jPanel6.setLayout(new java.awt.GridLayout(1, 0, 20, 20));

        jPanel1.setLayout(new java.awt.BorderLayout());

        beanRooms.setBeanName("RoomHospitalExt");
        beanRooms.setShowForm(false);
        beanRooms.setShowImage(false);
        beanRooms.setShowResult(true);

        javax.swing.GroupLayout beanRoomsLayout = new javax.swing.GroupLayout(beanRooms);
        beanRooms.setLayout(beanRoomsLayout);
        beanRoomsLayout.setHorizontalGroup(
            beanRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );
        beanRoomsLayout.setVerticalGroup(
            beanRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );

        jPanel1.add(beanRooms, java.awt.BorderLayout.CENTER);

        cboRooms.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PRIVATE", "SEMI PRIVATE", "WARD", "OPERATING ROOM", "ICU", "DELIVERY ROOM", "EMERGENCY ROOM", "NURSERY", "RADIOLOGY", "LABORATORY" }));
        cboRooms.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboRoomsItemStateChanged(evt);
            }
        });
        jPanel3.add(cboRooms);

        btnShowAllRooms.setText("Show All Rooms");
        btnShowAllRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllRoomsActionPerformed(evt);
            }
        });
        jPanel3.add(btnShowAllRooms);

        btnShowAllVacant.setText("All Vacant");
        btnShowAllVacant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllVacantActionPerformed(evt);
            }
        });
        jPanel3.add(btnShowAllVacant);

        jLabel2.setText("   Reports:");
        jPanel3.add(jLabel2);

        btnAdmissionReport.setText("Admission");
        btnAdmissionReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmissionReportActionPerformed(evt);
            }
        });
        jPanel3.add(btnAdmissionReport);

        btnVacantRoomReport.setText("Vacant");
        btnVacantRoomReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVacantRoomReportActionPerformed(evt);
            }
        });
        jPanel3.add(btnVacantRoomReport);

        jPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel6.add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        beanPatients.setBeanName("Patient");
        beanPatients.setShowForm(false);
        beanPatients.setShowImage(false);
        beanPatients.setShowResult(true);

        javax.swing.GroupLayout beanPatientsLayout = new javax.swing.GroupLayout(beanPatients);
        beanPatients.setLayout(beanPatientsLayout);
        beanPatientsLayout.setHorizontalGroup(
            beanPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );
        beanPatientsLayout.setVerticalGroup(
            beanPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );

        jPanel2.add(beanPatients, java.awt.BorderLayout.CENTER);

        btnAdmitPatient.setText("Admit to Selected Room");
        btnAdmitPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmitPatientActionPerformed(evt);
            }
        });
        jPanel5.add(btnAdmitPatient);

        btnAddNewPatient.setText("Add New Patient");
        btnAddNewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewPatientActionPerformed(evt);
            }
        });
        jPanel5.add(btnAddNewPatient);

        jPanel2.add(jPanel5, java.awt.BorderLayout.SOUTH);

        jPanel6.add(jPanel2);

        add(jPanel6, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Search Patient");
        jPanel4.add(jLabel1);

        txtPatient.setPreferredSize(new java.awt.Dimension(200, 20));
        txtPatient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPatientKeyTyped(evt);
            }
        });
        jPanel4.add(txtPatient);

        jPanel7.add(jPanel4);

        add(jPanel7, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatientKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPatientKeyTyped
        if (evt.getKeyChar()=='\n') {
        	if (txtPatient.getText()==null || txtPatient.getText().trim().isEmpty()) {
            	List lst = DBClient.getList("SELECT a FROM Patient a ORDER BY a.lastName, a.firstName");
            	beanPatients.setList(lst);
        	}
        	else {
            	List lst = DBClient.getList("SELECT a FROM Patient a WHERE a.lastName LIKE '"+txtPatient.getText()+"%' OR a.firstName LIKE '"+txtPatient.getText()+"%' ORDER BY a.lastName, a.firstName");
            	beanPatients.setList(lst);
        	}
        }
    }//GEN-LAST:event_txtPatientKeyTyped

    private void cboRoomsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboRoomsItemStateChanged
    	String str = cboRooms.getSelectedItem().toString();
    	List lst = DBClient.getList("SELECT a FROM RoomHospital a WHERE a.type='"+str+"'");
    	beanRooms.setList(lst);
    }//GEN-LAST:event_cboRoomsItemStateChanged

    private void btnShowAllRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllRoomsActionPerformed
    	List lst = DBClient.getList("SELECT a FROM RoomHospital a");
    	beanRooms.setList(lst);
    }//GEN-LAST:event_btnShowAllRoomsActionPerformed

    private void btnShowAllVacantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllVacantActionPerformed
    	List lst = DBClient.getList("SELECT a FROM RoomHospital a WHERE a.patientId=0");
    	beanRooms.setList(lst);
    }//GEN-LAST:event_btnShowAllVacantActionPerformed

    private void btnAdmitPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmitPatientActionPerformed
    	Patient p = (Patient) beanPatients.getBean();
    	RoomHospital r = (RoomHospital) beanRooms.getBean();
    	if (p==null || r==null) {
    		PanelUtil.showError(null, "Please select a room and patient.");
    		return;
    	}
    	if (p.section!=null && !p.section.isEmpty()) {
    		boolean b = PanelUtil.showPrompt(null, "Patient ["+p.toString()+"] is already admitted to room ["+p.section+"].\n Would you like to admit to other room?");
    		if (!b) return;
    	}
    	if (r.patientId!=0) {
    		PanelUtil.showMessage(null, "Bed ["+r.code+"] is already occupied.");
    		return;
    	}
    	
    	Admission ad = new Admission();
    	ad.patientId = p.personId;
    	ad.room = r.code;
    	ad.roomRate = r.rate;
    	ad.admissionDate = new Date();
    	ad.save();
    	
    	r.patientId = p.personId;
    	p.admissionId = ad.seq;
    	p.changeSupport.firePropertyChange("section", p.section, p.section=r.room+"-"+r.bed);
    	
    	List tmp = new ArrayList();
    	tmp.add(r);
    	tmp.add(p);
    	
    	List lst = DBClient.batchQueryNoCache(tmp, "SELECT a FROM RoomHospital a");
    	beanRooms.setList(lst);
    	
    	beanPatients.view.tblResult.tableChanged(null);
    }//GEN-LAST:event_btnAdmitPatientActionPerformed

    private void btnAddNewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewPatientActionPerformed
        PanelUtil.popupBeanTemplate(Patient.class,"Add Patient",true);
    }//GEN-LAST:event_btnAddNewPatientActionPerformed

    private void btnVacantRoomReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVacantRoomReportActionPerformed
        AbstractReportTemplate.getInstance().showReportFromFileTemplate("VacantRoomList", new HashMap());
    }//GEN-LAST:event_btnVacantRoomReportActionPerformed

    private void btnAdmissionReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmissionReportActionPerformed
        AbstractReportTemplate.getInstance().showReportFromFileTemplate("AdmissionList", new HashMap());
    }//GEN-LAST:event_btnAdmissionReportActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public component.BeanPanelPallete beanPatients;
    public component.BeanPanelPallete beanRooms;
    private javax.swing.JButton btnAddNewPatient;
    private javax.swing.JButton btnAdmissionReport;
    private javax.swing.JButton btnAdmitPatient;
    private javax.swing.JButton btnShowAllRooms;
    private javax.swing.JButton btnShowAllVacant;
    private javax.swing.JButton btnVacantRoomReport;
    private javax.swing.JComboBox cboRooms;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    public javax.swing.JTextField txtPatient;
    // End of variables declaration//GEN-END:variables
    
}
