/*
 * AttendanceScanner.java
 *
 * Created on October 19, 2008, 8:45 PM
 */

package ui.action;

import bean.Person;
import bean.accounting.payroll.PersonAttendance;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import service.util.AbstractIBean;
import util.DateUtil;

/**
 *
 * @author  Entokwaa
 */
public class AttendanceScannerAction extends javax.swing.JPanel {
    static AttendanceScannerAction action;
    SimpleDateFormat sdfDisplay = new SimpleDateFormat("HH:mm:ss");
    SimpleDateFormat sdf = new SimpleDateFormat("HHmm");
    
    public static void showScanner() {
        if (action==null) action = new AttendanceScannerAction();
        action.dlgScanner.setMinimumSize(Toolkit.getDefaultToolkit().getScreenSize());
        action.dlgScanner.setVisible(true);
    }
    
    /** Creates new form AttendanceScanner */
    public AttendanceScannerAction() {
        initComponents();
        Timer timer = new Timer();
        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                lblTime.setText(sdfDisplay.format(constants.Constants.useDate));
                txtId.requestFocus();
            }
        };
        timer.scheduleAtFixedRate(task, 1000, 1000);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgScanner = new javax.swing.JDialog();
        lblTime = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblExit = new javax.swing.JLabel();
        lblPerson = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        dlgScanner.setAlwaysOnTop(true);
        dlgScanner.setModal(true);
        dlgScanner.setName("dlgScanner"); // NOI18N
        dlgScanner.setUndecorated(true);

        lblTime.setFont(new java.awt.Font("Tahoma", 0, 36));
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime.setText("<<Time>>");
        lblTime.setName("lblTime"); // NOI18N

        txtId.setBackground(new java.awt.Color(204, 204, 204));
        txtId.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtId.setName("txtId"); // NOI18N
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
        });

        lblExit.setText("<<Exit>>");
        lblExit.setName("lblExit"); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        lblPerson.setFont(new java.awt.Font("Tahoma", 0, 14));
        lblPerson.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPerson.setText("<<PERSON>>");
        lblPerson.setName("lblPerson"); // NOI18N

        javax.swing.GroupLayout dlgScannerLayout = new javax.swing.GroupLayout(dlgScanner.getContentPane());
        dlgScanner.getContentPane().setLayout(dlgScannerLayout);
        dlgScannerLayout.setHorizontalGroup(
            dlgScannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgScannerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgScannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addComponent(lblPerson, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addGroup(dlgScannerLayout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                        .addComponent(lblExit)))
                .addContainerGap())
        );
        dlgScannerLayout.setVerticalGroup(
            dlgScannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgScannerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgScannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblExit)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/help.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
    dlgScanner.setVisible(false);
}//GEN-LAST:event_lblExitMouseClicked

    protected Person getPerson(String txt) {
        Person p = (Person) AbstractIBean.firstRecord("SELECT a FROM Person a WHERE a.personId=",txt);
        try {
            if (p==null) p = (Person) AbstractIBean.firstRecord("SELECT a FROM Student a WHERE a.studentNumber='",txt,"'");
        }
        catch (Exception e) {
        }
        return p;
    }
    
    protected void putAttendance() {
        String txt = txtId.getText();
        Person p = getPerson(txt);
        if (p!=null) {
            Date date = constants.Constants.useDate;
            PersonAttendance att = (PersonAttendance) p.firstRecord("SELECT a FROM PersonAttendance a WHERE a.personId=",p.personId+""," AND a.attendanceDate='",DateUtil.formatDateToSql(date),"'");
            if (att==null) {
                att = new PersonAttendance();
                att.attendanceDate = date;
                att.personId = p.personId;
                att.login = sdf.format(date);
            }
            else {
                att.logout = sdf.format(date);
            }
            att.save();
            lblPerson.setText(p.toString());
        }
    }

private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
    if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
        putAttendance();
        txtId.setText("");
    }
}//GEN-LAST:event_txtIdKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dlgScanner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblPerson;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables

}
