/*
 * TemplateViewer.java
 *
 * Created on September 15, 2008, 9:30 AM
 */

package test;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import springbean.AAAConfig;
import template.TemplateReader;
import template.screen.AbstractTemplatePanel;
import util.PanelUtil;

/**
 *
 * @author  Entokwaa
 */
public class TemplateViewer extends javax.swing.JFrame {

    public static void view(Class bean) {
        AAAConfig.getInstance();
        AbstractTemplatePanel view = TemplateReader.getTemplate(bean);
        TemplateViewer viewer = new TemplateViewer();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        viewer.setSize(screenSize);
        viewer.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        viewer.pnlMain.add((JPanel)view.getMainForm());
//        viewer.pack();
        viewer.setVisible(true);
    }
    
    public static JPanel getView(Class bean) {
        AAAConfig.getInstance();
        AbstractTemplatePanel view = TemplateReader.getTemplate(bean);
        return (JPanel)view.getMainForm();
    }

    public static JPanel getView(String bean) {
            AAAConfig.getInstance();
            Class cls = PanelUtil.getBeanClass(bean);
            AbstractTemplatePanel view = TemplateReader.getTemplate(cls);
            return (JPanel) view.getMainForm();
    }

    /** Creates new form TemplateViewer */
    public TemplateViewer() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        pnlMain.setLayout(new java.awt.GridLayout());
        getContentPane().add(pnlMain);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TemplateViewer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables

}
