/*
 * AdmissionAction.java
 *
 * Created on September 18, 2008, 10:50 PM
 */
package ui.action;

import bean.Admission;
import service.util.AbstractIBean;
import service.util.WSPersistenceEntityManager;
import springbean.SchoolDefaultProcess;
import util.PanelUtil;

/**
 *
 * @author  Entokwaa
 */
public class AdmissionAction extends javax.swing.JPanel {
    static AdmissionAction action;
    Admission ad;
    
    public static void showRegisterStudent(Admission ad) {
        if (action==null) {
            action = new AdmissionAction();
        }
        action.ad = ad;
        action.lblStudent.setText(ad.lastName+", "+ad.firstName+" "+ad.middleInitial);
        action.btnRegisterActionPerformed(null);
    }
    
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {
        if (ad.isEmptyKey()) {
            //PanelUtil.showError(btnRegisterStudent, "Please choose student to register.");
            return;
        }
        bean.Student studTmp = (bean.Student) AbstractIBean.firstRecord("SELECT a FROM Student a WHERE a.lastName='" + ad.getLastName() + "' AND a.firstName='" + ad.getFirstName() + "' AND a.middleInitial='" + ad.getMiddleInitial() + "'");
        if (studTmp==null || studTmp.isEmptyKey()) {
            dlgRegister.pack();
            dlgRegister.setVisible(true);
        } else {
            PanelUtil.showMessage(btnContinueRegister, "Student already registered for "+studTmp.getCourse());
        }
    }

    /** Creates new form AdmissionAction */
    public AdmissionAction() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        schoolPUEntityManager = WSPersistenceEntityManager.getInstance();
        courseQuery = java.beans.Beans.isDesignTime() ? null : schoolPUEntityManager.createQuery("SELECT c FROM Course c");
        courseList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(courseQuery.getResultList());
        dlgRegister = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        lblStudent = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboCourse = new component.JComboBoxPallete();
        btnContinueRegister = new javax.swing.JButton();

        dlgRegister.setTitle("Register Student");
        dlgRegister.setModal(true);
        dlgRegister.setName("dlgRegister"); // NOI18N
        dlgRegister.getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Student:");
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 0);
        dlgRegister.getContentPane().add(jLabel2, gridBagConstraints);

        lblStudent.setName("lblStudent"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 0);
        dlgRegister.getContentPane().add(lblStudent, gridBagConstraints);

        jLabel4.setText("Course:");
        jLabel4.setName("jLabel4"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 0);
        dlgRegister.getContentPane().add(jLabel4, gridBagConstraints);

        cboCourse.setName("cboCourse"); // NOI18N

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, courseList, cboCourse);
        bindingGroup.addBinding(jComboBoxBinding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 0);
        dlgRegister.getContentPane().add(cboCourse, gridBagConstraints);

        btnContinueRegister.setText("Register Student");
        btnContinueRegister.setName("btnContinueRegister"); // NOI18N
        btnContinueRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueRegisterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        dlgRegister.getContentPane().add(btnContinueRegister, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

private void btnContinueRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueRegisterActionPerformed
    ad.register();
    dlgRegister.setVisible(false);
}//GEN-LAST:event_btnContinueRegisterActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinueRegister;
    private component.JComboBoxPallete cboCourse;
    private java.util.List<bean.reference.Course> courseList;
    private javax.persistence.Query courseQuery;
    private javax.swing.JDialog dlgRegister;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblStudent;
    private javax.persistence.EntityManager schoolPUEntityManager;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
