/*
 * NewJPanel.java
 *
 * Created on September 6, 2008, 11:11 AM
 */

package template.screen;

import javax.swing.JPanel;
import javax.swing.border.TitledBorder;

import util.BeanUtil;
import bean.admin.AppConfig;
import javax.swing.UIManager;
import java.awt.Color;

/**
 *
 * @author  Entokwaa
 */
public class GroupPanel extends javax.swing.JPanel {
    private String name = "Department";
	
    public static GroupPanel construct(String name, JPanel newPanel) {
        GroupPanel pnl = new GroupPanel(name);
        pnl.pnlMain.add(newPanel);
        if (AppConfig.isGroupWithTitle()) {
            pnl.pnlMain.setBorder(javax.swing.BorderFactory.createTitledBorder(BeanUtil.concat(name,":")));
            pnl.setBorder(null);
            TitledBorder b = (TitledBorder) pnl.pnlMain.getBorder();
            if (constants.Constants.labelColor!=null) {
                b.setTitleColor(constants.Constants.labelColor);
            }
        }
        if (constants.Constants.panelBackground!=null) {
            pnl.setBackground(constants.Constants.panelBackground);
            if (newPanel!=null) newPanel.setBackground(constants.Constants.panelBackground);
        }
        return pnl;
    }
    
    /** Creates new form NewJPanel */
    public GroupPanel(String name) {
    	this.name = name;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        pnlMain = new javax.swing.JPanel();
        pnlMain.setBorder(new TitledBorder(UIManager.getBorder("TitledBorder.border"), "Department", TitledBorder.LEADING, TitledBorder.TOP, null, Color.BLUE));

        setLayout(new java.awt.BorderLayout());

        pnlMain.setLayout(new java.awt.GridLayout(1, 0));
        add(pnlMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables

}
