/*
 * TablePopup.java
 *
 * Created on September 20, 2008, 4:11 PM
 */

package template.screen;

import java.util.List;
import org.jdesktop.beansbinding.BindingGroup;
import template.screen.component.JTableReadOnly;

/**
 *
 * @author  Entokwaa
 */
public class TablePopup extends javax.swing.JPanel {
    static TablePopup popup;
    List records;
    Class cls;
    String[] fields;
    
    public static void showRecords(String title, List records, Class cls, String... fields) {
        if (popup==null) {
            popup = new TablePopup();
        }
        popup.records = records;
        popup.cls = cls;
        popup.fields = fields;
        popup.bind();
        popup.dlgTable.setTitle(title);
        popup.dlgTable.setVisible(true);
    }
    
    private void bind() {
        BindingGroup bindingGroup = new BindingGroup();
        TemplateParserUtil.bindPopTable(bindingGroup, records, tblRecords, cls, fields);
        tblRecords.updateUI();
        bindingGroup.bind();
    }
    
    /** Creates new form TablePopup */
    public TablePopup() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgTable = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecords = new JTableReadOnly();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(common2.Common2App.class).getContext().getResourceMap(TablePopup.class);
        dlgTable.setTitle(resourceMap.getString("dlgTable.title")); // NOI18N
        dlgTable.setAlwaysOnTop(true);
        dlgTable.setMinimumSize(new java.awt.Dimension(600, 250));
        dlgTable.setName("dlgTable"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRecords.setName("tblRecords"); // NOI18N
        jScrollPane1.setViewportView(tblRecords);

        javax.swing.GroupLayout dlgTableLayout = new javax.swing.GroupLayout(dlgTable.getContentPane());
        dlgTable.getContentPane().setLayout(dlgTableLayout);
        dlgTableLayout.setHorizontalGroup(
            dlgTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addContainerGap())
        );
        dlgTableLayout.setVerticalGroup(
            dlgTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );

        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dlgTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRecords;
    // End of variables declaration//GEN-END:variables

}
