/*
 * Template2.java
 *
 * Created on September 6, 2008, 11:39 PM
 */

package template.screen;

import javax.swing.JPanel;
import util.PanelUtil;

import java.util.List;

import service.util.AbstractIBean;

/**
 *
 * @author  Entokwaa
 */
public class TemplateSinglePage extends AbstractTemplatePanel {
    @Override
    protected void updateList(List<AbstractIBean> newList) {
        if (newList!=null) {
            for (AbstractIBean b : newList) {
                b.showCharts = false;
                b.showFile = false;
                b.showSubrecords = false;
                if (!template.showImages()) {
                    b.showImages = false;
                }
            }
        }
        super.updateList(newList);
    }

    public void callSearchResult() {
    	super.getMainSearchResult();
    }
    
    @Override
    public void hideSearchCriteria() {
        pnlCriteria2.setVisible(false);
    }

    @Override
    public void hideSearchResult() {
        pnlResult2.setVisible(false);
    }

    @Override
    public Object getMainForm() {
        super.getMainForm();
        pnlMainForm2.removeAll();
        pnlCriteria2.removeAll();
        pnlResult2.removeAll();
        pnlButton2.removeAll();         
        if (template.showImages()) {
            pnlMainForm2.add(pnlTop);
        }
        else {
            pnlMainForm2.add(pnlMainForm);
        }
        
        GroupPanel pnlCrit = GroupPanel.construct("Criteria", (JPanel)super.getMainSearch());
        pnlCriteria2.add(pnlCrit);
        pnlCrit.hide();

        GroupPanel pnlResult = GroupPanel.construct("Search Result", (JPanel)super.getMainSearchResult());
        pnlResult2.add(pnlResult);
        
        pnlButton2.add(super.pnlButton);
        return this;
    }

    @Override
    public Object getMainSearch() {
        return new JPanel();
    }

    @Override
    public Object getMainSearchResult() {
        return new JPanel();
    }

    /** Creates new form Template2 */
    public TemplateSinglePage() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlSearch = new javax.swing.JPanel();
        pnlResult2 = new javax.swing.JPanel();
        pnlCriteria2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pnlMainForm2 = new javax.swing.JPanel();
        pnlButton2 = new javax.swing.JPanel();

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(100, 400));

        setLayout(new java.awt.BorderLayout());

        pnlSearch.setName("pnlSearch"); // NOI18N

        pnlResult2.setName("pnlResult2"); // NOI18N
        pnlResult2.setLayout(new java.awt.GridLayout(1, 0));

        pnlCriteria2.setName("pnlCriteria2"); // NOI18N
        pnlCriteria2.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout pnlSearchLayout = new javax.swing.GroupLayout(pnlSearch);
        pnlSearch.setLayout(pnlSearchLayout);
        pnlSearchLayout.setHorizontalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlResult2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE)
                    .addComponent(pnlCriteria2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlSearchLayout.setVerticalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCriteria2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlResult2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlSearch, java.awt.BorderLayout.NORTH);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        pnlMainForm2.setMinimumSize(new java.awt.Dimension(750, 0));
        pnlMainForm2.setName("pnlMainForm2"); // NOI18N
        pnlMainForm2.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(pnlMainForm2, java.awt.BorderLayout.NORTH);

        pnlButton2.setName("pnlButton2"); // NOI18N
        pnlButton2.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(pnlButton2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    protected javax.swing.JPanel pnlButton2;
    protected javax.swing.JPanel pnlCriteria2;
    protected javax.swing.JPanel pnlMainForm2;
    protected javax.swing.JPanel pnlResult2;
    private javax.swing.JPanel pnlSearch;
    // End of variables declaration//GEN-END:variables

}
