
import java.lang.annotation.Annotation;

import template.Display;
import template.Displays;
import template.UITemplate;
import util.BeanUtil;
import util.PanelUtil;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JavaFXGenerator.java
 *
 * Created on Jul 19, 2009, 11:38:45 AM
 */

/**
 *
 * @author alex
 */
public class JavaFXGenerator extends javax.swing.JFrame {
    private String code1 = "/* " +
            "\n * BEAN.fx " +
            "\n * " +
            "\n */ " +
            "\nimport javafx.stage.Stage; " +
            "\nimport javafx.scene.Scene; \n" +
            "\nimport bean.*; \n" +
            "\n/** " +
            "\n * @author alex " +
            "\n */" +
            "\nvar bean: BEAN = new BEAN();\n\n";

    private String code2 = "var NAME:InputPallete = InputPallete{ " +
    		"\n     name:\"NAME\" " +
            "\n     myLabel:\"LABEL\" " +
            "\n     bean:bean " +
            "\n     top:TOP " +
            "\n     lblXPos:XPOS " +
            "\n     lblWidth:75 " +
            "\n     txtWidth:150 " +
            "\n};\n";

    private String code3 = "Stage { " +
            "\n    title: \"BEAN\" " +
            "\n    width: 500 " +
            "\n    height: 500 " +
            "\n    scene: Scene { " +
            "\n        content: [ \n";

    private String code4 = "\n	] " +
            "\n    } " +
            "\n}";
    /** Creates new form JavaFXGenerator */
    public JavaFXGenerator() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txtOther = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        txtBean = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCode = new javax.swing.JTextArea();

        jScrollPane2.setViewportView(txtOther);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bean:");

        btnCreate.setText("Create FX Code"); // NOI18N
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Generated Code:"));

        txtCode.setColumns(20);
        txtCode.setRows(5);
        jScrollPane1.setViewportView(txtCode);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtBean, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnCreate)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(txtBean, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnCreate))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String beanName = txtBean.getText();
        Class cls = util.PanelUtil.getBeanClass(beanName);
        if (cls==null) {
        	PanelUtil.showError(null, "Invalid bean.");
        	return;
        }
        template.UITemplate template = (UITemplate) cls.getAnnotation(template.UITemplate.class);
        template.Displays displays = (Displays) cls.getAnnotation(template.Displays.class);
        StringBuffer sb = new StringBuffer();
        String bean = BeanUtil.getEntityName(cls);
        sb.append(code1.replaceAll("BEAN", bean));
        Display[] arr = displays.value();
        int top = 10;
        int x1 = 10;
        int x2 = 250;
        int x3 = 500;
        int grid = template.gridCount()/2;
        int igrid = 0;
        for (Display d:arr) {
        	if (d.addInfoOnly()) continue;
        	String str = code2.replaceAll("NAME", d.name());
        	str = str.replaceAll("TOP", top+"");
            igrid++;
            if (igrid==1 || igrid>grid) {
                top += 40;
            	str = str.replaceAll("XPOS", x1+"");
            }
            else {
            	if (igrid==2) {
                	str = str.replaceAll("XPOS", x2+"");
            	}
            	else {
                	str = str.replaceAll("XPOS", x3+"");
                	igrid=0;
            	}
            }
        	String label = PanelUtil.getLabel(d.name(), d);
        	str = str.replaceAll("LABEL", label);
            sb.append(str);
        }
        sb.append(code3);
        sb.append("\n\n");
        for (int i=0; i<arr.length; i++) {
        	Display d = arr[i];
        	if (d.addInfoOnly()) continue;
        	if (d.type().equals("PopSearch")) {
                sb.append("\t").append(d.name()).append(".inputPopSearch");
        	}
        	else {
                sb.append("\t").append(d.name()).append(".inputOnly");
        	}
        	if (i+1<arr.length) {
                sb.append(",");
        	}
            sb.append("\n");
        }
        sb.append(code4);
        txtCode.setText(sb.toString());
    }//GEN-LAST:event_btnCreateActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaFXGenerator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtBean;
    private javax.swing.JTextArea txtCode;
    private javax.swing.JTextPane txtOther;
    // End of variables declaration//GEN-END:variables

}
