/*
 * DicomViewerPanel.java
 *
 * Created on July 10, 2008, 7:40 PM
 */
package component;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

import com.pixelmed.dicom.DicomInputStream;

import util.DataUtil;
import util.ImageUtil;
import util.PanelUtil;
import util.ThreadPoolUtil;

import component.bean.DrawingUtil;

/**
 *
 * @author  Entokwaa
 */
public class DicomViewerPanel extends javax.swing.JPanel {

    double scale = 1;
    double zoomVal;
    int angle;
    float contrastVal = 0;
    int loupeWidth = 110;
    public File f;

    public static void main(String[] args) {
        final DicomViewerPanel viewer = new DicomViewerPanel();
        JFrame frame = new JFrame("TEST");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add(viewer);
        frame.pack();
        frame.setVisible(true);
    }

    /** Creates new form DicomViewerPanel */
    public DicomViewerPanel() {
        initComponents();
		pnlLoupe.setLayout(new GridBagLayout());
        try {
            PanelUtil.updateColor(this);
            PanelUtil.updateColor(jPanel1);
            PanelUtil.updateColor(jPanel3);
            PanelUtil.updateColor(pnlLoupe);
            PanelUtil.updateColor(canvasDicom);
            PanelUtil.updateColor(jLabel1);
            PanelUtil.updateColor(jLabel2);
        } catch (Exception e) {
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fileUploadDicom = new javax.swing.JFileChooser();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        pnl2DDicom = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbo2DTransparentLevel = new javax.swing.JComboBox();
        jPanel10 = new javax.swing.JPanel();
        btn2DRotateLeft = new javax.swing.JButton();
        btn2DRotateRight = new javax.swing.JButton();
        btn2DRotateCenter = new javax.swing.JButton();
        btn2DRotateTop = new javax.swing.JButton();
        btn2DRotateDown = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbo2DZoom = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        btn2DOpenSingle = new javax.swing.JButton();
        btn2DNewFrame = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        pnl2DLoupe = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt2DMetaData = new javax.swing.JTextArea();
        slid2DDicomSelection = new javax.swing.JSlider();
        jPanel6 = new javax.swing.JPanel();
        canvasDicom = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnNewFrame = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cboTransparentLevel = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        btnRotateLeft = new javax.swing.JButton();
        btnRotateRight = new javax.swing.JButton();
        btnRotateCenter = new javax.swing.JButton();
        btnRotateTop = new javax.swing.JButton();
        btnRotateDown = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cboThickness = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        btnCaptureScreens = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cboZoom = new javax.swing.JComboBox();
        btnRemoveAll = new javax.swing.JButton();
        btnEnableClip = new javax.swing.JButton();
        btnDisableClip = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlLoupe = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMetaData = new javax.swing.JTextArea();

        fileUploadDicom.setDialogTitle("Upload Dicom"); // NOI18N
        fileUploadDicom.setSelectedFile(new java.io.File("D:\\sample.dcm"));

        setLayout(new java.awt.GridLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(DicomViewerPanel.class);
        pnl2DDicom.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnl2DDicom.border.title"))); // NOI18N

        javax.swing.GroupLayout pnl2DDicomLayout = new javax.swing.GroupLayout(pnl2DDicom);
        pnl2DDicom.setLayout(pnl2DDicomLayout);
        pnl2DDicomLayout.setHorizontalGroup(
            pnl2DDicomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        pnl2DDicomLayout.setVerticalGroup(
            pnl2DDicomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );

        jTabbedPane3.setMaximumSize(new java.awt.Dimension(300, 32767));

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel9.setLayout(new java.awt.GridBagLayout());

        jLabel5.setText("Transparent:"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel9.add(jLabel5, gridBagConstraints);

        cbo2DTransparentLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbo2DTransparentLevel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo2DTransparentLevelItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel9.add(cbo2DTransparentLevel, gridBagConstraints);

        jPanel10.setLayout(new java.awt.GridBagLayout());

        btn2DRotateLeft.setText("<"); // NOI18N
        btn2DRotateLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2DRotateLeftActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel10.add(btn2DRotateLeft, gridBagConstraints);

        btn2DRotateRight.setText(">"); // NOI18N
        btn2DRotateRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2DRotateRightActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel10.add(btn2DRotateRight, gridBagConstraints);

        btn2DRotateCenter.setText("(.)"); // NOI18N
        btn2DRotateCenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2DRotateCenterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel10.add(btn2DRotateCenter, gridBagConstraints);

        btn2DRotateTop.setText("^"); // NOI18N
        btn2DRotateTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2DRotateTopActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel10.add(btn2DRotateTop, gridBagConstraints);

        btn2DRotateDown.setText("v"); // NOI18N
        btn2DRotateDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2DRotateDownActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel10.add(btn2DRotateDown, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel9.add(jPanel10, gridBagConstraints);

        jLabel7.setText("Rotate:"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel9.add(jLabel7, gridBagConstraints);

        jLabel8.setText("Zoom:"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel9.add(jLabel8, gridBagConstraints);

        cbo2DZoom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "1.8", "1.9", "2.0" }));
        cbo2DZoom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo2DZoomItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel9.add(cbo2DZoom, gridBagConstraints);

        jPanel7.setLayout(new java.awt.GridLayout());

        btn2DOpenSingle.setText(resourceMap.getString("btn2DOpenSingle.text")); // NOI18N
        btn2DOpenSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2DOpenSingleActionPerformed(evt);
            }
        });
        jPanel7.add(btn2DOpenSingle);

        btn2DNewFrame.setText("Open Series"); // NOI18N
        btn2DNewFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2DNewFrameActionPerformed(evt);
            }
        });
        jPanel7.add(btn2DNewFrame);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel9.add(jPanel7, gridBagConstraints);

        jPanel8.add(jPanel9, java.awt.BorderLayout.NORTH);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout pnl2DLoupeLayout = new javax.swing.GroupLayout(pnl2DLoupe);
        pnl2DLoupe.setLayout(pnl2DLoupeLayout);
        pnl2DLoupeLayout.setHorizontalGroup(
            pnl2DLoupeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );
        pnl2DLoupeLayout.setVerticalGroup(
            pnl2DLoupeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(pnl2DLoupe);

        jPanel8.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jTabbedPane3.addTab(resourceMap.getString("jPanel8.TabConstraints.tabTitle"), jPanel8); // NOI18N

        jPanel11.setLayout(new java.awt.GridLayout());

        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder("Patient's Metadata"));

        txt2DMetaData.setColumns(20);
        txt2DMetaData.setEditable(false);
        txt2DMetaData.setRows(5);
        jScrollPane4.setViewportView(txt2DMetaData);

        jPanel11.add(jScrollPane4);

        jTabbedPane3.addTab(resourceMap.getString("jPanel11.TabConstraints.tabTitle"), jPanel11); // NOI18N

        slid2DDicomSelection.setPaintLabels(true);
        slid2DDicomSelection.setPaintTicks(true);
        slid2DDicomSelection.setSnapToTicks(true);
        slid2DDicomSelection.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("slid2DDicomSelection.border.title"))); // NOI18N
        slid2DDicomSelection.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slid2DDicomSelectionStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slid2DDicomSelection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl2DDicom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(pnl2DDicom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slid2DDicomSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane2.addTab(resourceMap.getString("jPanel5.TabConstraints.tabTitle"), jPanel5); // NOI18N

        canvasDicom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canvasDicomMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout canvasDicomLayout = new javax.swing.GroupLayout(canvasDicom);
        canvasDicom.setLayout(canvasDicomLayout);
        canvasDicomLayout.setHorizontalGroup(
            canvasDicomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        canvasDicomLayout.setVerticalGroup(
            canvasDicomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(300, 32767));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridBagLayout());

        btnNewFrame.setText("Open Series"); // NOI18N
        btnNewFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewFrameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel4.add(btnNewFrame, gridBagConstraints);

        jLabel4.setText("Transparent:"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(jLabel4, gridBagConstraints);

        cboTransparentLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cboTransparentLevel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTransparentLevelItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(cboTransparentLevel, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        btnRotateLeft.setText("<"); // NOI18N
        btnRotateLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRotateLeftActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel3.add(btnRotateLeft, gridBagConstraints);

        btnRotateRight.setText(">"); // NOI18N
        btnRotateRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRotateRightActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel3.add(btnRotateRight, gridBagConstraints);

        btnRotateCenter.setText("(.)"); // NOI18N
        btnRotateCenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRotateCenterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel3.add(btnRotateCenter, gridBagConstraints);

        btnRotateTop.setText("^"); // NOI18N
        btnRotateTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRotateTopActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(btnRotateTop, gridBagConstraints);

        btnRotateDown.setText("v"); // NOI18N
        btnRotateDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRotateDownActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(btnRotateDown, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jPanel3, gridBagConstraints);

        jLabel1.setText("Thickness:"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(jLabel1, gridBagConstraints);

        cboThickness.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        cboThickness.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboThicknessItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(cboThickness, gridBagConstraints);

        jLabel2.setText("Rotate:"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(jLabel2, gridBagConstraints);

        btnCaptureScreens.setText("Capture Screens"); // NOI18N
        btnCaptureScreens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaptureScreensActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(btnCaptureScreens, gridBagConstraints);

        jLabel3.setText("Zoom:"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(jLabel3, gridBagConstraints);

        cboZoom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "1.8", "1.9", "2.0" }));
        cboZoom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboZoomItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(cboZoom, gridBagConstraints);

        btnRemoveAll.setText(resourceMap.getString("btnRemoveAll.text")); // NOI18N
        btnRemoveAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveAllActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(btnRemoveAll, gridBagConstraints);

        btnEnableClip.setText("Enable Clip"); // NOI18N
        btnEnableClip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnableClipActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(btnEnableClip, gridBagConstraints);

        btnDisableClip.setText("Disable Clip"); // NOI18N
        btnDisableClip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisableClipActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(btnDisableClip, gridBagConstraints);

        jPanel1.add(jPanel4, java.awt.BorderLayout.NORTH);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout pnlLoupeLayout = new javax.swing.GroupLayout(pnlLoupe);
        pnlLoupe.setLayout(pnlLoupeLayout);
        pnlLoupeLayout.setHorizontalGroup(
            pnlLoupeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );
        pnlLoupeLayout.setVerticalGroup(
            pnlLoupeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnlLoupe);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Toolbar", jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Patient's Metadata"));

        txtMetaData.setColumns(20);
        txtMetaData.setEditable(false);
        txtMetaData.setRows(5);
        jScrollPane2.setViewportView(txtMetaData);

        jPanel2.add(jScrollPane2);

        jTabbedPane1.addTab("Meta Data", jPanel2);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(canvasDicom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(canvasDicom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane2.addTab(resourceMap.getString("jPanel6.TabConstraints.tabTitle"), jPanel6); // NOI18N

        add(jTabbedPane2);
    }// </editor-fold>//GEN-END:initComponents

    private void canvasDicomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasDicomMouseClicked
    int x = evt.getX();
    int y = evt.getY();
    double xval = x - loupeWidth/2;
    double yval = y - loupeWidth/2;
    if (xval<0) xval=0;
    if (yval<0) yval=0;
//    System.out.println("X:Y = "+xval+":"+yval);
//    imgLoupe = imgManipulated.getSubimage((int)xval, (int)yval, loupeWidth, loupeWidth);
//    pnlLoupe.repaint();
}//GEN-LAST:event_canvasDicomMouseClicked

Dicom3DViewer dicom;
private void btnNewFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewFrameActionPerformed
    if (fileUploadDicom.showOpenDialog(btnNewFrame)==JFileChooser.APPROVE_OPTION) {
        f = fileUploadDicom.getSelectedFile();
        if (dicom!=null) {
        	dicom.setVisible(false);
            dicom.canvas.invalidate();
            dicom.univ.cleanup();
        }
        setVisible(false);
        canvasDicom.setVisible(false);
        canvasDicom.removeAll();
        canvasDicom.updateUI();
        
        SwingUtilities.invokeLater(new Runnable() {
			@Override
			public void run() {
		        dicom = new Dicom3DViewer(f);
		        canvasDicom.setLayout(new BorderLayout());
		        canvasDicom.add(dicom, BorderLayout.CENTER);
		        canvasDicom.updateUI();
		        canvasDicom.setVisible(true);
		        dicom.setVisible(true);
		        setVisible(true);
			}
        });
        setVisible(true);
    }
}//GEN-LAST:event_btnNewFrameActionPerformed

int oldIndex;
private void cboTransparentLevelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTransparentLevelItemStateChanged
	int index = cboTransparentLevel.getSelectedIndex()+1;
	if (oldIndex==index) {
		return;
	}
	oldIndex = index;
	dicom.makeTransparentLevel(index);
}//GEN-LAST:event_cboTransparentLevelItemStateChanged

private void btnRotateTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRotateTopActionPerformed
    dicom.rotateTop();
}//GEN-LAST:event_btnRotateTopActionPerformed

private void btnRotateLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRotateLeftActionPerformed
    dicom.rotateLeft();
}//GEN-LAST:event_btnRotateLeftActionPerformed

private void btnRotateCenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRotateCenterActionPerformed
    dicom.rotateCenter();
}//GEN-LAST:event_btnRotateCenterActionPerformed

private void btnRotateRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRotateRightActionPerformed
    dicom.rotateRight();
}//GEN-LAST:event_btnRotateRightActionPerformed

private void btnRotateDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRotateDownActionPerformed
    dicom.rotateDown();
}//GEN-LAST:event_btnRotateDownActionPerformed

private void cboThicknessItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboThicknessItemStateChanged
	int i = cboThickness.getSelectedIndex()+1;
	dicom.showThickness(i);
}//GEN-LAST:event_cboThicknessItemStateChanged

private void btnCaptureScreensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaptureScreensActionPerformed
	dicom.captureScreens(pnlLoupe, 200);
}//GEN-LAST:event_btnCaptureScreensActionPerformed

private void cboZoomItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboZoomItemStateChanged
	String i = cboZoom.getSelectedItem().toString();
	double d = Double.parseDouble(i);
	dicom.showZoom(d);
}//GEN-LAST:event_cboZoomItemStateChanged

private void btnRemoveAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveAllActionPerformed
	pnlLoupe.removeAll();
	pnlLoupe.updateUI();
}//GEN-LAST:event_btnRemoveAllActionPerformed

private void btnEnableClipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnableClipActionPerformed
    dicom.enableClip();
}//GEN-LAST:event_btnEnableClipActionPerformed

private void btnDisableClipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisableClipActionPerformed
    dicom.disableClip();
}//GEN-LAST:event_btnDisableClipActionPerformed

private void btn2DNewFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2DNewFrameActionPerformed
    if (fileUploadDicom.showOpenDialog(btn2DNewFrame)==JFileChooser.APPROVE_OPTION) {
        f = fileUploadDicom.getSelectedFile();
        File folder = f.getParentFile();
        File[] flst = folder.listFiles();
        pnl2DLoupe.removeAll();
        pnl2DLoupe.setLayout(new GridBagLayout());
        GridBagConstraints con = new GridBagConstraints();
        con.ipadx = con.ipady = 2;
        for (File file:flst) {
			try {
//				DicomInputStream d = new DicomInputStream(file);
//				BufferedImage newImage = ImageUtil.getTransparentImageRemoveNoise((BufferedImage) ImageUtil.getImageFromStream(d), Color.BLACK);
				JLabel lbl = new DicomIcon(file, 75,75, this.pnl2DDicom);
				pnl2DLoupe.add(lbl, con);
				if (con.gridx>=2) {
					con.gridx=-1;
					con.gridy++;
				}
				con.gridx++;
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
        }
        slid2DDicomSelection.setMaximum(flst.length);
        pnl2DLoupe.updateUI();
    }

}//GEN-LAST:event_btn2DNewFrameActionPerformed

private void cbo2DTransparentLevelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo2DTransparentLevelItemStateChanged
    JLabel lbl = (JLabel) pnl2DDicom.getComponent(0);
    DicomIcon icon = (DicomIcon) lbl.getLabelFor();
    icon.transparentLevel = cbo2DTransparentLevel.getSelectedIndex()+1;
    icon.displayImage();
}//GEN-LAST:event_cbo2DTransparentLevelItemStateChanged

private void btn2DRotateLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2DRotateLeftActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_btn2DRotateLeftActionPerformed

private void btn2DRotateRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2DRotateRightActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_btn2DRotateRightActionPerformed

private void btn2DRotateCenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2DRotateCenterActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_btn2DRotateCenterActionPerformed

private void btn2DRotateTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2DRotateTopActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_btn2DRotateTopActionPerformed

private void btn2DRotateDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2DRotateDownActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_btn2DRotateDownActionPerformed

private void cbo2DZoomItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo2DZoomItemStateChanged
    JLabel lbl = (JLabel) pnl2DDicom.getComponent(0);
    DicomIcon icon = (DicomIcon) lbl.getLabelFor();
    double iconWidth = icon.img.getWidth() * 1.0d;
    int wh = (int) (iconWidth*DataUtil.getDoubleValue(cbo2DZoom.getSelectedItem().toString()));
    icon.displayImage(wh);
}//GEN-LAST:event_cbo2DZoomItemStateChanged

private void slid2DDicomSelectionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slid2DDicomSelectionStateChanged
	int n = slid2DDicomSelection.getValue();
	try {
		DicomIcon icon = (DicomIcon) pnl2DLoupe.getComponent(n);
		icon.displayImage();
	}
	catch (Exception e) {
	}
}//GEN-LAST:event_slid2DDicomSelectionStateChanged

private void btn2DOpenSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2DOpenSingleActionPerformed
    if (fileUploadDicom.showOpenDialog(btn2DNewFrame)==JFileChooser.APPROVE_OPTION) {
        f = fileUploadDicom.getSelectedFile();
        pnl2DLoupe.removeAll();
        pnl2DLoupe.setLayout(new GridBagLayout());
        GridBagConstraints con = new GridBagConstraints();
        con.ipadx = con.ipady = 2;
		try {
//			DicomInputStream d = new DicomInputStream(f);
//			BufferedImage newImage = ImageUtil.getTransparentImageRemoveNoise((BufferedImage) ImageUtil.getImageFromStream(d), Color.BLACK);
			JLabel lbl = new DicomIcon(f, 200, 200, this.pnl2DDicom);
			pnl2DLoupe.add(lbl, con);
			if (con.gridx>=2) {
				con.gridx=-1;
				con.gridy++;
			}
			con.gridx++;
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		slid2DDicomSelection.setMaximum(1);
        pnl2DLoupe.updateUI();
    }
}//GEN-LAST:event_btn2DOpenSingleActionPerformed

static class DicomIcon extends JLabel {
	BufferedImage img;
	JPanel pnl;
	int useWidth;
	int transparentLevel;
	DicomInputStream d;
	BufferedImage newImage;
	
	private class Runner implements Runnable {
		DicomIcon icon;
		File file;
		int width;
		int height;
		JPanel pnl;
		Runner(DicomIcon icon, File file, int width, int height, JPanel pnl) {
			this.icon = icon;
			this.file = file;
			this.width = width;
			this.height = height;
			this.pnl = pnl;
		}

		@Override
		public void run() {
			try {
//				PanelUtil.showWaitFrame("Loading images please wait.");
				DicomInputStream d = new DicomInputStream(file);
				icon.img = ImageUtil.getTransparentImageRemoveNoise((BufferedImage) ImageUtil.getImageFromStream(d), Color.BLACK);
				icon.useWidth = icon.img.getWidth();
				icon.setIcon(new ImageIcon(ImageUtil.resize(img, width, height)));
				icon.setPreferredSize(new Dimension(width, height));
				icon.addMouseListener(new MouseAdapter() {
					@Override
					public void mouseClicked(MouseEvent arg0) {
						displayImage();
					}
				});
//				PanelUtil.hideWaitFrame();
			}
			catch (Exception e) {
			}
		}
	}
	
	DicomIcon(File file, int width, int height, JPanel pnl) {
		this.pnl = pnl;
		Runner r = new Runner(this, file, width, height, pnl);
		ThreadPoolUtil.execute(r);
	}

	protected void displayImage() {
		displayImage(useWidth);
	}
	
	protected void displayImage(int width) {
		BufferedImage tmp = null;
		try {
			tmp = ImageUtil.getTransparentImage(ImageUtil.copy(img), Color.BLACK);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		tmp = ImageUtil.resize(tmp, width, width);
		ImageUtil.transparentDarkPixel(tmp, transparentLevel);
		pnl.removeAll();
		pnl.setLayout(new GridBagLayout());
		JLabel lbl = new JLabel();
		lbl.setIcon(new ImageIcon(tmp));
		lbl.setPreferredSize(new Dimension(width, width));
		lbl.setLabelFor(this);
		pnl.add(lbl);
		pnl.updateUI();
	}
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn2DNewFrame;
    private javax.swing.JButton btn2DOpenSingle;
    private javax.swing.JButton btn2DRotateCenter;
    private javax.swing.JButton btn2DRotateDown;
    public javax.swing.JButton btn2DRotateLeft;
    private javax.swing.JButton btn2DRotateRight;
    public javax.swing.JButton btn2DRotateTop;
    private javax.swing.JButton btnCaptureScreens;
    private javax.swing.JButton btnDisableClip;
    private javax.swing.JButton btnEnableClip;
    private javax.swing.JButton btnNewFrame;
    private javax.swing.JButton btnRemoveAll;
    private javax.swing.JButton btnRotateCenter;
    private javax.swing.JButton btnRotateDown;
    public javax.swing.JButton btnRotateLeft;
    private javax.swing.JButton btnRotateRight;
    public javax.swing.JButton btnRotateTop;
    private javax.swing.JPanel canvasDicom;
    private javax.swing.JComboBox cbo2DTransparentLevel;
    private javax.swing.JComboBox cbo2DZoom;
    private javax.swing.JComboBox cboThickness;
    private javax.swing.JComboBox cboTransparentLevel;
    private javax.swing.JComboBox cboZoom;
    private javax.swing.JFileChooser fileUploadDicom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JPanel pnl2DDicom;
    private javax.swing.JPanel pnl2DLoupe;
    private javax.swing.JPanel pnlLoupe;
    private javax.swing.JSlider slid2DDicomSelection;
    private javax.swing.JTextArea txt2DMetaData;
    private javax.swing.JTextArea txtMetaData;
    // End of variables declaration//GEN-END:variables
}
