/*
 * DicomViewerPanel.java
 *
 * Created on July 10, 2008, 7:40 PM
 */
package component;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;

import template.screen.TransactionPanel;
import util.PanelUtil;

/**
 *
 * @author  Entokwaa
 */
public class MultiDicomViewerPanel extends TransactionPanel {
    int activeDicom;

    byte[] dicomByteArray;
    File[] files;

    public byte[] getDicomByteArray() {
        return dicomByteArray;
    }

    public void setDicomByteArray(byte[] dicomByteArray) {
//        this.dicomByteArray = dicomByteArray;
//        if (dicomByteArray == null) {
//            return;
//        }
//        try {
//            ByteArrayInputStream bais = new ByteArrayInputStream(dicomByteArray);
//            ObjectInputStream ois = new ObjectInputStream(bais);
//            List<byte[]> lst = (List<byte[]>) ois.readObject();
//            lstDicom.clear();
//            for (byte[] bs : lst) {
//                DicomViewerPanel pnl = new DicomViewerPanel();
//                pnl.setDicomByteArray(bs);
//                lstDicom.add(pnl);
//            }
//            reDisplayDicoms();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }

    public static void main(String[] args) {
        MultiDicomViewerPanel viewer = new MultiDicomViewerPanel();
        JFrame frame = new JFrame("TEST");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add(viewer);
        frame.pack();
        frame.setVisible(true);
    }

    public void setTitle(String title) {
//    	dlgToolbar.setTitle(title);
    }
    
    /** Creates new form DicomViewerPanel */
    public MultiDicomViewerPanel() {
    	this("");
    }

    public MultiDicomViewerPanel(String title) {
        initComponents();
//        slidMove.setMaximum(1);
    	try {
    		PanelUtil.updateColor(this);
    		PanelUtil.updateColor(jPanel3);
    		PanelUtil.updateColor(pnlDicomPanel);
    		PanelUtil.updateColor(pnlLoupe);
    		PanelUtil.updateColor(pnlToolbar);
    		PanelUtil.updateColor(jPanel1);
    		PanelUtil.updateColor(jPanel2);
    		PanelUtil.updateColor(jPanel3);
    		PanelUtil.updateColor(jPanel4);
    		PanelUtil.updateColor(jPanel5);
    	}
    	catch (Exception e) {
    	}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fileUploadDicom = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        pnlToolbar = new javax.swing.JPanel();
        pnlLoupe = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnNewFrame = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMetaData = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        pnlDicomPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        slidMove = new javax.swing.JSlider();

        fileUploadDicom.setDialogTitle("Upload Dicom"); // NOI18N
        fileUploadDicom.setSelectedFile(new java.io.File("D:\\sample.dcm"));

        setPreferredSize(new java.awt.Dimension(900, 700));
        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(250, 32767));

        jPanel1.setLayout(new java.awt.BorderLayout());

        pnlToolbar.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(pnlToolbar, java.awt.BorderLayout.NORTH);

        pnlLoupe.setLayout(new java.awt.GridLayout(1, 0, 0, 15));
        jPanel1.add(pnlLoupe, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        btnNewFrame.setText("Open Series"); // NOI18N
        btnNewFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewFrameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 6);
        jPanel3.add(btnNewFrame, gridBagConstraints);

        jPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        jTabbedPane1.addTab("Toolbar", jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Patient's Meta Data"));

        txtMetaData.setColumns(20);
        txtMetaData.setEditable(false);
        txtMetaData.setRows(5);
        jScrollPane2.setViewportView(txtMetaData);

        jPanel2.add(jScrollPane2);

        jTabbedPane1.addTab("Meta Data", jPanel2);

        add(jTabbedPane1, java.awt.BorderLayout.EAST);

        jPanel4.setLayout(new java.awt.BorderLayout());

        pnlDicomPanel.setLayout(new java.awt.GridLayout(1, 0));
        jPanel4.add(pnlDicomPanel, java.awt.BorderLayout.CENTER);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Frame"));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        slidMove.setMaximum(1);
        slidMove.setValue(0);
        slidMove.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slidMoveStateChanged(evt);
            }
        });
        jPanel5.add(slidMove);

        jPanel4.add(jPanel5, java.awt.BorderLayout.SOUTH);

        add(jPanel4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void btnNewFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewFrameActionPerformed
	fileUploadDicom.setMultiSelectionEnabled(true);
	if (fileUploadDicom.showOpenDialog(btnNewFrame)==JFileChooser.APPROVE_OPTION) {
		files = fileUploadDicom.getSelectedFiles();
        reDisplayDicoms();
        slidMove.setMaximum(files.length-1);
    }
}//GEN-LAST:event_btnNewFrameActionPerformed

private void slidMoveStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slidMoveStateChanged
//	int index = slidMove.getValue();
//	DicomViewerPanel dicom = lstDicom.get(index);
//    pnlLoupe.removeAll();
//    pnlLoupe.add(dicom.getPnlLoupe());
//
//    pnlToolbar.removeAll();
//    pnlToolbar.add(dicom.getPnlToolbar());
//    try {
//        txtMetaData.setText(dicom.obj.toString());
//    }
//    catch (Exception ex) {
//    }
//    pnlLoupe.updateUI();
//    pnlToolbar.updateUI();
//    activeDicom = index;	
}//GEN-LAST:event_slidMoveStateChanged

private void reDisplayDicoms() {        
        pnlLoupe.removeAll();
        pnlLoupe.setLayout(new GridLayout(0, 3));
        for (int i = 0; i < files.length; i++) {
        	File f = files[i];
        	JButton btnNew = new JButton();
//            btnNew.setIcon(new javax.swing.ImageIcon(f)); // NOI18N
            btnNew.setText(f.getName()); // NOI18N
            btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            btnNew.setName(f.getName()); // NOI18N
            btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            btnNew.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    changeDisplay(evt);
                }
            });
            pnlLoupe.add(btnNew);
        }
        pnlLoupe.updateUI();
		PanelUtil.updateColor(pnlLoupe);
}

protected void changeDisplay(ActionEvent evt) {
	// TODO Auto-generated method stub
	
}

static class MouseListenerDicom extends MouseAdapter {
        MultiDicomViewerPanel multi;
        DicomViewerPanel dicom;
        int index;

        private MouseListenerDicom(DicomViewerPanel dicom, MultiDicomViewerPanel multi, int index) {
            this.dicom = dicom;
            this.multi = multi;
            this.index = index;
        }

        @Override
        public void mouseClicked(MouseEvent e) {
        }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewFrame;
    private javax.swing.JFileChooser fileUploadDicom;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnlDicomPanel;
    private javax.swing.JPanel pnlLoupe;
    private javax.swing.JPanel pnlToolbar;
    private javax.swing.JSlider slidMove;
    private javax.swing.JTextArea txtMetaData;
    // End of variables declaration//GEN-END:variables
}
