/*
 * BarChartPallete.java
 *
 * Created on February 3, 2008, 2:26 PM
 */

package component;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.gantt.TaskSeriesCollection;

/**
 *
 * @author  Entokwaa
 */
public class GanttChartPallete extends javax.swing.JPanel {

    String title = "3D Bar Chart";
    String xTitle = "Category";
    String yTitle = "Value";
    int chartType;
    TaskSeriesCollection data;

    public void setData(TaskSeriesCollection data) {
        this.data = data;
    }
    
    public TaskSeriesCollection getData() {
        return data;
    }

    public void refresh() {
        displayChart();
    }

    public int getChartType() {
        return chartType;
    }

    public void setChartType(int chartType) {
        this.chartType = chartType;
        displayChart();
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
        displayChart();
    }

    public String getXTitle() {
        return xTitle;
    }

    public void setXTitle(String xTitle) {
        this.xTitle = xTitle;
        displayChart();
    }

    public String getYTitle() {
        return yTitle;
    }

    public void setYTitle(String yTitle) {
        this.yTitle = yTitle;
        displayChart();
    }

    /** Creates new form BarChartPallete */
    public GanttChartPallete() {
        initComponents();
        displayChart();
    }

    public GanttChartPallete(String title, TaskSeriesCollection data) {
        initComponents();
        this.data = data;
        this.title = title;
        displayChart();
    }

    private void displayChart() {
        if (data==null) data = createDataset();
        JFreeChart chart = createChart(data);
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new java.awt.Dimension(500, 270));
        removeAll();
        add(chartPanel);
    }

    private TaskSeriesCollection createDataset() {
        return data;
    }

    private JFreeChart createChart(TaskSeriesCollection dataset) {
        JFreeChart chart = ChartFactory.createGanttChart(title, xTitle, yTitle, dataset, true, true, false);
        return chart;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
