/*
 * StudentRecordForm.java
 *
 * Created on March 11, 2009, 4:48 PM
 */

package ui;

import bean.Admission;
import bean.extension.AdmissionRequirements1Ext;
import bean.Enrollment;
import bean.Student;
import component.JTextFieldPallete;
import java.awt.Color;
import java.util.List;

import service.util.AbstractIBean;
import springbean.AAAConfig;
import template.screen.TransactionPanel;
import util.DBClient;
import util.PanelUtil;

/**
 *
 * @author  Charliemagne Mark
 */
public class StudentRecordForm extends TransactionPanel {
    public static void main(String[] args) {
        java.awt.Color clr = new java.awt.Color(44, 117, 44);
        constants.Constants.panelBackground = clr;
        constants.Constants.labelColor = Color.WHITE;
        AAAConfig.getInstance();
        PanelUtil.displayToFrame(new StudentRecordForm());
    }
    
    Student stud;
    protected void cancelUpdate() {
        setupData(stud);
    }

    @Override
    public void saveRecord() {
        pnlStudentInfo.getBean().save();

        pnlFather.getBean().save();
        pnlMother.getBean().save();
        pnlGuardian.getBean().save();
        
        AdmissionRequirements1Ext req = (AdmissionRequirements1Ext) pnlAdmissionInfo1.getBean();
        if (req!=null && !req.isEmptyKey()) {
//            update only
            req.save();
        }

        Enrollment lastEnroll = (Enrollment) pnlStudentStatus.getBean();
        if (lastEnroll!=null && !lastEnroll.isEmptyKey()) {
//            update only
            lastEnroll.save();
        }
    }

    protected void setupData(List lst) {
        stud = (Student) lst.get(0);
        setupData(stud);
    }
    
    private void setupData(Student stud) {
        pnlStudentInfo.setBean(stud);
        pnlBusOperator.setBean(stud);
        pnlHomeDetails.setBean(stud);
        pnlStudentInfoPanel.setBean(stud);
        pnlStudentSchoolAttended.setBean(stud);
        pnlCurriculumSubject.setBean(stud);

        //setup the father info
        pnlFather.setBean(stud.extractOrCreateDependent("FATHER"));
        pnlMother.setBean(stud.extractOrCreateDependent("MOTHER"));
        pnlGuardian.setBean(stud.extractOrCreateDependent("GUARDIAN"));
        
        Admission req = (Admission) AbstractIBean.firstRecord("SELECT a FROM Admission a WHERE a.personId="+stud.personId);
        pnlAdmissionInfo1.setBean(req);
        pnlAdmissionInfo2.setBean(req);

        Enrollment lastEnroll = (Enrollment) stud.selectFirstCache("SELECT a FROM Enrollment a WHERE a.studentId="+stud.personId+" ORDER BY a.seq DESC");
        pnlStudentStatus.setBean(lastEnroll);
        pnlStudentStatusSchoolDetail.setBean(lastEnroll);
        pnlStudentStatusTuitionDetail.setBean(lastEnroll);
        
        pnlFinalGradeInfo.setBean(lastEnroll);
        pnlFinalGradeAverage.setBean(lastEnroll);
    }
    /** Creates new form StudentRecordForm */
    public StudentRecordForm() {
        initComponents();
        //update color of the panel used
        PanelUtil.updateColor(pnlAdmissionRequirement);
        PanelUtil.updateColor(pnlEnrollmentInfo);
        PanelUtil.updateColor(pnlParentInfo);
        PanelUtil.updateColor(pnlPersonalInfo);
        PanelUtil.updateColor(pnlStudent);
        PanelUtil.updateColor(pnlStudentStatusSchoolDetail);
        PanelUtil.updateColor(pnlStudentStatusTuitionDetail);
        PanelUtil.updateColor(pnlSchoolAttended);
        PanelUtil.updateColor(pnlStudentCurriculumSubject);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlStudent = new javax.swing.JPanel();
        pnlStudentInfo = new component.BeanPanelPallete();
        jPanel1 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlPersonalInfo = new javax.swing.JPanel();
        pnlStudentInfoPanel = new component.BeanPanelPallete();
        pnlBusOperator = new component.BeanPanelPallete();
        pnlHomeDetails = new component.BeanPanelPallete();
        pnlParentInfo = new javax.swing.JPanel();
        pnlFather = new component.BeanPanelPallete();
        pnlMother = new component.BeanPanelPallete();
        pnlGuardian = new component.BeanPanelPallete();
        pnlAdmissionRequirement = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        pnlAdmissionInfo1 = new component.BeanPanelPallete();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnlAdmissionInfo2 = new component.BeanPanelPallete();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlEnrollmentInfo = new javax.swing.JPanel();
        pnlStudentStatus = new component.BeanPanelPallete();
        pnlStudentStatusSchoolDetail = new component.BeanPanelPallete();
        pnlStudentStatusTuitionDetail = new component.BeanPanelPallete();
        pnlFinalGrade = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        pnlFinalGradeInfo = new component.BeanPanelPallete();
        pnlFinalGradeAverage = new component.BeanPanelPallete();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtSearchSchoolYear = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pnlSchoolAttended = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        pnlStudentSchoolAttended = new component.BeanPanelPallete();
        pnlStudentCurriculumSubject = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        pnlCurriculumSubject = new component.BeanPanelPallete();
        jPanel5 = new javax.swing.JPanel();
        txtSearchField = new JTextFieldPallete();
        btnSearchNow = new javax.swing.JButton();

        setBackground(new java.awt.Color(44, 117, 44));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setLayout(new java.awt.GridBagLayout());

        pnlStudent.setBackground(new java.awt.Color(44, 117, 44));
        pnlStudent.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Personal Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlStudent.setName("pnlStudent"); // NOI18N
        pnlStudent.setLayout(new java.awt.GridBagLayout());

        pnlStudentInfo.setBeanName("StudentPersonalInfoExt");
        pnlStudentInfo.setName("pnlStudentInfo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        pnlStudent.add(pnlStudentInfo, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(44, 117, 44));
        jPanel1.setName("jPanel1"); // NOI18N

        btnSave.setBackground(new java.awt.Color(44, 117, 44));
        btnSave.setText("Save");
        btnSave.setName("btnSave"); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave);

        btnCancel.setBackground(new java.awt.Color(44, 117, 44));
        btnCancel.setText("Cancel/Update");
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlStudent.add(jPanel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        add(pnlStudent, gridBagConstraints);

        jTabbedPane1.setBackground(new java.awt.Color(44, 117, 44));
        jTabbedPane1.setForeground(new java.awt.Color(51, 51, 51));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane1.setAlignmentX(0.0F);
        jTabbedPane1.setAlignmentY(0.0F);
        jTabbedPane1.setName(""); // NOI18N

        pnlPersonalInfo.setBackground(new java.awt.Color(44, 117, 44));
        pnlPersonalInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlPersonalInfo.setName("pnlPersonalInfo"); // NOI18N
        pnlPersonalInfo.setLayout(new java.awt.GridBagLayout());

        pnlStudentInfoPanel.setBackground(new java.awt.Color(44, 117, 44));
        pnlStudentInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlStudentInfoPanel.setBeanName("StudentInfoExt"); // NOI18N
        pnlStudentInfoPanel.setName("pnlStudentInfoPanel"); // NOI18N

        javax.swing.GroupLayout pnlStudentInfoPanelLayout = new javax.swing.GroupLayout(pnlStudentInfoPanel);
        pnlStudentInfoPanel.setLayout(pnlStudentInfoPanelLayout);
        pnlStudentInfoPanelLayout.setHorizontalGroup(
            pnlStudentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlStudentInfoPanelLayout.setVerticalGroup(
            pnlStudentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlPersonalInfo.add(pnlStudentInfoPanel, gridBagConstraints);

        pnlBusOperator.setBackground(new java.awt.Color(44, 117, 44));
        pnlBusOperator.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bus Operator", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlBusOperator.setBeanName("BusOperatorExt");
        pnlBusOperator.setName("beanPanelPallete11"); // NOI18N

        javax.swing.GroupLayout pnlBusOperatorLayout = new javax.swing.GroupLayout(pnlBusOperator);
        pnlBusOperator.setLayout(pnlBusOperatorLayout);
        pnlBusOperatorLayout.setHorizontalGroup(
            pnlBusOperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlBusOperatorLayout.setVerticalGroup(
            pnlBusOperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlPersonalInfo.add(pnlBusOperator, gridBagConstraints);

        pnlHomeDetails.setBackground(new java.awt.Color(44, 117, 44));
        pnlHomeDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Home Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlHomeDetails.setBeanName("HomeDetailsExt");
        pnlHomeDetails.setName("beanPanelPallete12"); // NOI18N

        javax.swing.GroupLayout pnlHomeDetailsLayout = new javax.swing.GroupLayout(pnlHomeDetails);
        pnlHomeDetails.setLayout(pnlHomeDetailsLayout);
        pnlHomeDetailsLayout.setHorizontalGroup(
            pnlHomeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlHomeDetailsLayout.setVerticalGroup(
            pnlHomeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlPersonalInfo.add(pnlHomeDetails, gridBagConstraints);

        jTabbedPane1.addTab("Personal Info", pnlPersonalInfo);

        pnlParentInfo.setBackground(new java.awt.Color(44, 117, 44));
        pnlParentInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parent's Background", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlParentInfo.setName("pnlParentInfo"); // NOI18N
        pnlParentInfo.setLayout(new java.awt.GridLayout(3, 0));

        pnlFather.setBackground(new java.awt.Color(44, 117, 44));
        pnlFather.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Father's Profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlFather.setBeanName("PersonDependentFatherExt"); // NOI18N
        pnlFather.setName("pnlFather"); // NOI18N

        javax.swing.GroupLayout pnlFatherLayout = new javax.swing.GroupLayout(pnlFather);
        pnlFather.setLayout(pnlFatherLayout);
        pnlFatherLayout.setHorizontalGroup(
            pnlFatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        pnlFatherLayout.setVerticalGroup(
            pnlFatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        pnlParentInfo.add(pnlFather);

        pnlMother.setBackground(new java.awt.Color(44, 117, 44));
        pnlMother.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mother's Profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlMother.setBeanName("PersonDependentMotherExt");
        pnlMother.setName("pnlMother"); // NOI18N

        javax.swing.GroupLayout pnlMotherLayout = new javax.swing.GroupLayout(pnlMother);
        pnlMother.setLayout(pnlMotherLayout);
        pnlMotherLayout.setHorizontalGroup(
            pnlMotherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        pnlMotherLayout.setVerticalGroup(
            pnlMotherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        pnlParentInfo.add(pnlMother);

        pnlGuardian.setBackground(new java.awt.Color(44, 117, 44));
        pnlGuardian.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Guardian's Profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlGuardian.setBeanName("PersonDependentGuardianExt");
        pnlGuardian.setName("pnlGuardian"); // NOI18N

        javax.swing.GroupLayout pnlGuardianLayout = new javax.swing.GroupLayout(pnlGuardian);
        pnlGuardian.setLayout(pnlGuardianLayout);
        pnlGuardianLayout.setHorizontalGroup(
            pnlGuardianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        pnlGuardianLayout.setVerticalGroup(
            pnlGuardianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        pnlParentInfo.add(pnlGuardian);

        jTabbedPane1.addTab("Parent's Info", pnlParentInfo);

        pnlAdmissionRequirement.setBackground(new java.awt.Color(44, 117, 44));
        pnlAdmissionRequirement.setName("pnlAdmissionRequirement"); // NOI18N
        pnlAdmissionRequirement.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBackground(new java.awt.Color(44, 117, 44));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Admission Requirements", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setEnabled(false);
        jPanel2.setFocusable(false);
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setBackground(new java.awt.Color(44, 117, 44));
        jPanel4.setName("jPanel4"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);

        pnlAdmissionInfo1.setBackground(new java.awt.Color(44, 117, 44));
        pnlAdmissionInfo1.setBeanName("AdmissionRequirements1Ext");
        pnlAdmissionInfo1.setName("pnlAdmissionInfo1"); // NOI18N

        javax.swing.GroupLayout pnlAdmissionInfo1Layout = new javax.swing.GroupLayout(pnlAdmissionInfo1);
        pnlAdmissionInfo1.setLayout(pnlAdmissionInfo1Layout);
        pnlAdmissionInfo1Layout.setHorizontalGroup(
            pnlAdmissionInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );
        pnlAdmissionInfo1Layout.setVerticalGroup(
            pnlAdmissionInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(pnlAdmissionInfo1);

        jLabel4.setBackground(new java.awt.Color(44, 117, 44));
        jLabel4.setForeground(new java.awt.Color(44, 117, 44));
        jLabel4.setText("jLabel4");
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel2.add(jLabel4);

        jLabel5.setBackground(new java.awt.Color(44, 117, 44));
        jLabel5.setForeground(new java.awt.Color(44, 117, 44));
        jLabel5.setText("jLabel4");
        jLabel5.setName("jLabel5"); // NOI18N
        jPanel2.add(jLabel5);

        jLabel6.setBackground(new java.awt.Color(44, 117, 44));
        jLabel6.setForeground(new java.awt.Color(44, 117, 44));
        jLabel6.setText("jLabel4");
        jLabel6.setName("jLabel6"); // NOI18N
        jPanel2.add(jLabel6);

        pnlAdmissionInfo2.setBackground(new java.awt.Color(44, 117, 44));
        pnlAdmissionInfo2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "                   For Foreign Students", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlAdmissionInfo2.setBeanName("AdmissionRequirements2Ext");
        pnlAdmissionInfo2.setName("pnlAdmissionInfo2"); // NOI18N

        javax.swing.GroupLayout pnlAdmissionInfo2Layout = new javax.swing.GroupLayout(pnlAdmissionInfo2);
        pnlAdmissionInfo2.setLayout(pnlAdmissionInfo2Layout);
        pnlAdmissionInfo2Layout.setHorizontalGroup(
            pnlAdmissionInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );
        pnlAdmissionInfo2Layout.setVerticalGroup(
            pnlAdmissionInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(pnlAdmissionInfo2);

        jPanel3.setBackground(new java.awt.Color(44, 117, 44));
        jPanel3.setName("jPanel3"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("               Applicants for grade school and high school levels must have general");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("               average of 83% (English, Math, Science,  Filipino and Social Studies or");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("               and a satisfactory conduct grade.");
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);

        pnlAdmissionRequirement.add(jPanel2);

        jTabbedPane1.addTab("Admission Requirements", pnlAdmissionRequirement);

        pnlEnrollmentInfo.setBackground(new java.awt.Color(44, 117, 44));
        pnlEnrollmentInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enrollment Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlEnrollmentInfo.setName("pnlEnrollmentInfo"); // NOI18N
        pnlEnrollmentInfo.setLayout(new java.awt.GridBagLayout());

        pnlStudentStatus.setBeanName("EnrollmentInfoExt");
        pnlStudentStatus.setName("pnlStudentStatus"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        pnlEnrollmentInfo.add(pnlStudentStatus, gridBagConstraints);

        pnlStudentStatusSchoolDetail.setBorder(javax.swing.BorderFactory.createTitledBorder("School Details"));
        pnlStudentStatusSchoolDetail.setBeanName("EnrollmentInfoSchoolDetailExt");
        pnlStudentStatusSchoolDetail.setName("pnlStudentStatusSchoolDetail"); // NOI18N

        javax.swing.GroupLayout pnlStudentStatusSchoolDetailLayout = new javax.swing.GroupLayout(pnlStudentStatusSchoolDetail);
        pnlStudentStatusSchoolDetail.setLayout(pnlStudentStatusSchoolDetailLayout);
        pnlStudentStatusSchoolDetailLayout.setHorizontalGroup(
            pnlStudentStatusSchoolDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlStudentStatusSchoolDetailLayout.setVerticalGroup(
            pnlStudentStatusSchoolDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        pnlEnrollmentInfo.add(pnlStudentStatusSchoolDetail, gridBagConstraints);

        pnlStudentStatusTuitionDetail.setBorder(javax.swing.BorderFactory.createTitledBorder("Tuition Fee Details"));
        pnlStudentStatusTuitionDetail.setBeanName("EnrollmentInfoTuitionDetailExt");
        pnlStudentStatusTuitionDetail.setName("pnlStudentStatusTuitionDetail"); // NOI18N

        javax.swing.GroupLayout pnlStudentStatusTuitionDetailLayout = new javax.swing.GroupLayout(pnlStudentStatusTuitionDetail);
        pnlStudentStatusTuitionDetail.setLayout(pnlStudentStatusTuitionDetailLayout);
        pnlStudentStatusTuitionDetailLayout.setHorizontalGroup(
            pnlStudentStatusTuitionDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlStudentStatusTuitionDetailLayout.setVerticalGroup(
            pnlStudentStatusTuitionDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        pnlEnrollmentInfo.add(pnlStudentStatusTuitionDetail, gridBagConstraints);

        jTabbedPane1.addTab("Student Status", pnlEnrollmentInfo);

        pnlFinalGrade.setBackground(new java.awt.Color(44, 117, 44));
        pnlFinalGrade.setName("pnlFinalGrade"); // NOI18N

        jPanel6.setBackground(new java.awt.Color(44, 117, 44));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Grades", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel6.setName("jPanel6"); // NOI18N
        jPanel6.setLayout(new java.awt.GridLayout(2, 0));

        pnlFinalGradeInfo.setBackground(new java.awt.Color(44, 117, 44));
        pnlFinalGradeInfo.setBeanName("StudentGradingExt");
        pnlFinalGradeInfo.setName("pnlFinalGradeInfo"); // NOI18N
        pnlFinalGradeInfo.setShowSubRecords(true);

        javax.swing.GroupLayout pnlFinalGradeInfoLayout = new javax.swing.GroupLayout(pnlFinalGradeInfo);
        pnlFinalGradeInfo.setLayout(pnlFinalGradeInfoLayout);
        pnlFinalGradeInfoLayout.setHorizontalGroup(
            pnlFinalGradeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );
        pnlFinalGradeInfoLayout.setVerticalGroup(
            pnlFinalGradeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        jPanel6.add(pnlFinalGradeInfo);

        pnlFinalGradeAverage.setBackground(new java.awt.Color(44, 117, 44));
        pnlFinalGradeAverage.setBeanName("StudentGrading1Ext");
        pnlFinalGradeAverage.setName("pnlFinalGradeAverage"); // NOI18N

        javax.swing.GroupLayout pnlFinalGradeAverageLayout = new javax.swing.GroupLayout(pnlFinalGradeAverage);
        pnlFinalGradeAverage.setLayout(pnlFinalGradeAverageLayout);
        pnlFinalGradeAverageLayout.setHorizontalGroup(
            pnlFinalGradeAverageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );
        pnlFinalGradeAverageLayout.setVerticalGroup(
            pnlFinalGradeAverageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        jPanel6.add(pnlFinalGradeAverage);

        jPanel7.setBackground(new java.awt.Color(44, 117, 44));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Main Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.setName("jPanel7"); // NOI18N
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("School Year:");
        jLabel7.setName("jLabel7"); // NOI18N
        jPanel7.add(jLabel7, new java.awt.GridBagConstraints());

        txtSearchSchoolYear.setName("txtSearchSchoolYear"); // NOI18N
        txtSearchSchoolYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchSchoolYearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel7.add(txtSearchSchoolYear, gridBagConstraints);

        jButton1.setText("Search");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel7.add(jButton1, gridBagConstraints);

        javax.swing.GroupLayout pnlFinalGradeLayout = new javax.swing.GroupLayout(pnlFinalGrade);
        pnlFinalGrade.setLayout(pnlFinalGradeLayout);
        pnlFinalGradeLayout.setHorizontalGroup(
            pnlFinalGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFinalGradeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFinalGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlFinalGradeLayout.setVerticalGroup(
            pnlFinalGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFinalGradeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Final Grade", pnlFinalGrade);

        pnlSchoolAttended.setBackground(new java.awt.Color(44, 117, 44));
        pnlSchoolAttended.setName("pnlSchoolAttended"); // NOI18N

        jPanel9.setBackground(new java.awt.Color(44, 117, 44));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student School Attended", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel9.setName("jPanel9"); // NOI18N
        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        pnlStudentSchoolAttended.setBeanName("StudentSchoolAttended");
        pnlStudentSchoolAttended.setName("pnlStudentSchoolAttended"); // NOI18N
        pnlStudentSchoolAttended.setShowSubRecords(true);

        javax.swing.GroupLayout pnlStudentSchoolAttendedLayout = new javax.swing.GroupLayout(pnlStudentSchoolAttended);
        pnlStudentSchoolAttended.setLayout(pnlStudentSchoolAttendedLayout);
        pnlStudentSchoolAttendedLayout.setHorizontalGroup(
            pnlStudentSchoolAttendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );
        pnlStudentSchoolAttendedLayout.setVerticalGroup(
            pnlStudentSchoolAttendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );

        jPanel9.add(pnlStudentSchoolAttended);

        javax.swing.GroupLayout pnlSchoolAttendedLayout = new javax.swing.GroupLayout(pnlSchoolAttended);
        pnlSchoolAttended.setLayout(pnlSchoolAttendedLayout);
        pnlSchoolAttendedLayout.setHorizontalGroup(
            pnlSchoolAttendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSchoolAttendedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSchoolAttendedLayout.setVerticalGroup(
            pnlSchoolAttendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSchoolAttendedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("School Attended", pnlSchoolAttended);

        pnlStudentCurriculumSubject.setBackground(new java.awt.Color(44, 117, 44));
        pnlStudentCurriculumSubject.setName("pnlStudentCurriculumSubject"); // NOI18N

        jPanel8.setBackground(new java.awt.Color(44, 117, 44));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Curriculum", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.setName("jPanel8"); // NOI18N
        jPanel8.setLayout(new java.awt.GridLayout());

        pnlCurriculumSubject.setBeanName("StudentSubject1Ext");
        pnlCurriculumSubject.setName("pnlCurriculumSubject"); // NOI18N
        pnlCurriculumSubject.setShowSubRecords(true);

        javax.swing.GroupLayout pnlCurriculumSubjectLayout = new javax.swing.GroupLayout(pnlCurriculumSubject);
        pnlCurriculumSubject.setLayout(pnlCurriculumSubjectLayout);
        pnlCurriculumSubjectLayout.setHorizontalGroup(
            pnlCurriculumSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );
        pnlCurriculumSubjectLayout.setVerticalGroup(
            pnlCurriculumSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );

        jPanel8.add(pnlCurriculumSubject);

        javax.swing.GroupLayout pnlStudentCurriculumSubjectLayout = new javax.swing.GroupLayout(pnlStudentCurriculumSubject);
        pnlStudentCurriculumSubject.setLayout(pnlStudentCurriculumSubjectLayout);
        pnlStudentCurriculumSubjectLayout.setHorizontalGroup(
            pnlStudentCurriculumSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentCurriculumSubjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlStudentCurriculumSubjectLayout.setVerticalGroup(
            pnlStudentCurriculumSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentCurriculumSubjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Curriculum Subject", pnlStudentCurriculumSubject);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        add(jTabbedPane1, gridBagConstraints);
        jTabbedPane1.getAccessibleContext().setAccessibleName("Parents Info");

        jPanel5.setBackground(new java.awt.Color(44, 117, 44));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Student:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setLayout(new java.awt.GridBagLayout());

        txtSearchField.setName("txtSearchField"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel5.add(txtSearchField, gridBagConstraints);

        btnSearchNow.setText("Search Now");
        btnSearchNow.setName("btnSearchNow"); // NOI18N
        btnSearchNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchNowActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel5.add(btnSearchNow, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        add(jPanel5, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

private void btnSearchNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchNowActionPerformed
    String txt = txtSearchField.getText().toUpperCase();
    List lst = DBClient.getList("SELECT a FROM Student a WHERE a.lastName LIKE '",txt,"%' OR a.firstName LIKE '",txt,"%'");
    if (lst==null || lst.size()==0) {
        PanelUtil.showError(btnSearchNow, "No student found.");
    }
    else {
        setupData(lst);
    }    
}//GEN-LAST:event_btnSearchNowActionPerformed

private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    cancelUpdate();
}//GEN-LAST:event_btnCancelActionPerformed

private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    saveRecord();
}//GEN-LAST:event_btnSaveActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

private void txtSearchSchoolYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchSchoolYearActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtSearchSchoolYearActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearchNow;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    protected component.BeanPanelPallete pnlAdmissionInfo1;
    protected component.BeanPanelPallete pnlAdmissionInfo2;
    private javax.swing.JPanel pnlAdmissionRequirement;
    protected component.BeanPanelPallete pnlBusOperator;
    private component.BeanPanelPallete pnlCurriculumSubject;
    private javax.swing.JPanel pnlEnrollmentInfo;
    protected component.BeanPanelPallete pnlFather;
    private javax.swing.JPanel pnlFinalGrade;
    private component.BeanPanelPallete pnlFinalGradeAverage;
    private component.BeanPanelPallete pnlFinalGradeInfo;
    protected component.BeanPanelPallete pnlGuardian;
    protected component.BeanPanelPallete pnlHomeDetails;
    protected component.BeanPanelPallete pnlMother;
    private javax.swing.JPanel pnlParentInfo;
    private javax.swing.JPanel pnlPersonalInfo;
    private javax.swing.JPanel pnlSchoolAttended;
    private javax.swing.JPanel pnlStudent;
    private javax.swing.JPanel pnlStudentCurriculumSubject;
    protected component.BeanPanelPallete pnlStudentInfo;
    protected component.BeanPanelPallete pnlStudentInfoPanel;
    private component.BeanPanelPallete pnlStudentSchoolAttended;
    protected component.BeanPanelPallete pnlStudentStatus;
    private component.BeanPanelPallete pnlStudentStatusSchoolDetail;
    private component.BeanPanelPallete pnlStudentStatusTuitionDetail;
    protected javax.swing.JTextField txtSearchField;
    private javax.swing.JTextField txtSearchSchoolYear;
    // End of variables declaration//GEN-END:variables

}
