/*
 * GenericPrintDisplayer.java
 *
 * Created on December 22, 2007, 12:34 PM
 */

package component;

import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.jdic.browser.WebBrowser;
import org.jdesktop.jdic.browser.WebBrowserEvent;
import org.jdesktop.jdic.browser.WebBrowserListener;

import util.Log;

/**
 *
 * @author  Budoy Entokwa
 */
public class GenericPrintDisplayer extends javax.swing.JPanel implements WebBrowserListener {
    static boolean autoprint = false;
    static GenericPrintDisplayer gpd;
    PrintPane print;
    WebBrowser webBrowser;

    public static void printHTML(String html) {
        try {
            autoprint = false;
            new component.GenericPrintDisplayer();
//            Desktop.getDesktop().print(new File("sample.html"));
            gpd.webBrowser.setContent(html);
            gpd.dlgPanel.pack();
            gpd.dlgPanel.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger("global").log(Level.SEVERE, null, ex);
        }
    }

    public static void autoPrintHTML(String html) {
        autoprint = true;
        try {
            autoprint = false;
            new component.GenericPrintDisplayer();
            gpd.webBrowser.setContent(html);
            gpd.dlgPanel.pack();
            if (!autoprint) gpd.dlgPanel.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger("global").log(Level.SEVERE, null, ex);
        }
    }

    /** Creates new form GenericPrintDisplayer */
    public GenericPrintDisplayer() {
        if (gpd == null) {
            initComponents();
            gpd = this;
            webBrowser = new WebBrowser();
            webBrowser.addWebBrowserListener(this);
            pnlViewer.add(webBrowser);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgPanel = new javax.swing.JDialog();
        pnlViewer = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnPrint = new javax.swing.JButton();

        dlgPanel.setTitle("Print Viewer");
        dlgPanel.setAlwaysOnTop(true);

        pnlViewer.setLayout(new java.awt.GridLayout(1, 0));

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrint);

        javax.swing.GroupLayout dlgPanelLayout = new javax.swing.GroupLayout(dlgPanel.getContentPane());
        dlgPanel.getContentPane().setLayout(dlgPanelLayout);
        dlgPanelLayout.setHorizontalGroup(
            dlgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(dlgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlViewer, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
                .addContainerGap())
        );
        dlgPanelLayout.setVerticalGroup(
            dlgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlViewer, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
    webBrowser.executeScript("window.print();");
    dlgPanel.setVisible(false);
    autoprint = false;
}//GEN-LAST:event_btnPrintActionPerformed
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnPrint;
    public javax.swing.JDialog dlgPanel;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel pnlViewer;
    // End of variables declaration//GEN-END:variables
	
    public void downloadCompleted(WebBrowserEvent event) {
        Log.out("Download Completed");
    }

    public void downloadError(WebBrowserEvent event) {
        Log.out("Download Error");
    }

    public void downloadProgress(WebBrowserEvent event) {
        Log.out("Download in Progress");
    }

    public void downloadStarted(WebBrowserEvent event) {
        Log.out("Download Started");
    }

    public void initializationCompleted(WebBrowserEvent arg0) {
        return;
    }

    public void documentCompleted(WebBrowserEvent arg0) {
        Log.out("Document Completed");
        if (autoprint) {
            webBrowser.executeScript("window.print();");
            dlgPanel.setVisible(false);
            autoprint = false;
        }
        return;
    }

    public void titleChange(WebBrowserEvent arg0) {
        return;
    }

    public void statusTextChange(WebBrowserEvent arg0) {
        return;
    }
}
