/*
 * PopupPanel.java
 *
 * Created on February 14, 2009, 1:20 PM
 */
package component;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JPanel;
import template.TemplateReader;
import template.screen.AbstractTemplatePanel;
import util.PanelUtil;

/**
 *
 * @author  Charliemagne Mark
 */
public class PopupPanel extends javax.swing.JDialog {
    public AbstractTemplatePanel pnl;
    
    public static PopupPanel getPanel(String bean, String sql) {
        PopupPanel panel = new PopupPanel(common2.Common2View.mainView.getFrame(), true);
        showBeanPanel(panel, bean, sql);
//        panel.setVisible(true);
        return panel;
    }

    private static void showPanel(PopupPanel panel, String name, String clsStr) {
        JPanel pnl = PanelUtil.getPanel(name, clsStr);
        panel.pnlTemplate.removeAll();
        panel.pnlTemplate.add(pnl);
        panel.pnlTemplate.updateUI();
    }

    private static void showBeanPanel(PopupPanel panel, String bean, final String sql) {
        try {
            if (bean == null || bean.trim().isEmpty()) {
                return;
            }
            if (bean.endsWith("Form")) {
                showPanel(panel, bean, bean);
                return;
            }
            final AbstractTemplatePanel tmp = TemplateReader.getTemplate(PanelUtil.getBeanClass(bean));
            panel.pnl = tmp;
            panel.pnlTemplate.removeAll();
            panel.pnlTemplate.add((JComponent)tmp.getMainForm());
            panel.pnlTemplate.updateUI();
            panel.setTitle(tmp.getTitle());
//            Thread t = new Thread(new Runnable() {
//                public void run() {
//                    try {
//                        Thread.currentThread().sleep(500);
                        tmp.firstRecord();
                        tmp.ruleWrapper.onLoad();
                        tmp.loadSql(sql);
//                    } catch (Exception e) {
//                    }
//                }
//            });
//            t.start();
        } catch (Exception ex) {
            System.out.println("BEAN == " + bean);
            Logger.getLogger(PopupPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** Creates new form PopupPanel */
    public PopupPanel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTemplate = new javax.swing.JPanel();
        pnlButton = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(common2.Common2App.class).getContext().getResourceMap(PopupPanel.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setAlwaysOnTop(true);
        setModal(true);
        setName("Form"); // NOI18N

        pnlTemplate.setName("pnlTemplate"); // NOI18N
        pnlTemplate.setLayout(new java.awt.GridLayout());
        getContentPane().add(pnlTemplate, java.awt.BorderLayout.CENTER);

        pnlButton.setName("pnlButton"); // NOI18N

        btnSave.setText(resourceMap.getString("btnSave.text")); // NOI18N
        btnSave.setName("btnSave"); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnlButton.add(btnSave);

        getContentPane().add(pnlButton, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    pnl.saveRecord();
}//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                PopupPanel dialog = new PopupPanel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlTemplate;
    // End of variables declaration//GEN-END:variables
}
