
package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-04/12/2007 02:26 PM(vivekp)-RC1
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Server", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Server {


    /**
     * 
     * @param parameter
     * @return
     *     returns java.lang.Object
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "call", targetNamespace = "http://service/", className = "service.Call")
    @ResponseWrapper(localName = "callResponse", targetNamespace = "http://service/", className = "service.CallResponse")
    public Object call(
        @WebParam(name = "parameter", targetNamespace = "")
        Object parameter);

}
