/*
 * AcceptPaymentForm.java
 *
 * Created on March 26, 2009, 4:44 PM
 */

package ui.cashier;

import bean.Person;
import bean.sales.Payment;

import java.awt.*;
import javax.swing.JPanel;
import springbean.AAAConfig;
import util.BeanUtil;
import util.PanelUtil;
import rule.BusinessRuleWrapper;

/**
 *
 * @author  Maria Monica
 */
public class AcceptCheckForm extends JPanel {
	static Payment lastCheck;
    static Payment pay;
	
    public static Payment acceptCheck(Person stud, double amount, double discount) {
        AcceptCheckForm form = new AcceptCheckForm();
        pay = (Payment) form.pnlPayment.getBean();
        pay.amount = amount;
        pay.discount = discount;
        form.pnlPayment.setBean(pay);
        BusinessRuleWrapper rule = form.pnlPayment.view.ruleWrapper;
        rule.onChangeRecord();
        if (stud!=null) {
            form.datStud = stud;
            form.txtStudent.setText(stud.toString());
        }
//        BeanUtil.copyBean(stud, form.datStud);
        form.dlg.setLayout(new GridLayout());
        form.dlg.add(form);
        form.dlg.pack();
        Dimension dim = form.dlg.getPreferredSize();
        dim.width = 600;
        form.dlg.setPreferredSize(dim);
        form.dlg.setMinimumSize(dim);
        form.dlg.setSize(dim);
        form.dlg.setVisible(true);
        lastCheck = (Payment) form.pnlPayment.getBean();
        return lastCheck;
    }
    /** Creates new form AcceptPaymentForm */
   
    public AcceptCheckForm() {
        initComponents();
        PanelUtil.updateColor(pnlPayment);
        PanelUtil.updateColor(this);
        PanelUtil.updateColor(this.jPanel1);
        PanelUtil.updateColor(this.jPanel2);
        PanelUtil.updateColor(this.jPanel4);
        PanelUtil.updateColor(this.pnlStudent);
    }
    
    
    public static void main(String[] args) {
        java.awt.Color clr = new java.awt.Color(44, 117, 44);
        constants.Constants.panelBackground = clr;
        constants.Constants.labelColor = Color.WHITE;
        AAAConfig.getInstance();
        PanelUtil.displayToFrame(new AcceptCheckForm());
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        dlg = new javax.swing.JDialog();
        datStud = new bean.Person();
        jPanel1 = new javax.swing.JPanel();
        lblStudent = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        txtStudent = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        pnlStudent = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnPrintOr = new javax.swing.JButton();
        btnCopyLastCheck = new javax.swing.JButton();
        btnClearCheck = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pnlPayment = new component.BeanPanelPallete();

        dlg.setTitle("Accept Payment");
        dlg.setModal(true);
        dlg.setName("dlg"); // NOI18N

        javax.swing.GroupLayout dlgLayout = new javax.swing.GroupLayout(dlg.getContentPane());
        dlg.getContentPane().setLayout(dlgLayout);
        dlgLayout.setHorizontalGroup(
            dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dlgLayout.setVerticalGroup(
            dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(44, 117, 44));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblStudent.setForeground(new java.awt.Color(255, 255, 255));
        lblStudent.setText("Student:");
        lblStudent.setName("lblStudent"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(lblStudent, gridBagConstraints);

        lblAmount.setForeground(new java.awt.Color(255, 255, 255));
        lblAmount.setText("Amount:");
        lblAmount.setName("lblAmount"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(lblAmount, gridBagConstraints);

        txtStudent.setForeground(new java.awt.Color(255, 255, 255));
        txtStudent.setName("txtStudent"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, datStud, org.jdesktop.beansbinding.ELProperty.create("${lastName}, ${firstName} ${middleInitial}"), txtStudent, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 0);
        jPanel1.add(txtStudent, gridBagConstraints);

        txtAmount.setName("txtAmount"); // NOI18N
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 0);
        jPanel1.add(txtAmount, gridBagConstraints);

        setBackground(new java.awt.Color(44, 117, 44));

        pnlStudent.setBackground(new java.awt.Color(44, 117, 44));
        pnlStudent.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        pnlStudent.setName("pnlStudent"); // NOI18N

        jPanel4.setBackground(new java.awt.Color(44, 117, 44));
        jPanel4.setName("jPanel4"); // NOI18N

        btnPrintOr.setText("OK");
        btnPrintOr.setName("btnPrintOr"); // NOI18N
        btnPrintOr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintOrActionPerformed(evt);
            }
        });
        jPanel4.add(btnPrintOr);

        btnCopyLastCheck.setText("Copy Last Check");
        btnCopyLastCheck.setName("btnCopyLastCheck"); // NOI18N
        btnCopyLastCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyLastCheckActionPerformed(evt);
            }
        });
        jPanel4.add(btnCopyLastCheck);

        btnClearCheck.setText("Clear");
        btnClearCheck.setName("btnClearCheck"); // NOI18N
        btnClearCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearCheckActionPerformed(evt);
            }
        });
        jPanel4.add(btnClearCheck);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        pnlPayment.setBorder(javax.swing.BorderFactory.createTitledBorder("Payments"));
        pnlPayment.setBeanName("PaymentAcceptPaymentExt");
        pnlPayment.setMinimumSize(new java.awt.Dimension(150, 150));
        pnlPayment.setName("PaymentCashierExt"); // NOI18N
        pnlPayment.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout pnlPaymentLayout = new javax.swing.GroupLayout(pnlPayment);
        pnlPayment.setLayout(pnlPaymentLayout);
        pnlPaymentLayout.setHorizontalGroup(
            pnlPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );
        pnlPaymentLayout.setVerticalGroup(
            pnlPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );

        jPanel2.add(pnlPayment);

        javax.swing.GroupLayout pnlStudentLayout = new javax.swing.GroupLayout(pnlStudent);
        pnlStudent.setLayout(pnlStudentLayout);
        pnlStudentLayout.setHorizontalGroup(
            pnlStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlStudentLayout.setVerticalGroup(
            pnlStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtAmountActionPerformed

private void btnPrintOrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintOrActionPerformed
	double amountToPay = pay.amount - pay.discount;
	if (pay.extractCheckAmount()>amountToPay) {
		PanelUtil.showError(btnPrintOr, "Check amount [",pay.extractCheckAmount(),"] is more than the amount to pay [",amountToPay,"]");
		return;
	}
	dlg.setVisible(false);
}//GEN-LAST:event_btnPrintOrActionPerformed

private void btnCopyLastCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyLastCheckActionPerformed
	if (lastCheck!=null) {
		Payment p = (Payment) pnlPayment.getBean();
		p.accountNumber1 = lastCheck.accountNumber1;
		p.accountNumber2 = lastCheck.accountNumber2;
		p.accountNumber3 = lastCheck.accountNumber3;
		p.accountNumber4 = lastCheck.accountNumber4;
		p.accountNumber5 = lastCheck.accountNumber5;
		p.accountNumber6 = lastCheck.accountNumber6;
		p.accountNumber7 = lastCheck.accountNumber7;
		p.accountNumber8 = lastCheck.accountNumber8;
		p.accountNumber9 = lastCheck.accountNumber9;
		p.accountNumber10 = lastCheck.accountNumber10;
		p.changeValue("accountNumber1", lastCheck.accountNumber1);
		p.changeValue("accountNumber2", lastCheck.accountNumber2);
		p.changeValue("accountNumber3", lastCheck.accountNumber3);
		p.changeValue("accountNumber4", lastCheck.accountNumber4);
		p.changeValue("accountNumber5", lastCheck.accountNumber5);
		p.changeValue("accountNumber6", lastCheck.accountNumber6);
		p.changeValue("accountNumber7", lastCheck.accountNumber7);
		p.changeValue("accountNumber8", lastCheck.accountNumber8);
		p.changeValue("accountNumber9", lastCheck.accountNumber9);
		p.changeValue("accountNumber10", lastCheck.accountNumber10);

		p.changeValue("accountNumber1", lastCheck.accountNumber1);
		p.changeValue("accountNumber2", lastCheck.accountNumber2);
		p.changeValue("accountNumber3", lastCheck.accountNumber3);
		p.changeValue("accountNumber4", lastCheck.accountNumber4);
		p.changeValue("accountNumber5", lastCheck.accountNumber5);
		p.changeValue("accountNumber6", lastCheck.accountNumber6);
		p.changeValue("accountNumber7", lastCheck.accountNumber7);
		p.changeValue("accountNumber8", lastCheck.accountNumber8);
		p.changeValue("accountNumber9", lastCheck.accountNumber9);
		p.changeValue("accountNumber10", lastCheck.accountNumber10);
	}
}//GEN-LAST:event_btnCopyLastCheckActionPerformed

private void btnClearCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearCheckActionPerformed
	Payment p = (Payment) pnlPayment.getBean();
	Payment newp = new Payment();
	newp.amount = p.amount;
	newp.discount = p.discount;
	pnlPayment.setBean(newp);
}//GEN-LAST:event_btnClearCheckActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearCheck;
    private javax.swing.JButton btnCopyLastCheck;
    private javax.swing.JButton btnPrintOr;
    private bean.Person datStud;
    private javax.swing.JDialog dlg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblStudent;
    private component.BeanPanelPallete pnlPayment;
    private javax.swing.JPanel pnlStudent;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JLabel txtStudent;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
