/*
 * CodeGenerator.java
 *
 * Created on September 19, 2008, 7:40 AM
 */
package test;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import service.util.WSPersistenceEntityManager;
import util.PanelUtil;

/**
 *
 * @author  Entokwaa
 */
public class CodeGeneratorFrame extends javax.swing.JFrame {
    Map<Class, CodeGenerator> beanMap = new HashMap<Class, CodeGenerator>();
    /** Creates new form CodeGenerator */
    public CodeGeneratorFrame() {
        initComponents();
        setupBeans();
    }

    public void setupBeans() {
        List<String> names = XMLTester.getAllBeanNames();
        lstBeans.clear();
        lstBeans.addAll(names);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager1 = WSPersistenceEntityManager.getInstance();
        queryBeans = java.beans.Beans.isDesignTime() ? null : entityManager1.createQuery("SELECT a.head FROM Department a");
        lstBeans = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : queryBeans.getResultList();
        datDisplay = new test.DisplayImpl();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboBeans = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cboTemplate = new javax.swing.JComboBox();
        pnlMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Bean:");
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1, new java.awt.GridBagConstraints());

        cboBeans.setName("cboBeans"); // NOI18N

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lstBeans, cboBeans);
        bindingGroup.addBinding(jComboBoxBinding);

        cboBeans.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboBeansItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 200;
        jPanel1.add(cboBeans, gridBagConstraints);

        jLabel2.setText("Use Template:");
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 24, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        cboTemplate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Template1", "Template2", "Template3", "Template4", "Template5", "Template6" }));
        cboTemplate.setName("cboTemplate"); // NOI18N
        cboTemplate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTemplateItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 100;
        jPanel1.add(cboTemplate, gridBagConstraints);

        pnlMain.setName("pnlMain"); // NOI18N
        pnlMain.setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlMain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cboBeansItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboBeansItemStateChanged
    String beanName = cboBeans.getSelectedItem().toString();
    Class cls = PanelUtil.getBeanClass(beanName);
    if (!beanMap.containsKey(cls)) {
        beanMap.put(cls, new CodeGenerator(cls));
    }
    CodeGenerator generator = beanMap.get(cls);
    pnlMain.removeAll();
    pnlMain.add(generator.splitPane);
    pnlMain.updateUI();
}//GEN-LAST:event_cboBeansItemStateChanged

private void cboTemplateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTemplateItemStateChanged
// TODO add your handling code here:
}//GEN-LAST:event_cboTemplateItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CodeGeneratorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboBeans;
    private javax.swing.JComboBox cboTemplate;
    private test.DisplayImpl datDisplay;
    private javax.persistence.EntityManager entityManager1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private java.util.List lstBeans;
    private javax.swing.JPanel pnlMain;
    private javax.persistence.Query queryBeans;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
