/*
 * CashierTransactionForm.java
 *
 * Created on March 16, 2009, 4:20 PM
 */
package ui;

import bean.accounting.CashDrawer;
import bean.accounting.Invoice;
import bean.accounting.OtherPayment;
import bean.admin.AppConfig;
import bean.admin.UserStation;
import constants.UserInfo;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;
import javax.swing.JPanel;
import springbean.AAAConfig;
import template.report.AbstractReportTemplate;
import template.screen.TransactionPanel;
import ui.cashier.IAcceptPaymentWindow;
import util.DBClient;
import util.DateUtil;
import util.PanelUtil;

/**
 *
 * @author  Charliemagne Mark
 */
public class AbstractCashierForm extends TransactionPanel {
    List<IAcceptPaymentWindow> lst = new ArrayList();
    
    public void addWindow(String title, IAcceptPaymentWindow window) {
        tabMain.addTab(title, (JPanel) window);
        window.setDrawer(this);
//        window.run();
        try {
            window.setUseYear(cboSchoolYear.getSelectedItem().toString());
        }
        catch (Exception e) {
        }
        lst.add(window);
    }
    
    public static void main(String[] args) {
        java.awt.Color clr = new java.awt.Color(44, 117, 44);
        constants.Constants.panelBackground = clr;
        constants.Constants.labelColor = Color.WHITE;
        AAAConfig.getInstance();
        UserInfo.weblogin("WENG", "WENG");
        PanelUtil.displayToFrame(new AbstractCashierForm());
    }                                                                

    private void passKey(JComponent comp) {
        comp.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                super.keyPressed(e);
                JComponent c = (JComponent) e.getSource();
                if (e.getKeyCode() == KeyEvent.VK_DOWN) {
                    c.transferFocus();
                } else if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    ActionListener[] evt = c.getListeners(ActionListener.class);
                    for (ActionListener a : evt) {
                        a.actionPerformed(null);
                    }
                }
            }
        });
    }

    /** Creates new form CashierTransactionForm */
    public AbstractCashierForm() {
        try {
            if (!UserStation.isCashierAllowed()) {
                return;
            }
        } catch (Exception e) {
            PanelUtil.showError(null, e.getMessage());
            return;
        }
        initComponents();
        PanelUtil.updateColor(this);
        PanelUtil.updateColor(pnlBottomLeft);
        PanelUtil.updateColor(pnlCashDrawer);
        PanelUtil.updateColor(pnlHeader);
        PanelUtil.updateColor(pnlLeftCenter);
        PanelUtil.updateColor(pnlTransactionMenu);
        PanelUtil.updateColor(oRSeries1);

        PanelUtil.updateColor(lblBranchLabel);
        PanelUtil.updateColor(lblBusinessDay);
        PanelUtil.updateColor(lblStationLabel);
        PanelUtil.updateColor(lblTime);
        PanelUtil.updateColor(lblUserLabel);
//        PanelUtil.updateColor(lblStudentTitle);
        
        PanelUtil.updateColor(lblSchoolYear);
        PanelUtil.updateColor(jLabel2);
        PanelUtil.updateColor(jLabel3);
        PanelUtil.updateColor(jLabel4);
        PanelUtil.updateColor(jLabel5);
        PanelUtil.updateColor(jLabel6);
        PanelUtil.updateColor(jLabel7);

        passKey(btnMultiplePayment);
        passKey(btnNewStudent);
        passKey(btnORReprint);
        passKey(btnOldScreen);
        passKey(btnOldStudent);
        passKey(btnOtherPayment);
        cboSchoolYear.setSelectedItem(AppConfig.getSchoolYear());
        updateDrawer();
//        lblStationLabel.setText(UserStation.extractStationName());

        btnItemSalesReport.setVisible(false);
        btnCollectionReport.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dlgTransaction = new javax.swing.JDialog();
        btnOldStudent = new javax.swing.JButton();
        btnNewStudent = new javax.swing.JButton();
        btnMultiplePayment = new javax.swing.JButton();
        btnOtherPayment = new javax.swing.JButton();
        btnORReprint = new javax.swing.JButton();
        btnOldScreen = new javax.swing.JButton();
        pnlLeftCenter = new javax.swing.JPanel();
        pnlCashDrawer = new component.BeanPanelPallete();
        pnlHeader = new javax.swing.JPanel();
        lblUserLabel = new javax.swing.JLabel();
        lblBranchLabel = new javax.swing.JLabel();
        lblStationLabel = new javax.swing.JLabel();
        lblBusinessDay = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnlTransactionMenu = new javax.swing.JPanel();
        lblSchoolYear = new javax.swing.JLabel();
        txtViewOR = new javax.swing.JTextField();
        cboSchoolYear = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        pnlBottomLeft = new javax.swing.JPanel();
        btnCollectionReport = new javax.swing.JButton();
        btnItemSalesReport = new javax.swing.JButton();
        btnBookSold = new javax.swing.JButton();
        btnOtherPaymentReport = new javax.swing.JButton();
        tabMain = new javax.swing.JTabbedPane();
        oRSeries1 = new ui.cashier.ORSeries();

        dlgTransaction.setName("dlgTransaction"); // NOI18N
        dlgTransaction.getContentPane().setLayout(new java.awt.GridBagLayout());

        btnOldStudent.setText("OLD STUDENT");
        btnOldStudent.setName("btnOldStudent"); // NOI18N
        btnOldStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOldStudentActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 3, 2);
        dlgTransaction.getContentPane().add(btnOldStudent, gridBagConstraints);

        btnNewStudent.setText("NEW STUDENT");
        btnNewStudent.setName("btnNewStudent"); // NOI18N
        btnNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewStudentActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 3, 2);
        dlgTransaction.getContentPane().add(btnNewStudent, gridBagConstraints);

        btnMultiplePayment.setText("MULTIPLE PAYMENT");
        btnMultiplePayment.setName("btnMultiplePayment"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 3, 2);
        dlgTransaction.getContentPane().add(btnMultiplePayment, gridBagConstraints);

        btnOtherPayment.setText("OTHER PAYMENT");
        btnOtherPayment.setName("btnOtherPayment"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 3, 2);
        dlgTransaction.getContentPane().add(btnOtherPayment, gridBagConstraints);

        btnORReprint.setText("OR REPRINT");
        btnORReprint.setName("btnORReprint"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 3, 2);
        dlgTransaction.getContentPane().add(btnORReprint, gridBagConstraints);

        btnOldScreen.setText("OLD SCREEN");
        btnOldScreen.setName("btnOldScreen"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 3, 2);
        dlgTransaction.getContentPane().add(btnOldScreen, gridBagConstraints);

        setLayout(new java.awt.GridBagLayout());

        pnlLeftCenter.setName("pnlLeftCenter"); // NOI18N
        pnlLeftCenter.setLayout(new java.awt.GridLayout(1, 0));

        pnlCashDrawer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cash Drawer Total", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        pnlCashDrawer.setBeanName("CashDrawer");
        pnlCashDrawer.setMinimumSize(new java.awt.Dimension(150, 150));
        pnlCashDrawer.setName("pnlCashDrawer"); // NOI18N
        pnlCashDrawer.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout pnlCashDrawerLayout = new javax.swing.GroupLayout(pnlCashDrawer);
        pnlCashDrawer.setLayout(pnlCashDrawerLayout);
        pnlCashDrawerLayout.setHorizontalGroup(
            pnlCashDrawerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        pnlCashDrawerLayout.setVerticalGroup(
            pnlCashDrawerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        pnlLeftCenter.add(pnlCashDrawer);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        add(pnlLeftCenter, gridBagConstraints);

        pnlHeader.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlHeader.setName("pnlHeader"); // NOI18N
        pnlHeader.setLayout(new java.awt.GridBagLayout());

        lblUserLabel.setText("User:");
        lblUserLabel.setName("lblUserLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        pnlHeader.add(lblUserLabel, gridBagConstraints);

        lblBranchLabel.setText("Branch:");
        lblBranchLabel.setName("lblBranchLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        pnlHeader.add(lblBranchLabel, gridBagConstraints);

        lblStationLabel.setText("Station:");
        lblStationLabel.setName("lblStationLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        pnlHeader.add(lblStationLabel, gridBagConstraints);

        lblBusinessDay.setText("Business Day:");
        lblBusinessDay.setName("lblBusinessDay"); // NOI18N
        lblBusinessDay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBusinessDayMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        pnlHeader.add(lblBusinessDay, gridBagConstraints);

        lblTime.setText("Time:");
        lblTime.setName("lblTime"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        pnlHeader.add(lblTime, gridBagConstraints);

        jLabel3.setText("User:");
        jLabel3.setName("jLabel3"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        pnlHeader.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Branch:");
        jLabel4.setName("jLabel4"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 39, 0, 0);
        pnlHeader.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Station:");
        jLabel5.setName("jLabel5"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 39, 0, 0);
        pnlHeader.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Business Day:");
        jLabel6.setName("jLabel6"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 39, 0, 0);
        pnlHeader.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Time:");
        jLabel7.setName("jLabel7"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 39, 0, 0);
        pnlHeader.add(jLabel7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(pnlHeader, gridBagConstraints);

        pnlTransactionMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transaction Menu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        pnlTransactionMenu.setName("pnlTransactionMenu"); // NOI18N
        pnlTransactionMenu.setLayout(new java.awt.GridBagLayout());

        lblSchoolYear.setText("           Use this Year:        ");
        lblSchoolYear.setName("lblSchoolYear"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlTransactionMenu.add(lblSchoolYear, gridBagConstraints);

        txtViewOR.setName("txtViewOR"); // NOI18N
        txtViewOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewORActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlTransactionMenu.add(txtViewOR, gridBagConstraints);

        cboSchoolYear.setModel(getSchoolYearModel());
        cboSchoolYear.setName("cboSchoolYear"); // NOI18N
        cboSchoolYear.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboSchoolYearItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        pnlTransactionMenu.add(cboSchoolYear, gridBagConstraints);

        jLabel2.setText("View O R:");
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlTransactionMenu.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        add(pnlTransactionMenu, gridBagConstraints);

        pnlBottomLeft.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transaction Report", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        pnlBottomLeft.setName("pnlBottomLeft"); // NOI18N
        pnlBottomLeft.setLayout(new java.awt.GridBagLayout());

        btnCollectionReport.setText("Collection");
        btnCollectionReport.setName("btnCollectionReport"); // NOI18N
        btnCollectionReport.setPreferredSize(new java.awt.Dimension(150, 23));
        btnCollectionReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCollectionReportActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        pnlBottomLeft.add(btnCollectionReport, gridBagConstraints);

        btnItemSalesReport.setText("Items");
        btnItemSalesReport.setName("btnItemSalesReport"); // NOI18N
        btnItemSalesReport.setPreferredSize(new java.awt.Dimension(150, 23));
        btnItemSalesReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemSalesReportActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        pnlBottomLeft.add(btnItemSalesReport, gridBagConstraints);

        btnBookSold.setText("Books");
        btnBookSold.setName("btnBookSold"); // NOI18N
        btnBookSold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookSoldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlBottomLeft.add(btnBookSold, gridBagConstraints);

        btnOtherPaymentReport.setText("Others");
        btnOtherPaymentReport.setName("btnOtherPaymentReport"); // NOI18N
        btnOtherPaymentReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtherPaymentReportActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        pnlBottomLeft.add(btnOtherPaymentReport, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        add(pnlBottomLeft, gridBagConstraints);

        tabMain.setMinimumSize(new java.awt.Dimension(820, 600));
        tabMain.setName("tabMain"); // NOI18N
        tabMain.setPreferredSize(new java.awt.Dimension(820, 600));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(tabMain, gridBagConstraints);

        oRSeries1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OR Series", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        oRSeries1.setName("oRSeries1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 70;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 9);
        add(oRSeries1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

private void btnCollectionReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCollectionReportActionPerformed
    AbstractReportTemplate.getInstance().showReportFromFileTemplateDialog("DailyCollectionReport", "", "Collection Report", null);
}//GEN-LAST:event_btnCollectionReportActionPerformed

private void btnOldStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOldStudentActionPerformed
    dlgTransaction.setVisible(false);
}//GEN-LAST:event_btnOldStudentActionPerformed

private void btnNewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewStudentActionPerformed
    dlgTransaction.setVisible(false);
}//GEN-LAST:event_btnNewStudentActionPerformed

private void txtViewORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewORActionPerformed
    String or = txtViewOR.getText();
    for (IAcceptPaymentWindow win:lst) {
        win.searchOR(or);
    }
    if (or.contains("-")) {
    	String orType = or.substring(0, or.indexOf("-")).toUpperCase();
    	or = or.substring(or.indexOf("-")+1).trim();
        Invoice inv = (Invoice) DBClient.getFirstRecord("SELECT a FROM Invoice a WHERE a.orType='",orType,"' AND a.orNumber=",or);
        if (inv==null) {
            PanelUtil.showError(txtViewOR, "OR #",or," not found.");
            return;
        }
        AbstractReportTemplate.getInstance().showReportFromFileTemplateDialog("OfficialReceipt", inv.seq, "Print Invoice", null);
    }
    else {
        Invoice inv = (Invoice) DBClient.getFirstRecord("SELECT a FROM Invoice a WHERE a.orType='N' AND a.orNumber=",or);
        if (inv==null) {
            PanelUtil.showError(txtViewOR, "OR #",or," not found.");
            return;
        }
        AbstractReportTemplate.getInstance().showReportFromFileTemplateDialog("OfficialReceipt", inv.seq, "Print Invoice", null);
    }
//    otherPayment1.loadOR(or);
//    oldStudent1.loadOR(or);
}//GEN-LAST:event_txtViewORActionPerformed

private void cboSchoolYearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboSchoolYearItemStateChanged
    for (IAcceptPaymentWindow win:lst) {
        win.setUseYear(cboSchoolYear.getSelectedItem().toString());
    }
    Thread t = new Thread(new Runnable() {
        public void run() {
            for (IAcceptPaymentWindow win:lst) {
                win.reloadPayments();
            }
        }
    });
    t.start();
}//GEN-LAST:event_cboSchoolYearItemStateChanged

private void btnOtherPaymentReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtherPaymentReportActionPerformed
    AbstractReportTemplate.getInstance().showReportFromFileTemplateDialog("OtherPaymentLineItem", "", "Other Payments", null);
}//GEN-LAST:event_btnOtherPaymentReportActionPerformed

private void btnItemSalesReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemSalesReportActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btnItemSalesReportActionPerformed

private void btnBookSoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookSoldActionPerformed
    AbstractReportTemplate.getInstance().showReportFromFileTemplateDialog("BookSold", "", "Sold Books", null);
}//GEN-LAST:event_btnBookSoldActionPerformed

private void lblBusinessDayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBusinessDayMouseClicked
	if (PanelUtil.showPrompt(lblBusinessDay, "Would you like to make overnight transaction?")) {
		constants.Constants.useDate = DateUtil.addDay(new Date(), 1);
		updateDrawer();
	}
}//GEN-LAST:event_lblBusinessDayMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookSold;
    private javax.swing.JButton btnCollectionReport;
    private javax.swing.JButton btnItemSalesReport;
    private javax.swing.JButton btnMultiplePayment;
    private javax.swing.JButton btnNewStudent;
    private javax.swing.JButton btnORReprint;
    private javax.swing.JButton btnOldScreen;
    private javax.swing.JButton btnOldStudent;
    private javax.swing.JButton btnOtherPayment;
    private javax.swing.JButton btnOtherPaymentReport;
    private javax.swing.JComboBox cboSchoolYear;
    private javax.swing.JDialog dlgTransaction;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblBranchLabel;
    private javax.swing.JLabel lblBusinessDay;
    public javax.swing.JLabel lblSchoolYear;
    private javax.swing.JLabel lblStationLabel;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUserLabel;
    public ui.cashier.ORSeries oRSeries1;
    public javax.swing.JPanel pnlBottomLeft;
    public component.BeanPanelPallete pnlCashDrawer;
    public javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlLeftCenter;
    public javax.swing.JPanel pnlTransactionMenu;
    public javax.swing.JTabbedPane tabMain;
    private javax.swing.JTextField txtViewOR;
    // End of variables declaration//GEN-END:variables

    private DefaultComboBoxModel getSchoolYearModel() {
        return new DefaultComboBoxModel(AppConfig.getSchoolYears().toArray());
    }
    
    public void updateDrawer() {
        System.out.println("UPDATE CASH DRAWER SERVER CALL");
        CashDrawer d = CashDrawer.updateCashDrawer();
        pnlCashDrawer.setBean(d);
        lblBranchLabel.setText(d.branch);
        lblBusinessDay.setText(DateUtil.formatDate(constants.Constants.useDate,"MMM dd, yyyy"));
        lblStationLabel.setText(d.userStation);
        lblTime.setText(DateUtil.formatDate(new Date(), "HH:mm"));
        lblUserLabel.setText(d.cashier);
        
        oRSeries1.updateSeries();
    }
    
    
}
