/*
 * ChangeThemeForm.java
 *
 * Created on March 15, 2009, 6:01 PM
 */

package ui;

import bean.admin.AppConfig;
import common2.Common2View;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import springbean.AAAConfig;
import util.PanelUtil;

/**
 *
 * @author  Charliemagne Mark
 */
public class ChangeThemeForm extends javax.swing.JPanel {
    public static void main(String[] args) {
        PanelUtil.displayToFrame(new ChangeThemeForm());
    }
    
    /** Creates new form ChangeThemeForm */
    public ChangeThemeForm() {
        initComponents();
        AAAConfig.getInstance();
        String panelColor = AppConfig.extractPanelBackground();
        String labelColor = AppConfig.extractLabelColor();
        try {
            String[] arr1 = panelColor.split(" ");
            String[] arr2 = labelColor.split(" ");
            Color c1 = PanelUtil.getColor(arr1);
            Color c2 = PanelUtil.getColor(arr2);
            constants.Constants.panelBackground = c1;
            constants.Constants.labelColor = c2;
            
            chkShowHostLogin.setSelected(AppConfig.isShowHostLogin());
        }
        catch (Exception e) {
        }
        PanelUtil.updateColor(this);
        PanelUtil.updateColor(lbl);
        
        String image = AppConfig.extractLoadingImage();
        if (image==null || image.isEmpty()) return;
        image = image.toLowerCase();
        ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/icons/" + image));
        int height = icon.getIconHeight();
        int width = icon.getIconWidth();
        lblSplashIconView.setMaximumSize(new Dimension(width, height));
        lblSplashIconView.setMinimumSize(new Dimension(width, height));
        lblSplashIconView.setPreferredSize(new Dimension(width, height));
        lblSplashIconView.setIcon(icon);
        btnSplashIcon.setText("Change Splash Icon ["+image+"]");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dlgColorChooser = new javax.swing.JColorChooser();
        btnChangePanelColor = new javax.swing.JButton();
        btnChangeLabelColor = new javax.swing.JButton();
        lbl = new javax.swing.JLabel();
        btnSplashIcon = new javax.swing.JButton();
        btnSaveTheme = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblSplashIconView = new javax.swing.JLabel();
        btnReportFolder = new javax.swing.JButton();
        btnWelcomeLabel = new javax.swing.JButton();
        chkShowHostLogin = new javax.swing.JCheckBox();

        dlgColorChooser.setName("dlgColorChooser"); // NOI18N

        setName("Form"); // NOI18N
        setLayout(new java.awt.GridBagLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(common2.Common2App.class).getContext().getResourceMap(ChangeThemeForm.class);
        btnChangePanelColor.setText(resourceMap.getString("btnChangePanelColor.text")); // NOI18N
        btnChangePanelColor.setName("btnChangePanelColor"); // NOI18N
        btnChangePanelColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePanelColorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        add(btnChangePanelColor, gridBagConstraints);

        btnChangeLabelColor.setText(resourceMap.getString("btnChangeLabelColor.text")); // NOI18N
        btnChangeLabelColor.setName("btnChangeLabelColor"); // NOI18N
        btnChangeLabelColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeLabelColorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        add(btnChangeLabelColor, gridBagConstraints);

        lbl.setFont(new java.awt.Font("Tahoma", 0, 24));
        lbl.setText(resourceMap.getString("lbl.text")); // NOI18N
        lbl.setName("lbl"); // NOI18N
        add(lbl, new java.awt.GridBagConstraints());

        btnSplashIcon.setText(resourceMap.getString("btnSplashIcon.text")); // NOI18N
        btnSplashIcon.setName("btnSplashIcon"); // NOI18N
        btnSplashIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSplashIconActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 0);
        add(btnSplashIcon, gridBagConstraints);

        btnSaveTheme.setText(resourceMap.getString("btnSaveTheme.text")); // NOI18N
        btnSaveTheme.setName("btnSaveTheme"); // NOI18N
        btnSaveTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveThemeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(29, 0, 0, 0);
        add(btnSaveTheme, gridBagConstraints);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblSplashIconView.setName("lblSplashIconView"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(lblSplashIconView, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 0);
        add(jPanel1, gridBagConstraints);

        btnReportFolder.setText(resourceMap.getString("btnReportFolder.text")); // NOI18N
        btnReportFolder.setName("btnReportFolder"); // NOI18N
        btnReportFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportFolderActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 0);
        add(btnReportFolder, gridBagConstraints);

        btnWelcomeLabel.setText(resourceMap.getString("btnWelcomeLabel.text")); // NOI18N
        btnWelcomeLabel.setName("btnWelcomeLabel"); // NOI18N
        btnWelcomeLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWelcomeLabelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 0);
        add(btnWelcomeLabel, gridBagConstraints);

        chkShowHostLogin.setText(resourceMap.getString("chkShowHostLogin.text")); // NOI18N
        chkShowHostLogin.setName("chkShowHostLogin"); // NOI18N
        chkShowHostLogin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkShowHostLoginItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 0);
        add(chkShowHostLogin, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

private void btnChangePanelColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePanelColorActionPerformed
    Color c = JColorChooser.showDialog(btnChangePanelColor, "Choose Panel Color", constants.Constants.panelBackground);
    constants.Constants.panelBackground = c;
    PanelUtil.updateColor(this);
    Common2View.mainView.changeTheme();
}//GEN-LAST:event_btnChangePanelColorActionPerformed

private void btnChangeLabelColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeLabelColorActionPerformed
    Color c = JColorChooser.showDialog(btnChangePanelColor, "Choose Label Color", constants.Constants.labelColor);
    constants.Constants.labelColor = c;
    PanelUtil.updateColor(lbl);
    Common2View.mainView.changeTheme();
}//GEN-LAST:event_btnChangeLabelColorActionPerformed

private void btnSaveThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveThemeActionPerformed
    AppConfig.setAppValue("PANEL BACKGROUND", PanelUtil.getColorStr(constants.Constants.panelBackground));
    AppConfig.setAppValue("LABEL COLOR", PanelUtil.getColorStr(constants.Constants.labelColor));
    AppConfig.setAppValue("LOADING IMAGE", lblSplashIconView.getText());
    AppConfig.setAppValue("CLIENT_REPORT_FOLDER", btnReportFolder.getToolTipText());
    AppConfig.setAppValue("WELCOME LABEL", btnWelcomeLabel.getToolTipText());
    AppConfig.setAppValue("SHOW HOST LOGIN", chkShowHostLogin.isSelected()?"TRUE":"FALSE");
}//GEN-LAST:event_btnSaveThemeActionPerformed

private void btnSplashIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSplashIconActionPerformed
    String str = PanelUtil.showPromptMessage(btnSplashIcon, "Type the filename of icon to be used", "Choose Splash Icon");
    ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/icons/" + str));
    int height = icon.getIconHeight();
    int width = icon.getIconWidth();
    lblSplashIconView.setMaximumSize(new Dimension(width, height));
    lblSplashIconView.setMinimumSize(new Dimension(width, height));
    lblSplashIconView.setPreferredSize(new Dimension(width, height));
    lblSplashIconView.setIcon(icon);  
    lblSplashIconView.setText(str);
    btnSplashIcon.setText("Change Splash Icon ["+str+"]");    
}//GEN-LAST:event_btnSplashIconActionPerformed

private void btnReportFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportFolderActionPerformed
    String txt = PanelUtil.showPromptDefaultMessage(btnReportFolder, "Report Folder", AppConfig.getReportFolder());
    btnReportFolder.setToolTipText(txt);
}//GEN-LAST:event_btnReportFolderActionPerformed

private void btnWelcomeLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWelcomeLabelActionPerformed
    String txt = PanelUtil.showPromptDefaultMessage(btnWelcomeLabel, "WelcomeLabel", AppConfig.getWelcomeLabel());
    btnWelcomeLabel.setToolTipText(txt);
}//GEN-LAST:event_btnWelcomeLabelActionPerformed

private void chkShowHostLoginItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkShowHostLoginItemStateChanged

}//GEN-LAST:event_chkShowHostLoginItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeLabelColor;
    private javax.swing.JButton btnChangePanelColor;
    private javax.swing.JButton btnReportFolder;
    private javax.swing.JButton btnSaveTheme;
    private javax.swing.JButton btnSplashIcon;
    private javax.swing.JButton btnWelcomeLabel;
    private javax.swing.JCheckBox chkShowHostLogin;
    private javax.swing.JColorChooser dlgColorChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblSplashIconView;
    // End of variables declaration//GEN-END:variables

}
