/*
 * EmployeeAttendanceForm.java
 *
 * Created on August 26, 2009, 9:31 AM
 */

package ui;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import bean.Employee;
import bean.person.PersonAttendance;
import bean.reference.EventHoliday;
import service.util.WSPersistenceEntityManager;
import template.screen.TransactionPanel;
import util.BeanUtil;
import util.DBClient;
import util.DateUtil;
import util.Log;
import util.PanelUtil;

/**
 *
 * @author  alex
 */
public class EmployeeAttendanceForm extends TransactionPanel {
	static EmployeeAttendanceForm form;
	Employee emp;
	
	protected String getEmployeeBean() {
		return "Employee";
	}
	
    @Override
	public String getTitle() {
		return "Employee Attendance";
	}

	public static void display(Employee emp) {
    	if (form==null) {
    		form = new EmployeeAttendanceForm();
    	}
    	form.emp = emp;
    	form.setAttendance();
    	form.dlgAttendance.pack();
    	form.dlgAttendance.setVisible(true);
    }
	
    private void setAttendance() {
    	String yearmonth = BeanUtil.concat(cboYear.getSelectedItem().toString(),"-",cboMonth.getSelectedItem().toString()); 
    	String s = BeanUtil.concat(yearmonth,"-",1);
    	String e = BeanUtil.concat(yearmonth,"-",31);
    	
    	String start = DateUtil.formatDateToSql(DateUtil.readDate(s, "yyyy-MMMM-dd"));
    	String end = DateUtil.formatDateToSql(DateUtil.readDate(e, "yyyy-MMMM-dd"));
    	String sql = BeanUtil.concat("SELECT a FROM PersonAttendance a WHERE a.personId=",emp.personId," AND a.attendanceDate BETWEEN '",start,"' AND '",end,"' ORDER BY a.attendanceDate");
    	Log.out(sql);
    	List tmp = DBClient.getList(sql);
    	PanelUtil.setListData(personattendanceList, tmp);
    }
    
    private PersonAttendance getAttendance(Date d, List<PersonAttendance> lst) {
    	if (lst!=null && !lst.isEmpty()) {
        	for (PersonAttendance att:lst) {
        		if (att.attendanceDate.equals(d)) {
        			return att;
        		}
        	}
    	}
    	PersonAttendance att = new PersonAttendance();
    	att.personId = emp.personId;
    	att.attendanceDate = d;
    	EventHoliday hol = EventHoliday.extractHoliday(att.attendanceDate);
    	if (hol==null) {
    		att.attendanceType = "REGULAR";
    		if (DateUtil.Days.isSaturday(att.attendanceDate)) {
    			att.attendanceType = "SATURDAY";
    		}
    		else if (DateUtil.Days.isSunday(att.attendanceDate)) {
    			att.attendanceType = "SUNDAY";
    		}
    	}
    	else {
    		att.attendanceType = hol.eventHoliday;
    		att.holidayPercentPay = hol.percentage; 
    	}
    	return att;
    }
    
    /** Creates new form EmployeeAttendanceForm */
    public EmployeeAttendanceForm() {
        initComponents();
        pnlEmployee.view.tblResult.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    loadAttendance();
                }
            }
        });
    }
    
    protected void loadAttendance() {
		emp = (Employee) pnlEmployee.getBean();
		if (emp==null || emp.isEmptyKey()) {
			PanelUtil.showError(null, "Please select employee.");
			return;
		}
		setAttendance();
//		List lst = DBClient.getList("SELECT a FROM PersonAttendance a WHERE a.personId=",emp.personId);
//		PanelUtil.setListData(personattendanceList, lst);
	}

	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        dlgAttendance = new javax.swing.JDialog();
        schoolPUEntityManager = WSPersistenceEntityManager.getInstance();
        personattendanceQuery = schoolPUEntityManager.createQuery("SELECT a FROM PersonAttendance a WHERE a.seq=0");
        personattendanceList = org.jdesktop.observablecollections.ObservableCollections.observableList(personattendanceQuery.getResultList());
        if (personattendanceList==null || personattendanceList.isEmpty()) {
            personattendanceList.add(new PersonAttendance());
        }
        btnChangeCalendar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        pnlEmployee = new component.BeanPanelPallete();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtSearchEmployee = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnPresent = new javax.swing.JButton();
        btnSickLeave = new javax.swing.JButton();
        btnVacationLeave = new javax.swing.JButton();
        btnAbsent = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        btnHoliday = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnPopulateAttendance = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAttendance = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboYear = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cboMonth = new javax.swing.JComboBox();

        dlgAttendance.setAlwaysOnTop(true);
        dlgAttendance.setName("dlgAttendance"); // NOI18N
        dlgAttendance.getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        btnChangeCalendar.setText("Change Calendar"); // NOI18N
        btnChangeCalendar.setName("btnChangeCalendar"); // NOI18N
        btnChangeCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeCalendarActionPerformed(evt);
            }
        });

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(common2.Common2App.class).getContext().getResourceMap(EmployeeAttendanceForm.class);
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel5.border.title"))); // NOI18N
        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setLayout(new java.awt.BorderLayout());

        pnlEmployee.setBeanName(getEmployeeBean());
        pnlEmployee.setName("pnlEmployee"); // NOI18N
        pnlEmployee.setShowForm(false);
        pnlEmployee.setShowImage(false);
        pnlEmployee.setShowResult(true);
        jPanel5.add(pnlEmployee, java.awt.BorderLayout.CENTER);

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel1.add(jLabel3);

        txtSearchEmployee.setText(resourceMap.getString("txtSearchEmployee.text")); // NOI18N
        txtSearchEmployee.setName("txtSearchEmployee"); // NOI18N
        txtSearchEmployee.setPreferredSize(new java.awt.Dimension(150, 20));
        txtSearchEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchEmployeeActionPerformed(evt);
            }
        });
        jPanel1.add(txtSearchEmployee);

        jPanel5.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        add(jPanel5, java.awt.BorderLayout.WEST);

        jPanel3.setName("jPanel3"); // NOI18N

        btnPresent.setText("Present"); // NOI18N
        btnPresent.setName("btnPresent"); // NOI18N
        btnPresent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresentActionPerformed(evt);
            }
        });
        jPanel3.add(btnPresent);

        btnSickLeave.setText("Sick Leave"); // NOI18N
        btnSickLeave.setName("btnSickLeave"); // NOI18N
        btnSickLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSickLeaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSickLeave);

        btnVacationLeave.setText("Vacation Leave"); // NOI18N
        btnVacationLeave.setName("btnVacationLeave"); // NOI18N
        btnVacationLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVacationLeaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnVacationLeave);

        btnAbsent.setText("Absent"); // NOI18N
        btnAbsent.setName("btnAbsent"); // NOI18N
        btnAbsent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbsentActionPerformed(evt);
            }
        });
        jPanel3.add(btnAbsent);

        btnCalculate.setText("Calculate"); // NOI18N
        btnCalculate.setName("btnCalculate"); // NOI18N
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        jPanel3.add(btnCalculate);

        btnHoliday.setText("View Holiday");
        btnHoliday.setName("btnHoliday"); // NOI18N
        btnHoliday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHolidayActionPerformed(evt);
            }
        });
        jPanel3.add(btnHoliday);

        btnSave.setText("Save");
        btnSave.setName("btnSave"); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSave);

        btnPopulateAttendance.setText("Attendance Check"); // NOI18N
        btnPopulateAttendance.setName("btnPopulateAttendance"); // NOI18N
        btnPopulateAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopulateAttendanceActionPerformed(evt);
            }
        });
        jPanel3.add(btnPopulateAttendance);

        add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel6.border.title"))); // NOI18N
        jPanel6.setName("jPanel6"); // NOI18N
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblAttendance.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblAttendance.setName("tblAttendance"); // NOI18N

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, personattendanceList, tblAttendance);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${attendanceDate}"));
        columnBinding.setColumnName("Attendance Date");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${attendanceType}"));
        columnBinding.setColumnName("Attendance Type");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${login}"));
        columnBinding.setColumnName("Login");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${logout}"));
        columnBinding.setColumnName("Logout");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${late}"));
        columnBinding.setColumnName("Late");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${overtime}"));
        columnBinding.setColumnName("Overtime");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nightDiff}"));
        columnBinding.setColumnName("Night Diff");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${totalHours}"));
        columnBinding.setColumnName("Total Hours");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${approvedOvertime}"));
        columnBinding.setColumnName("Approved Overtime");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${approvedNightDiff}"));
        columnBinding.setColumnName("Approved Night Diff");
        columnBinding.setColumnClass(Double.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tblAttendance);

        jPanel6.add(jScrollPane1);

        add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel2.setName("jPanel2"); // NOI18N

        jLabel1.setText("Year:"); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel2.add(jLabel1);

        cboYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2009", "2010", "2011", "2012", "2013", "2014", "2015" }));
        cboYear.setName("cboYear"); // NOI18N
        cboYear.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboYearItemStateChanged(evt);
            }
        });
        jPanel2.add(cboYear);

        jLabel2.setText("Month:"); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel2.add(jLabel2);

        cboMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cboMonth.setName("cboMonth"); // NOI18N
        cboMonth.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMonthItemStateChanged(evt);
            }
        });
        jPanel2.add(cboMonth);

        add(jPanel2, java.awt.BorderLayout.NORTH);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    protected void btnAttendanceCheckActionPerformed(ActionEvent evt) {
    	boolean b = PanelUtil.showPrompt(null, "Attendance Check might take several minutes, would you like to continue?");
    	if (b) {
    		PanelUtil.showWaitFrame();
        	PersonAttendance.populateAttendance();
        	btnChangeCalendarActionPerformed(null);
    		PanelUtil.hideWaitFrame();
    	}
	}

	private void btnChangeCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeCalendarActionPerformed
        setAttendance();
    }//GEN-LAST:event_btnChangeCalendarActionPerformed

        private void btnPresentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresentActionPerformed
        int[] rows = tblAttendance.getSelectedRows();
        for (int i=0; rows!=null && i<rows.length; i++) {
        	PersonAttendance att = personattendanceList.get(rows[i]);
    		if (att.attendanceType==null || att.attendanceType.isEmpty() || 
    				"REGULAR".equals(att.attendanceType) || att.attendanceType.contains("LEAVE") || att.attendanceType.contains("ABSENT")) {
        		att.changeValue("attendanceType", "REGULAR");
        		att.changeValue("login", "700");
        		att.changeValue("logout", "1600");
        		att.changeValue("totalHours", 8);

        		att.changeValue("attendanceType", "REGULAR");
        		att.changeValue("login", "700");
        		att.changeValue("logout", "1600");
        		att.changeValue("totalHours", 8);
    		}
        }
}//GEN-LAST:event_btnPresentActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        if (personattendanceList!=null && !personattendanceList.isEmpty()) {
        	for (PersonAttendance att:personattendanceList) {
        		att.calculate();
        	}
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnHolidayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHolidayActionPerformed
        PanelUtil.popupBeanTemplate(EventHoliday.class, "Holidays", true);
    }//GEN-LAST:event_btnHolidayActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        DBClient.persistBean( (List) personattendanceList);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtSearchEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchEmployeeActionPerformed
    	String txt = txtSearchEmployee.getText();
    	String sql = BeanUtil.concat("SELECT a FROM Employee a WHERE a.lastName LIKE '",txt,"%' OR a.firstName LIKE '",txt,"%' OR a.department LIKE '",txt,"%' OR a.position LIKE '",txt,"%' ORDER BY a.lastName, a.firstName");
        List lst = DBClient.getList(sql);
        PanelUtil.setListData(pnlEmployee.view.list, lst);
    }//GEN-LAST:event_txtSearchEmployeeActionPerformed

    private void btnSickLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSickLeaveActionPerformed
        int[] rows = tblAttendance.getSelectedRows();
        for (int i=0; rows!=null && i<rows.length; i++) {
        	PersonAttendance att = personattendanceList.get(rows[i]);
        	att.changeValue("attendanceType", "SICK LEAVE");
    		att.changeValue("login", "0");
    		att.changeValue("logout", "0");
    		att.changeValue("totalHours", 0);

        	att.changeValue("attendanceType", "SICK LEAVE");
    		att.changeValue("login", "0");
    		att.changeValue("logout", "0");
    		att.changeValue("totalHours", 0);
        }
    }//GEN-LAST:event_btnSickLeaveActionPerformed

    private void btnVacationLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVacationLeaveActionPerformed
        int[] rows = tblAttendance.getSelectedRows();
        for (int i=0; rows!=null && i<rows.length; i++) {
        	PersonAttendance att = personattendanceList.get(rows[i]);
        	att.changeValue("attendanceType", "VACATION LEAVE");
    		att.changeValue("login", "0");
    		att.changeValue("logout", "0");
    		att.changeValue("totalHours", 0);

        	att.changeValue("attendanceType", "VACATION LEAVE");
    		att.changeValue("login", "0");
    		att.changeValue("logout", "0");
    		att.changeValue("totalHours", 0);
        }
    }//GEN-LAST:event_btnVacationLeaveActionPerformed

    private void btnAbsentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbsentActionPerformed
        int[] rows = tblAttendance.getSelectedRows();
        for (int i=0; rows!=null && i<rows.length; i++) {
        	PersonAttendance att = personattendanceList.get(rows[i]);
        	att.changeValue("attendanceType", "ABSENT");
    		att.changeValue("login", "0");
    		att.changeValue("logout", "0");
    		att.changeValue("totalHours", 0);

        	att.changeValue("attendanceType", "ABSENT");
    		att.changeValue("login", "0");
    		att.changeValue("logout", "0");
    		att.changeValue("totalHours", 0);
        }
    }//GEN-LAST:event_btnAbsentActionPerformed

    private void cboYearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboYearItemStateChanged
        setAttendance();
    }//GEN-LAST:event_cboYearItemStateChanged

    private void cboMonthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMonthItemStateChanged
        setAttendance();
    }//GEN-LAST:event_cboMonthItemStateChanged

    private void btnPopulateAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopulateAttendanceActionPerformed
        PersonAttendance.populateAttendance();
    }//GEN-LAST:event_btnPopulateAttendanceActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbsent;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnChangeCalendar;
    private javax.swing.JButton btnHoliday;
    private javax.swing.JButton btnPopulateAttendance;
    private javax.swing.JButton btnPresent;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSickLeave;
    private javax.swing.JButton btnVacationLeave;
    private javax.swing.JComboBox cboMonth;
    private javax.swing.JComboBox cboYear;
    private javax.swing.JDialog dlgAttendance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private java.util.List<bean.person.PersonAttendance> personattendanceList;
    private javax.persistence.Query personattendanceQuery;
    private component.BeanPanelPallete pnlEmployee;
    private javax.persistence.EntityManager schoolPUEntityManager;
    private javax.swing.JTable tblAttendance;
    private javax.swing.JTextField txtSearchEmployee;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    
}
