package ui;

import bean.admin.Report;
import component.AbstractReport;
import component.AbstractReportParameterViewer;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import service.util.WSPersistenceEntityManager;

public class ReportForm extends JPanel {

    public String getHelpName() {
        return "Module.Reports.Report Designer Form";
    }
	
	public ReportForm() {
		initComponents();
		displayReports();
	}
	
	protected void displayReports() {
		for (Report report : list) {
			boolean b = report.getActive();
			if (!b) {
				continue;
			}
			ReportButton btn = new ReportButton(report.getReportLabel());
			btn.withParam = report.getWithParam();
			btn.setName(report.getReportName());
			btn.setToolTipText(report.getDescription());
			//check allowed groups and users
			pnlReport.add(btn);
			btn.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    try {
                        ReportButton btn = (ReportButton) e.getSource();
                        java.lang.String reportName = btn.getName();
						AbstractReport repRenderer = (AbstractReport) Class.forName(reportName).newInstance();
						if (btn.withParam==null || !btn.withParam) {
							repRenderer.showReport();
						}
						else {
							AbstractReportParameterViewer reportPnl = repRenderer.getParamViewer();
							reportPnl.setParentDialog(dlgReport);
							dlgReport.setTitle(reportPnl.getTitle());
							dlgReport.removeAll();
							dlgReport.add(reportPnl);
							dlgReport.pack();
							dlgReport.setVisible(true);
						}
                    } catch (Exception ex) {
                        Logger.getLogger("global").log(Level.SEVERE, null, ex);
                    }
                }				
			});
		}
	} 
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = WSPersistenceEntityManager.getInstance();
        query = entityManager.createQuery("SELECT r FROM Report r");
        list = com.sun.java.util.BindingCollections.observableList(query.getResultList());
        dlgReport = new javax.swing.JDialog();
        pnlReport = new javax.swing.JPanel();

        dlgReport.setTitle("Report Display");
        dlgReport.setAlwaysOnTop(true);
        dlgReport.setModal(true);

        org.jdesktop.layout.GroupLayout dlgReportLayout = new org.jdesktop.layout.GroupLayout(dlgReport.getContentPane());
        dlgReport.getContentPane().setLayout(dlgReportLayout);
        dlgReportLayout.setHorizontalGroup(
            dlgReportLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 505, Short.MAX_VALUE)
        );
        dlgReportLayout.setVerticalGroup(
            dlgReportLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 391, Short.MAX_VALUE)
        );

        pnlReport.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reports", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14)));
        pnlReport.setLayout(new java.awt.GridLayout(0, 4, 8, 8));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(pnlReport, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(pnlReport, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
		
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dlgReport;
    private javax.persistence.EntityManager entityManager;
    private java.util.List<bean.admin.Report> list;
    private javax.swing.JPanel pnlReport;
    private javax.persistence.Query query;
    // End of variables declaration//GEN-END:variables
	
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				JFrame frame = new JFrame();
				frame.setContentPane(new ReportForm());
				frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame.pack();
				frame.setVisible(true);
			}
		});
	}

	private static class ReportButton extends JButton {
		public ReportButton(String text) {
			super(text);
		}
		
		Boolean withParam;
	}
}
