/*
 * SaveDynamicReportForm.java
 *
 * Created on March 8, 2008, 1:48 PM
 */

package ui;

import bean.admin.DynamicReport;
import component.AbstractPanel;
import component.AbstractReport;
import component.LineNumber;
import component.reportdesigner.ReportDesigner;
import java.awt.EventQueue;
import java.io.File;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import net.sf.jasperreports.engine.JRParameter;
import net.sf.jasperreports.engine.JasperReport;
import service.util.WSPersistenceEntityManager;
import util.DataUtil;
import util.HelpMovieViewer;
import util.PanelUtil;

/**
 *
 * @author  Entokwaa
 */
public class SaveDynamicReportForm extends AbstractPanel {

    @Override
    public String getHelpName() {
        return "Module.Reports.Dynamic Report Category";
    }

    @Override
    public boolean isSingleton() {
        return false;
    }
    
    /** Creates new form SaveDynamicReportForm */
    public SaveDynamicReportForm() {
        initComponents();
        LineNumber lineNumber = new LineNumber(txtReportXML);
        lineNumber.setPreferredSize(999);
        scrReportXML.setRowHeaderView(lineNumber);
        List<String> lstReports = DataUtil.getReportXML();
        for (String str:lstReports) {
            DataUtil.putResourceToFile(str, constants.Constants.ROOT_FOLDER+"tmp/designing"); 
        }
        reloadAllFiles();
    }
    
    private void reloadAllFiles() {
        PanelUtil.clearList(dynamicReportList);
        File[] files = component.reportdesigner.ReportDesigner.getDesignFiles();
        for (File f:files) {
            try {
                if (f.getName().endsWith("bak")) continue;
                bean.admin.DynamicReport e = new bean.admin.DynamicReport();
                e.setCode(f.getName());
                e.setReportName(f.getPath());
                e.setXmlContent(new String(util.DataUtil.getBytes(f)));
                e.setFile(f);
                dynamicReportList.add(e);
            } catch (Exception ex) {
                Logger.getLogger("global").log(Level.SEVERE, null, ex);
            }
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingContext = new javax.beans.binding.BindingContext();

        schoolPUEntityManager = WSPersistenceEntityManager.getInstance();
        reportParameterViewer1 = new component.ReportParameterViewer();
        dynamicReportQuery = schoolPUEntityManager.createQuery("SELECT d FROM DynamicReport d");
        dynamicReportList = com.sun.java.util.BindingCollections.observableList(dynamicReportQuery.getResultList());
        dlgSaveReport = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSaveReportNow = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstReport = new javax.swing.JList();
        jPanel5 = new javax.swing.JPanel();
        btnNewReport = new javax.swing.JButton();
        btnRefreshReports = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        scrReportXML = new javax.swing.JScrollPane();
        txtReportXML = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pnlReportViewer = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnSaveDesign = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();

        dlgSaveReport.getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Report Title:"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 0);
        dlgSaveReport.getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Sort:"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 0);
        dlgSaveReport.getContentPane().add(jLabel2, gridBagConstraints);

        btnSaveReportNow.setText("Save Report"); // NOI18N
        btnSaveReportNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveReportNowActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 0);
        dlgSaveReport.getContentPane().add(btnSaveReportNow, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Report Design", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.beans.binding.Binding binding = new javax.beans.binding.Binding(dynamicReportList, null, lstReport, "elements");
        binding.addChildBinding("${comboDisplay}", null);
        bindingContext.addBinding(binding);

        lstReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstReportMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstReport);

        btnNewReport.setText("New Report"); // NOI18N
        btnNewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewReportActionPerformed(evt);
            }
        });
        jPanel5.add(btnNewReport);

        btnRefreshReports.setText("Refresh Reports"); // NOI18N
        btnRefreshReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshReportsActionPerformed(evt);
            }
        });
        jPanel5.add(btnRefreshReports);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        scrReportXML.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtReportXML.setColumns(20);
        txtReportXML.setRows(5);

        bindingContext.addBinding(lstReport, "${selectedElement.XML}", txtReportXML, "text");

        scrReportXML.setViewportView(txtReportXML);

        jPanel2.add(scrReportXML);

        jTabbedPane1.addTab("XML", jPanel2);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        pnlReportViewer.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane3.setViewportView(pnlReportViewer);

        jPanel4.add(jScrollPane3);

        jTabbedPane1.addTab("Report View", jPanel4);

        btnSaveDesign.setText("Save Design"); // NOI18N
        btnSaveDesign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDesignActionPerformed(evt);
            }
        });
        jPanel6.add(btnSaveDesign);

        btnHelp.setText("Help"); // NOI18N
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        jPanel6.add(btnHelp);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bindingContext.bind();
    }// </editor-fold>//GEN-END:initComponents

private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
//    HelpMovieViewer.showPanelHelp(this, "ReportDesignerHelp");
}//GEN-LAST:event_btnHelpActionPerformed

private void btnSaveReportNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveReportNowActionPerformed
//    dlgSaveReport.setVisible(false);
}//GEN-LAST:event_btnSaveReportNowActionPerformed

private void btnSaveDesignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDesignActionPerformed
    int index = lstReport.getSelectedIndex();
    DynamicReport obj = dynamicReportList.get(index);
    if (obj==null || obj.getFile()==null) {
        PanelUtil.showError(jPanel1, "Please select a valid report file");
        return;
    }
    JasperReport report = AbstractReport.compileReport(obj.getFile());
    String name = report.getName();
    if (name==null || name.isEmpty() || name.equals("classic")) {
        PanelUtil.showError(jLabel1, "The report does not have a name.");
        return;
    }
    ReportDesigner.saveDesign(obj.getFile(), name, 1000);
}//GEN-LAST:event_btnSaveDesignActionPerformed

private void btnRefreshReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshReportsActionPerformed
        reloadAllFiles();
}//GEN-LAST:event_btnRefreshReportsActionPerformed

private void btnNewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewReportActionPerformed
    ReportDesigner.showMe();
}//GEN-LAST:event_btnNewReportActionPerformed

private void lstReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstReportMouseClicked
    if (SwingUtilities.isRightMouseButton(evt)) {
        return;
    }
    int index = lstReport.getSelectedIndex();
    DynamicReport obj = dynamicReportList.get(index);
    if (obj==null || obj.getFile()==null) {
        PanelUtil.showError(jPanel1, "Please select a valid report file");
        return;
    }
    if (evt.getClickCount()==2) {
        ReportDesigner.showMe(obj.getFile());
    }
    JasperReport report = AbstractReport.compileReport(obj.getFile());
    List<JRParameter> params = AbstractReport.getReportParameters(report);
    if (params!=null && params.size()>0) {
        reportParameterViewer1.showParameters(report, pnlReportViewer, obj.getFile());
    }
    else {  
        AbstractReport.displayReportToPanel(pnlReportViewer, report);
    }
}//GEN-LAST:event_lstReportMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnNewReport;
    private javax.swing.JButton btnRefreshReports;
    private javax.swing.JButton btnSaveDesign;
    private javax.swing.JButton btnSaveReportNow;
    private javax.swing.JDialog dlgSaveReport;
    private java.util.List<bean.admin.DynamicReport> dynamicReportList;
    private javax.persistence.Query dynamicReportQuery;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList lstReport;
    private javax.swing.JPanel pnlReportViewer;
    private component.ReportParameterViewer reportParameterViewer1;
    private javax.persistence.EntityManager schoolPUEntityManager;
    private javax.swing.JScrollPane scrReportXML;
    private javax.swing.JTextArea txtReportXML;
    private javax.beans.binding.BindingContext bindingContext;
    // End of variables declaration//GEN-END:variables
    
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				JFrame frame = new JFrame();
				frame.setContentPane(new SaveDynamicReportForm());
				frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame.pack();
				frame.setVisible(true);
			}
		});
	}

    public String getTitle() {
        return "Report Designer";
    }

    public JTable getMasterTable() {
        return null;
    }

    public List getMasterList() {
        return null;
    }

    public EntityManager getEntityManager() {
        return null;
    }

    public Query getMasterQuery() {
        return null;
    }

    public Class getBeanClass() {
        return bean.admin.DynamicReport.class;
    }
}
