/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package bean.extension;

import springbean.GradingProcess;
import template.ChildRecords;
import template.Display;
import template.DisplayGroup;
import template.DisplayGroups;
import template.Displays;
import template.ParentAddInfo;
import template.UITemplate;
import template.screen.TemplateLeftRight;
import util.PanelUtil;
import bean.EmployeeFaculty;
import bean.Student;
import bean.admin.AuditTrail;
import bean.person.StudentValuesGrading;
import bean.reference.GradeLevel;
import bean.reference.LockGrading;
import bean.reference.Section;

/**
 * 
 * @author Charliemagne Mark
 */
@UITemplate(template = TemplateLeftRight.class, showChart = false, showFiles = false, showImages = false, columnSearch = {
		"faculty", "gradeLevel", "section", "student", "studentNumber" }, criteriaSearch = {
		"facultyId", "gradeLevel", "section", "studentId" }, gridCount = 2, title = "Student Values Grading")
@ChildRecords(value = { // @ChildRecord(template=ChildTemplateListPopup.class,
						// fieldMapping={"seq","admissionId"},
						// entity=AdmissionExamReference.class,
						// sql="SELECT a FROM AdmissionExam a WHERE a.admissionId=${seq} ORDER BY a.examType",
						// title="Exams")
}, info = {
		@ParentAddInfo(title = "Affective Development  (Preschool)", gridCount = 2, displayFields = { "" }, hideGroup = "3,4,5,6"),
		@ParentAddInfo(title = "Psychomotor Development  (Preschool)", gridCount = 2, displayFields = { "" }, hideGroup = "2,4,5,6"),
		@ParentAddInfo(title = "Mega Skills  (Grade 1-4)", gridCount = 2, displayFields = { "" }, hideGroup = "2,3,5,6"),
		@ParentAddInfo(title = "Values Promoted  (Grade 5-6/High School)", gridCount = 2, displayFields = { "" }, hideGroup = "2,3,4,6"),
		@ParentAddInfo(title = "ZL2 Components  (Grade 5-6/High School)", gridCount = 2, displayFields = { "" }, hideGroup = "2,3,4,5")
// @ParentAddInfo(title = "Affective Development", gridCount = 2,
// displayFields =
// {"kp","fh","fr","aw","ft","ic","ih","wi","id","in","de","wp","hs","ir","ls"}),
// @ParentAddInfo(title = "Psychomotor Development", gridCount = 2,
// displayFields =
// {"ap","ce","tc","cfp","df","wlr","cst","ocs","cwp","cp","pa"})
//    
})
@DisplayGroups( {

		@DisplayGroup(title = "Teacher's Comment", gridCount = 2, fields = {
				"comment1", "comment2", "comment3", "comment4" }),
		@DisplayGroup(title = "Misc Grades", gridCount = 6, fields = {
				"totalDays", "present", "absent",
				"totalDays2", "present2", "absent2",
				"totalDays3", "present3", "absent3",
				"totalDays4", "present4", "absent4"}),
		// Affective Development count = 15
		@DisplayGroup(title = "Affective Development", gridCount = 10, fields = {
				"kp", "kp2", "kp3", "kp4", "kpFinal", "fh", "fh2", "fh3",
				"fh4", "fhFinal", "fr", "fr2", "fr3", "fr4", "frFinal", "aw",
				"aw2", "aw3", "aw4", "awFinal", "ft", "ft2", "ft3", "ft4",
				"ftFinal", "ic", "ic2", "ic3", "ic4", "icFinal", "ih", "ih2",
				"ih3", "ih4", "ihFinal", "wi", "wi2", "wi3", "wi4", "wiFinal",
				"id", "id2", "id3", "id4", "idFinal", "neatAndOrganize",
				"neatAndOrganize2", "neatAndOrganize3", "neatAndOrganize4",
				"neatAndOrganizeFinal", "de", "de2", "de3", "de4", "deFinal",
				"wp", "wp2", "wp3", "wp4", "wpFinal", "hs", "hs2", "hs3",
				"hs4", "hsFinal", "ir", "ir2", "ir3", "ir4", "irFinal", "ls",
				"ls2", "ls3", "ls4", "lsFinal" }, addInfoOnly = true),
		// Psychomotor Development count = 11
		@DisplayGroup(title = "Psychomotor Development", gridCount = 10, fields = {
				"ap", "ap2", "ap3", "ap4", "apFinal", "ce", "ce2", "ce3",
				"ce4", "ceFinal", "tc", "tc2", "tc3", "tc4", "tcFinal", "cfp",
				"cfp2", "cfp3", "cfp4", "cfpFinal", "df", "df2", "df3", "df4",
				"dfFinal", "wlr", "wlr2", "wlr3", "wlr4", "wlrFinal", "cst",
				"cst2", "cst3", "cst4", "cstFinal", "ocs", "ocs2", "ocs3",
				"ocs4", "ocsFinal", "cwp", "cwp2", "cwp3", "cwp4", "cwpFinal",
				"cp", "cp2", "cp3", "cp4", "cpFinal", "pa", "pa2", "pa3",
				"pa4", "paFinal" }, addInfoOnly = true),
		// Megaskills count = 12
		@DisplayGroup(title = "Mega Skills", gridCount = 10, fields = { "con",
				"con2", "con3", "con4", "conFinal", "mot", "mot2", "mot3",
				"mot4", "motFinal", "eff", "eff2", "eff3", "eff4", "effFinal",
				"res", "res2", "res3", "res4", "resFinal", "ini", "ini2",
				"ini3", "ini4", "iniFinal", "per", "per2", "per3", "per4",
				"perFinal", "car", "car2", "car3", "car4", "carFinal", "tea",
				"tea2", "tea3", "tea4", "teaFinal", "com", "com2", "com3",
				"com4", "comFinal", "pro", "pro2", "pro3", "pro4", "proFinal",
				"focus", "focus2", "focus3", "focus4", "focusFinal", "respect",
				"respect2", "respect3", "respect4", "respectFinal",
				"clubsAndParticipation", "clubsAndParticipation2",
				"clubsAndParticipation3", "clubsAndParticipation4",
				"clubsAndParticipationFinal",
				"scouting", "scouting2",
				"scouting3", "scouting4",
				"scoutingFinal"}, addInfoOnly = true),
		// Values Promoted count = 14
		@DisplayGroup(title = "Values Promoted", gridCount = 10, fields = {
				"els", "els2", "els3", "els4", "elsFinal", "wfr", "wfr2",
				"wfr3", "wfr4", "wfrFinal", "apgw", "apgw2", "apgw3", "apgw4",
				"apgwFinal", "spaa", "spaa2", "spaa3", "spaa4", "spaaFinal",
				"iva", "iva2", "iva3", "iva4", "ivaFinal", "isl", "isl2",
				"isl3", "isl4", "islFinal", "aspvi", "aspvi2", "aspvi3",
				"aspvi4", "aspviFinal", "hspd", "hspd2", "hspd3", "hspd4",
				"hspdFinal", "sd", "sd2", "sd3", "sd4", "sdFinal", "put",
				"put2", "put3", "put4", "putFinal", "hlew", "hlew2", "hlew3",
				"hlew4", "hlewFinal", "prs", "prs2", "prs3", "prs4",
				"prsFinal", "cr", "cr2", "cr3", "cr4", "crFinal", "cws",
				"cws2", "cws3", "cws4", "cwsFinal" }, addInfoOnly = true),
		// ZL2 Components count = 6
		@DisplayGroup(title = "ZL2 Components", gridCount = 10, fields = {
				"pfe", "pfe2", "pfe3", "pfe4", "pfeFinal", "cra", "cra2",
				"cra3", "cra4", "craFinal", "ca", "ca2", "ca3", "ca4",
				"caFinal", "kin", "kin2", "kin3", "kin4", "kinFinal", "ec1",
				"ec12", "ec13", "ec14", "ec1Final", "ec2", "ec22", "ec23",
				"ec24", "ec2Final" }, addInfoOnly = true),
        @DisplayGroup(title = "Monthly Attendance", gridCount = 12, fields = {
        		"jan", "feb","mar","apr","may","jun","jul","aug","sep","oct","nov","dece" }, addInfoOnly = true)

})
@Displays( {
		@Display(name = "studentNumber", width = 150, type = "Label"),
		@Display(name = "facultyId", type = "PopSearch", linktoBean = EmployeeFaculty.class, label = "Faculty", width = 300, enabled = false),
		@Display(name = "studentId", type = "PopSearch", linktoBean = Student.class, label = "Student", width = 300, enabled = false),
		@Display(name = "gradeLevel", type = "PopSearch", linktoBean = GradeLevel.class, label = "Grade Level", width = 300, enabled = false),
		@Display(name = "section", type = "PopSearch", linktoBean = Section.class, width = 300, enabled = false),
	    @Display(name = "status",type="Combo",width=300,modelCombo={"Regular","Probationary Academic","Probationary Behavior","Probationary Academic and Behavior"}),
		// @Display(name = "quarter", type="Combo",
		// modelCombo={"1","2","3","4"},width=300),
		@Display(name = "comment1", width = 400, label = "1st Quarter Comment", type = "TextArea", height=60),
		@Display(name = "comment2", width = 400, label = "2nd Quarter Comment", type = "TextArea", height=60),
		@Display(name = "comment3", width = 400, label = "3rd Quarter Comment", type = "TextArea", height=60),
		@Display(name = "comment4", width = 400, label = "4th Quarter Comment", type = "TextArea", height=60),
		@Display(name = "totalDays", width = 30),
		@Display(name = "present", width = 30),
		@Display(name = "absent", width = 30),
		@Display(name = "totalDays2", width = 30),
		@Display(name = "present2", width = 30),
		@Display(name = "absent2", width = 30),
		@Display(name = "totalDays3", width = 30),
		@Display(name = "present3", width = 30),
		@Display(name = "absent3", width = 30),
		@Display(name = "totalDays4", width = 30),
		@Display(name = "present4", width = 30),
		@Display(name = "absent4", width = 30),

		// Affective Development
		@Display(name = "kp", addInfoOnly = true, leftLabel = "Knows and recites Simple Prayers", labelTop = true, label = "1st", width = 30),
		@Display(name = "kp2", addInfoOnly = true, width = 30, labelTop = true, label = "2nd"),
		@Display(name = "kp3", addInfoOnly = true, width = 30, labelTop = true, label = "3rd"),
		@Display(name = "kp4", addInfoOnly = true, width = 30, labelTop = true, label = "4th"),
		@Display(name = "kpFinal", enabled = false, addInfoOnly = true, width = 30, labelTop = true, label = "Final"),
		@Display(name = "fh", addInfoOnly = true, label = "Is Aware of Filipino Culture and Heritage", width = 30),
		@Display(name = "fh2", addInfoOnly = true, width = 30, hideLabel = true),
		@Display(name = "fh3", addInfoOnly = true, width = 30, hideLabel = true),
		@Display(name = "fh4", addInfoOnly = true, width = 30, hideLabel = true),
		@Display(name = "fhFinal", enabled = false, addInfoOnly = true, width = 30, hideLabel = true),
		@Display(name = "fr", addInfoOnly = true, label = "Follows Classroom Routine", width = 30),
		@Display(name = "fr2", addInfoOnly = true, width = 30, hideLabel = true),
		@Display(name = "fr3", addInfoOnly = true, width = 30, hideLabel = true),
		@Display(name = "fr4", addInfoOnly = true, width = 30, hideLabel = true),
		@Display(name = "frFinal", enabled = false, addInfoOnly = true, width = 30, hideLabel = true),
		@Display(name = "aw", addInfoOnly = true, label = "Accepts Suggestions Willingly", width = 30),
		@Display(name = "aw2", addInfoOnly = true, width = 30, hideLabel = true),
		@Display(name = "aw3", addInfoOnly = true, width = 30, hideLabel = true),
		@Display(name = "aw4", addInfoOnly = true, width = 30, hideLabel = true),
		@Display(name = "awFinal", enabled = false, addInfoOnly = true, width = 30, hideLabel = true),
		@Display(name = "ft", addInfoOnly = true, label = "Finishes Assigned Task on Time", width = 30),
		@Display(name = "ft2", addInfoOnly = true, width = 30, hideLabel = true),
		@Display(name = "ft3", addInfoOnly = true, width = 30, hideLabel = true),
		@Display(name = "ft4", addInfoOnly = true, width = 30, hideLabel = true),
		@Display(name = "ftFinal", enabled = false, addInfoOnly = true, width = 30, hideLabel = true),
		@Display(name = "ic", addInfoOnly = true, label = "Is Confident", width = 30),
		@Display(name = "ic2", addInfoOnly = true, label = "Is Confident", width = 30, hideLabel = true),
		@Display(name = "ic3", addInfoOnly = true, label = "Is Confident", width = 30, hideLabel = true),
		@Display(name = "ic4", addInfoOnly = true, label = "Is Confident", width = 30, hideLabel = true),
		@Display(name = "icFinal", enabled = false, addInfoOnly = true, label = "Is Confident", width = 30, hideLabel = true),
		@Display(name = "ih", addInfoOnly = true, label = "Is Consistently Honest", width = 30),
		@Display(name = "ih2", addInfoOnly = true, label = "Is Consistently Honest", width = 30, hideLabel = true),
		@Display(name = "ih3", addInfoOnly = true, label = "Is Consistently Honest", width = 30, hideLabel = true),
		@Display(name = "ih4", addInfoOnly = true, label = "Is Consistently Honest", width = 30, hideLabel = true),
		@Display(name = "ihFinal", enabled = false, addInfoOnly = true, label = "Is Consistently Honest", width = 30, hideLabel = true),
		@Display(name = "wi", addInfoOnly = true, label = "Works Independently", width = 30),
		@Display(name = "wi2", addInfoOnly = true, label = "Works Independently", width = 30, hideLabel = true),
		@Display(name = "wi3", addInfoOnly = true, label = "Works Independently", width = 30, hideLabel = true),
		@Display(name = "wi4", addInfoOnly = true, label = "Works Independently", width = 30, hideLabel = true),
		@Display(name = "wiFinal", enabled = false, addInfoOnly = true, label = "Works Independently", width = 30, hideLabel = true),
		@Display(name = "id", addInfoOnly = true, label = "Is Dependable", width = 30),
		@Display(name = "id2", addInfoOnly = true, label = "Is Dependable", width = 30, hideLabel = true),
		@Display(name = "id3", addInfoOnly = true, label = "Is Dependable", width = 30, hideLabel = true),
		@Display(name = "id4", addInfoOnly = true, label = "Is Dependable", width = 30, hideLabel = true),
		@Display(name = "idFinal", enabled = false, addInfoOnly = true, label = "Is Dependable", width = 30, hideLabel = true),
		@Display(name = "neatAndOrganize", addInfoOnly = true, label = "Is Neat and Organized", width = 30),
		@Display(name = "neatAndOrganize2", addInfoOnly = true, label = "Is Neat and Organized", width = 30, hideLabel = true),
		@Display(name = "neatAndOrganize3", addInfoOnly = true, label = "Is Neat and Organized", width = 30, hideLabel = true),
		@Display(name = "neatAndOrganize4", addInfoOnly = true, label = "Is Neat and Organized", width = 30, hideLabel = true),
		@Display(name = "neatAndOrganizeFinal", enabled = false, addInfoOnly = true, label = "Is Neat and Organized", width = 30, hideLabel = true),
		@Display(name = "de", addInfoOnly = true, label = "Demonstrates Concern for Environment", width = 30),
		@Display(name = "de2", addInfoOnly = true, label = "Demonstrates Concern for Environment", width = 30, hideLabel = true),
		@Display(name = "de3", addInfoOnly = true, label = "Demonstrates Concern for Environment", width = 30, hideLabel = true),
		@Display(name = "de4", addInfoOnly = true, label = "Demonstrates Concern for Environment", width = 30, hideLabel = true),
		@Display(name = "deFinal", enabled = false, addInfoOnly = true, label = "Demonstrates Concern for Environment", width = 30, hideLabel = true),
		@Display(name = "wp", addInfoOnly = true, label = "Works and Plays Well with Others", width = 30),
		@Display(name = "wp2", addInfoOnly = true, label = "Works and Plays Well with Others", width = 30, hideLabel = true),
		@Display(name = "wp3", addInfoOnly = true, label = "Works and Plays Well with Others", width = 30, hideLabel = true),
		@Display(name = "wp4", addInfoOnly = true, label = "Works and Plays Well with Others", width = 30, hideLabel = true),
		@Display(name = "wpFinal", enabled = false, addInfoOnly = true, label = "Works and Plays Well with Others", width = 30, hideLabel = true),
		@Display(name = "hs", addInfoOnly = true, label = "Handles Varied Situations", width = 30),
		@Display(name = "hs2", addInfoOnly = true, label = "Handles Varied Situations", width = 30, hideLabel = true),
		@Display(name = "hs3", addInfoOnly = true, label = "Handles Varied Situations", width = 30, hideLabel = true),
		@Display(name = "hs4", addInfoOnly = true, label = "Handles Varied Situations", width = 30, hideLabel = true),
		@Display(name = "hsFinal", enabled = false, addInfoOnly = true, label = "Handles Varied Situations", width = 30, hideLabel = true),
		@Display(name = "ir", addInfoOnly = true, label = "Is Respectful to Others", width = 30),
		@Display(name = "ir2", addInfoOnly = true, label = "Is Respectful to Others", width = 30, hideLabel = true),
		@Display(name = "ir3", addInfoOnly = true, label = "Is Respectful to Others", width = 30, hideLabel = true),
		@Display(name = "ir4", addInfoOnly = true, label = "Is Respectful to Others", width = 30, hideLabel = true),
		@Display(name = "irFinal", enabled = false, addInfoOnly = true, label = "Is Respectful to Others", width = 30, hideLabel = true),
		@Display(name = "ls", addInfoOnly = true, label = "Listens While others Speak", width = 30),
		@Display(name = "ls2", addInfoOnly = true, label = "Listens While others Speak", width = 30, hideLabel = true),
		@Display(name = "ls3", addInfoOnly = true, label = "Listens While others Speak", width = 30, hideLabel = true),
		@Display(name = "ls4", addInfoOnly = true, label = "Listens While others Speak", width = 30, hideLabel = true),
		@Display(name = "lsFinal", enabled = false, addInfoOnly = true, label = "Listens While others Speak", width = 30, hideLabel = true),

		// Psychomotor Development
		@Display(name = "ap", addInfoOnly = true, label = "Actively Participates at Play", width = 30),
		@Display(name = "ap2", addInfoOnly = true, label = "Actively Participates at Play", width = 30, hideLabel = true),
		@Display(name = "ap3", addInfoOnly = true, label = "Actively Participates at Play", width = 30, hideLabel = true),
		@Display(name = "ap4", addInfoOnly = true, label = "Actively Participates at Play", width = 30, hideLabel = true),
		@Display(name = "apFinal", enabled = false, addInfoOnly = true, label = "Actively Participates at Play", width = 30, hideLabel = true),
		@Display(name = "ce", addInfoOnly = true, label = "Colors Evenly", width = 30),
		@Display(name = "ce2", addInfoOnly = true, label = "Colors Evenly", width = 30, hideLabel = true),
		@Display(name = "ce3", addInfoOnly = true, label = "Colors Evenly", width = 30, hideLabel = true),
		@Display(name = "ce4", addInfoOnly = true, label = "Colors Evenly", width = 30, hideLabel = true),
		@Display(name = "ceFinal", enabled = false, addInfoOnly = true, label = "Colors Evenly", width = 30, hideLabel = true),
		@Display(name = "tc", addInfoOnly = true, label = "Traces Clearly", width = 30),
		@Display(name = "tc2", addInfoOnly = true, label = "Traces Clearly", width = 30, hideLabel = true),
		@Display(name = "tc3", addInfoOnly = true, label = "Traces Clearly", width = 30, hideLabel = true),
		@Display(name = "tc4", addInfoOnly = true, label = "Traces Clearly", width = 30, hideLabel = true),
		@Display(name = "tcFinal", enabled = false, addInfoOnly = true, label = "Traces Clearly", width = 30, hideLabel = true),
                @Display(name = "df", addInfoOnly = true, label = "Draws Recognizable Figures", width = 30),
		@Display(name = "df2", addInfoOnly = true, label = "Draws Recognizable Figures", width = 30, hideLabel = true),
		@Display(name = "df3", addInfoOnly = true, label = "Draws Recognizable Figures", width = 30, hideLabel = true),
		@Display(name = "df4", addInfoOnly = true, label = "Draws Recognizable Figures", width = 30, hideLabel = true),
		@Display(name = "dfFinal", enabled = false, addInfoOnly = true, label = "Draws Recognizable Figures", width = 30, hideLabel = true),
                @Display(name = "wlr", addInfoOnly = true, label = "Writes Following Left to Right Progression", width = 30),
		@Display(name = "wlr2", addInfoOnly = true, label = "Writes Following Left to Right Progression", width = 30, hideLabel = true),
		@Display(name = "wlr3", addInfoOnly = true, label = "Writes Following Left to Right Progression", width = 30, hideLabel = true),
		@Display(name = "wlr4", addInfoOnly = true, label = "Writes Following Left to Right Progression", width = 30, hideLabel = true),
		@Display(name = "wlrFinal", enabled = false, addInfoOnly = true, label = "Writes Following Left to Right Progression", width = 30, hideLabel = true),
                @Display(name = "ocs", addInfoOnly = true, label = "Observes Correct Spacing", width = 30),
		@Display(name = "ocs2", addInfoOnly = true, label = "Observes Correct Spacing", width = 30, hideLabel = true),
		@Display(name = "ocs3", addInfoOnly = true, label = "Observes Correct Spacing", width = 30, hideLabel = true),
		@Display(name = "ocs4", addInfoOnly = true, label = "Observes Correct Spacing", width = 30, hideLabel = true),
		@Display(name = "ocsFinal", enabled = false, addInfoOnly = true, label = "Observes Correct Spacing", width = 30, hideLabel = true),
                @Display(name = "cwp", addInfoOnly = true, label = "Copies with Precission", width = 30),
		@Display(name = "cwp2", addInfoOnly = true, label = "Copies with Precission", width = 30, hideLabel = true),
		@Display(name = "cwp3", addInfoOnly = true, label = "Copies with Precission", width = 30, hideLabel = true),
		@Display(name = "cwp4", addInfoOnly = true, label = "Copies with Precission", width = 30, hideLabel = true),
		@Display(name = "cwpFinal", enabled = false, addInfoOnly = true, label = "Copies with Precission", width = 30, hideLabel = true),
                @Display(name = "cp", addInfoOnly = true, label = "Cuts Precisely", width = 30),
		@Display(name = "cp2", addInfoOnly = true, label = "Cuts Precisely", width = 30, hideLabel = true),
		@Display(name = "cp3", addInfoOnly = true, label = "Cuts Precisely", width = 30, hideLabel = true),
		@Display(name = "cp4", addInfoOnly = true, label = "Cuts Precisely", width = 30, hideLabel = true),
		@Display(name = "cpFinal", enabled = false, addInfoOnly = true, label = "Cuts Precisely", width = 30, hideLabel = true),
		@Display(name = "pa", addInfoOnly = true, label = "Pastes Accurately", width = 30),
		@Display(name = "pa2", addInfoOnly = true, label = "Pastes Accurately", width = 30, hideLabel = true),
		@Display(name = "pa3", addInfoOnly = true, label = "Pastes Accurately", width = 30, hideLabel = true),
		@Display(name = "pa4", addInfoOnly = true, label = "Pastes Accurately", width = 30, hideLabel = true),
		@Display(name = "paFinal", enabled = false, addInfoOnly = true, label = "Pastes Accurately", width = 30, hideLabel = true),
                
		@Display(name = "cfp", addInfoOnly = true, label = "Can Follow Patterns", width = 30),
		@Display(name = "cfp2", addInfoOnly = true, label = "Can Follow Patterns", width = 30, hideLabel = true),
		@Display(name = "cfp3", addInfoOnly = true, label = "Can Follow Patterns", width = 30, hideLabel = true),
		@Display(name = "cfp4", addInfoOnly = true, label = "Can Follow Patterns", width = 30, hideLabel = true),
		@Display(name = "cfpFinal", enabled = false, addInfoOnly = true, label = "Can Follow Patterns", width = 30, hideLabel = true),
		@Display(name = "cst", addInfoOnly = true, label = "Is Concious of Stroke Terminals", width = 30),
		@Display(name = "cst2", addInfoOnly = true, label = "Is Concious of Stroke Terminals", width = 30, hideLabel = true),
		@Display(name = "cst3", addInfoOnly = true, label = "Is Concious of Stroke Terminals", width = 30, hideLabel = true),
		@Display(name = "cst4", addInfoOnly = true, label = "Is Concious of Stroke Terminals", width = 30, hideLabel = true),
		@Display(name = "cstFinal", enabled = false, addInfoOnly = true, label = "Is Concious of Stroke Terminals", width = 30, hideLabel = true),
		
		
		

		// Mega Skill
		@Display(name = "con", addInfoOnly = true, leftLabel = "Confidence", labelTop = true, label = "1st", width = 30),
		@Display(name = "con2", addInfoOnly = true, labelTop = true, label = "2nd", width = 30),
		@Display(name = "con3", addInfoOnly = true, labelTop = true, label = "3rd", width = 30),
		@Display(name = "con4", addInfoOnly = true, labelTop = true, label = "4th", width = 30),
		@Display(name = "conFinal", enabled = false, addInfoOnly = true, labelTop = true, label = "Final", width = 30),
		@Display(name = "mot", addInfoOnly = true, label = "Motivation", width = 30),
		@Display(name = "mot2", addInfoOnly = true, label = "Motivation", width = 30, hideLabel = true),
		@Display(name = "mot3", addInfoOnly = true, label = "Motivation", width = 30, hideLabel = true),
		@Display(name = "mot4", addInfoOnly = true, label = "Motivation", width = 30, hideLabel = true),
		@Display(name = "motFinal", enabled = false, addInfoOnly = true, label = "Motivation", width = 30, hideLabel = true),
		@Display(name = "eff", addInfoOnly = true, label = "Effort", width = 30),
		@Display(name = "eff2", addInfoOnly = true, label = "Effort", width = 30, hideLabel = true),
		@Display(name = "eff3", addInfoOnly = true, label = "Effort", width = 30, hideLabel = true),
		@Display(name = "eff4", addInfoOnly = true, label = "Effort", width = 30, hideLabel = true),
		@Display(name = "effFinal", enabled = false, addInfoOnly = true, label = "Effort", width = 30, hideLabel = true),
		@Display(name = "res", addInfoOnly = true, label = "Responsiblity", width = 30),
		@Display(name = "res2", addInfoOnly = true, label = "Responsiblity", width = 30, hideLabel = true),
		@Display(name = "res3", addInfoOnly = true, label = "Responsiblity", width = 30, hideLabel = true),
		@Display(name = "res4", addInfoOnly = true, label = "Responsiblity", width = 30, hideLabel = true),
		@Display(name = "resFinal", enabled = false, addInfoOnly = true, label = "Responsiblity", width = 30, hideLabel = true),
		@Display(name = "ini", addInfoOnly = true, label = "Initiative", width = 30),
		@Display(name = "ini2", addInfoOnly = true, label = "Initiative", width = 30, hideLabel = true),
		@Display(name = "ini3", addInfoOnly = true, label = "Initiative", width = 30, hideLabel = true),
		@Display(name = "ini4", addInfoOnly = true, label = "Initiative", width = 30, hideLabel = true),
		@Display(name = "iniFinal", enabled = false, addInfoOnly = true, label = "Initiative", width = 30, hideLabel = true),
		@Display(name = "per", addInfoOnly = true, label = "Perseverance", width = 30),
		@Display(name = "per2", addInfoOnly = true, label = "Perseverance", width = 30, hideLabel = true),
		@Display(name = "per3", addInfoOnly = true, label = "Perseverance", width = 30, hideLabel = true),
		@Display(name = "per4", addInfoOnly = true, label = "Perseverance", width = 30, hideLabel = true),
		@Display(name = "perFinal", enabled = false, addInfoOnly = true, label = "Perseverance", width = 30, hideLabel = true),
		@Display(name = "car", addInfoOnly = true, label = "Caring", width = 30),
		@Display(name = "car2", addInfoOnly = true, label = "Caring", width = 30, hideLabel = true),
		@Display(name = "car3", addInfoOnly = true, label = "Caring", width = 30, hideLabel = true),
		@Display(name = "car4", addInfoOnly = true, label = "Caring", width = 30, hideLabel = true),
		@Display(name = "carFinal", enabled = false, addInfoOnly = true, label = "Caring", width = 30, hideLabel = true),
		@Display(name = "tea", addInfoOnly = true, label = "Teamwork", width = 30),
		@Display(name = "tea2", addInfoOnly = true, label = "Teamwork", width = 30, hideLabel = true),
		@Display(name = "tea3", addInfoOnly = true, label = "Teamwork", width = 30, hideLabel = true),
		@Display(name = "tea4", addInfoOnly = true, label = "Teamwork", width = 30, hideLabel = true),
		@Display(name = "teaFinal", enabled = false, addInfoOnly = true, label = "Teamwork", width = 30, hideLabel = true),
		@Display(name = "com", addInfoOnly = true, label = "Common Sense", width = 30),
		@Display(name = "com2", addInfoOnly = true, label = "Common Sense", width = 30, hideLabel = true),
		@Display(name = "com3", addInfoOnly = true, label = "Common Sense", width = 30, hideLabel = true),
		@Display(name = "com4", addInfoOnly = true, label = "Common Sense", width = 30, hideLabel = true),
		@Display(name = "comFinal", enabled = false, addInfoOnly = true, label = "Common Sense", width = 30, hideLabel = true),
		@Display(name = "pro", addInfoOnly = true, label = "Problem Solving", width = 30),
		@Display(name = "pro2", addInfoOnly = true, label = "Problem Solving", width = 30, hideLabel = true),
		@Display(name = "pro3", addInfoOnly = true, label = "Problem Solving", width = 30, hideLabel = true),
		@Display(name = "pro4", addInfoOnly = true, label = "Problem Solving", width = 30, hideLabel = true),
		@Display(name = "proFinal", enabled = false, addInfoOnly = true, label = "Problem Solving", width = 30, hideLabel = true),
		@Display(name = "focus", addInfoOnly = true, label = "Focus", width = 30),
		@Display(name = "focus2", addInfoOnly = true, label = "Focus", width = 30, hideLabel = true),
		@Display(name = "focus3", addInfoOnly = true, label = "Focus", width = 30, hideLabel = true),
		@Display(name = "focus4", addInfoOnly = true, label = "Focus", width = 30, hideLabel = true),
		@Display(name = "focusFinal", enabled = false, addInfoOnly = true, label = "Focus", width = 30, hideLabel = true),
		@Display(name = "respect", addInfoOnly = true, label = "Respect", width = 30),
		@Display(name = "respect2", addInfoOnly = true, label = "Respect", width = 30, hideLabel = true),
		@Display(name = "respect3", addInfoOnly = true, label = "Respect", width = 30, hideLabel = true),
		@Display(name = "respect4", addInfoOnly = true, label = "Respect", width = 30, hideLabel = true),
		@Display(name = "respectFinal", enabled = false, addInfoOnly = true, label = "Respect", width = 30, hideLabel = true),
		@Display(name = "clubsAndParticipation", addInfoOnly = true, label = "Clubs", width = 30),
		@Display(name = "clubsAndParticipation2", addInfoOnly = true, label = "Clubs", width = 30, hideLabel = true),
		@Display(name = "clubsAndParticipation3", addInfoOnly = true, label = "Clubs", width = 30, hideLabel = true),
		@Display(name = "clubsAndParticipation4", addInfoOnly = true, label = "Clubs", width = 30, hideLabel = true),
		@Display(name = "clubsAndParticipationFinal", enabled = false, addInfoOnly = true, label = "Clubs", width = 30, hideLabel = true),
		@Display(name = "scouting", addInfoOnly = true, label = "Scouting", width = 30),
		@Display(name = "scouting2", addInfoOnly = true, label = "Scouting", width = 30, hideLabel = true),
		@Display(name = "scouting3", addInfoOnly = true, label = "Scouting", width = 30, hideLabel = true),
		@Display(name = "scouting4", addInfoOnly = true, label = "Scouting", width = 30, hideLabel = true),
		@Display(name = "scoutingFinal", enabled = false, addInfoOnly = true, label = "Scouting", width = 30, hideLabel = true),

		// Values promoted
		@Display(name = "els", addInfoOnly = true, leftLabel = "Effective Leadership Skills", labelTop = true, label = "1st", width = 30),
		@Display(name = "els2", addInfoOnly = true, labelTop = true, label = "2nd", width = 30),
		@Display(name = "els3", addInfoOnly = true, labelTop = true, label = "3rd", width = 30),
		@Display(name = "els4", addInfoOnly = true, labelTop = true, label = "4th", width = 30),
		@Display(name = "elsFinal", enabled = false, addInfoOnly = true, labelTop = true, label = "Final", width = 30),
		@Display(name = "wfr", addInfoOnly = true, label = "Wholesome Followership Role", width = 30),
		@Display(name = "wfr2", addInfoOnly = true, label = "Wholesome Followership Role", width = 30, hideLabel = true),
		@Display(name = "wfr3", addInfoOnly = true, label = "Wholesome Followership Role", width = 30, hideLabel = true),
		@Display(name = "wfr4", addInfoOnly = true, label = "Wholesome Followership Role", width = 30, hideLabel = true),
		@Display(name = "wfrFinal", enabled = false, addInfoOnly = true, label = "Wholesome Followership Role", width = 30, hideLabel = true),
		@Display(name = "apgw", addInfoOnly = true, label = "Active Participation at Group Work", width = 30),
		@Display(name = "apgw2", addInfoOnly = true, label = "Active Participation at Group Work", width = 30, hideLabel = true),
		@Display(name = "apgw3", addInfoOnly = true, label = "Active Participation at Group Work", width = 30, hideLabel = true),
		@Display(name = "apgw4", addInfoOnly = true, label = "Active Participation at Group Work", width = 30, hideLabel = true),
		@Display(name = "apgwFinal", enabled = false, addInfoOnly = true, label = "Active Participation at Group Work", width = 30, hideLabel = true),
		@Display(name = "spaa", addInfoOnly = true, label = "Knows and recites Simple Prayers", width = 30),
		@Display(name = "spaa2", addInfoOnly = true, label = "Knows and recites Simple Prayers", width = 30, hideLabel = true),
		@Display(name = "spaa3", addInfoOnly = true, label = "Knows and recites Simple Prayers", width = 30, hideLabel = true),
		@Display(name = "spaa4", addInfoOnly = true, label = "Knows and recites Simple Prayers", width = 30, hideLabel = true),
		@Display(name = "spaaFinal", enabled = false, addInfoOnly = true, label = "Knows and recites Simple Prayers", width = 30, hideLabel = true),
		@Display(name = "iva", addInfoOnly = true, label = "Integration of Values Acquired", width = 30),
		@Display(name = "iva2", addInfoOnly = true, label = "Integration of Values Acquired", width = 30, hideLabel = true),
		@Display(name = "iva3", addInfoOnly = true, label = "Integration of Values Acquired", width = 30, hideLabel = true),
		@Display(name = "iva4", addInfoOnly = true, label = "Integration of Values Acquired", width = 30, hideLabel = true),
		@Display(name = "ivaFinal", enabled = false, addInfoOnly = true, label = "Integration of Values Acquired", width = 30, hideLabel = true),
		@Display(name = "isl", addInfoOnly = true, label = "Integration of Skills Learned", width = 30),
		@Display(name = "isl2", addInfoOnly = true, label = "Integration of Skills Learned", width = 30, hideLabel = true),
		@Display(name = "isl3", addInfoOnly = true, label = "Integration of Skills Learned", width = 30, hideLabel = true),
		@Display(name = "isl4", addInfoOnly = true, label = "Integration of Skills Learned", width = 30, hideLabel = true),
		@Display(name = "islFinal", enabled = false, addInfoOnly = true, label = "Integration of Skills Learned", width = 30, hideLabel = true),
		@Display(name = "aspvi", addInfoOnly = true, label = "Active Sharing of Personal Views and Ideas", width = 30),
		@Display(name = "aspvi2", addInfoOnly = true, label = "Active Sharing of Personal Views and Ideas", width = 30, hideLabel = true),
		@Display(name = "aspvi3", addInfoOnly = true, label = "Active Sharing of Personal Views and Ideas", width = 30, hideLabel = true),
		@Display(name = "aspvi4", addInfoOnly = true, label = "Active Sharing of Personal Views and Ideas", width = 30, hideLabel = true),
		@Display(name = "aspviFinal", enabled = false, addInfoOnly = true, label = "Active Sharing of Personal Views and Ideas", width = 30, hideLabel = true),
		@Display(name = "hspd", addInfoOnly = true, label = "High Standards of Personal Discipline", width = 30),
		@Display(name = "hspd2", addInfoOnly = true, label = "High Standards of Personal Discipline", width = 30, hideLabel = true),
		@Display(name = "hspd3", addInfoOnly = true, label = "High Standards of Personal Discipline", width = 30, hideLabel = true),
		@Display(name = "hspd4", addInfoOnly = true, label = "High Standards of Personal Discipline", width = 30, hideLabel = true),
		@Display(name = "hspdFinal", enabled = false, addInfoOnly = true, label = "High Standards of Personal Discipline", width = 30, hideLabel = true),
		@Display(name = "sd", addInfoOnly = true, label = "Self-directedness", width = 30),
		@Display(name = "sd2", addInfoOnly = true, label = "Self-directedness", width = 30, hideLabel = true),
		@Display(name = "sd3", addInfoOnly = true, label = "Self-directedness", width = 30, hideLabel = true),
		@Display(name = "sd4", addInfoOnly = true, label = "Self-directedness", width = 30, hideLabel = true),
		@Display(name = "sdFinal", enabled = false, addInfoOnly = true, label = "Self-directedness", width = 30, hideLabel = true),
		@Display(name = "put", addInfoOnly = true, label = "Productive Use of Time", width = 30),
		@Display(name = "put2", addInfoOnly = true, label = "Productive Use of Time", width = 30, hideLabel = true),
		@Display(name = "put3", addInfoOnly = true, label = "Productive Use of Time", width = 30, hideLabel = true),
		@Display(name = "put4", addInfoOnly = true, label = "Productive Use of Time", width = 30, hideLabel = true),
		@Display(name = "putFinal", enabled = false, addInfoOnly = true, label = "Productive Use of Time", width = 30, hideLabel = true),
		@Display(name = "hlew", addInfoOnly = true, label = "Highest Level of Excellence at Work", width = 30),
		@Display(name = "hlew2", addInfoOnly = true, label = "Highest Level of Excellence at Work", width = 30, hideLabel = true),
		@Display(name = "hlew3", addInfoOnly = true, label = "Highest Level of Excellence at Work", width = 30, hideLabel = true),
		@Display(name = "hlew4", addInfoOnly = true, label = "Highest Level of Excellence at Work", width = 30, hideLabel = true),
		@Display(name = "hlewFinal", enabled = false, addInfoOnly = true, label = "Highest Level of Excellence at Work", width = 30, hideLabel = true),
		@Display(name = "prs", addInfoOnly = true, label = "Practical Recycling Skills", width = 30),
		@Display(name = "prs2", addInfoOnly = true, label = "Practical Recycling Skills", width = 30, hideLabel = true),
		@Display(name = "prs3", addInfoOnly = true, label = "Practical Recycling Skills", width = 30, hideLabel = true),
		@Display(name = "prs4", addInfoOnly = true, label = "Practical Recycling Skills", width = 30, hideLabel = true),
		@Display(name = "prsFinal", enabled = false, addInfoOnly = true, label = "Practical Recycling Skills", width = 30, hideLabel = true),
		@Display(name = "cr", addInfoOnly = true, label = "Creativity and Resourcefullness", width = 30),
		@Display(name = "cr2", addInfoOnly = true, label = "Creativity and Resourcefullness", width = 30, hideLabel = true),
		@Display(name = "cr3", addInfoOnly = true, label = "Creativity and Resourcefullness", width = 30, hideLabel = true),
		@Display(name = "cr4", addInfoOnly = true, label = "Creativity and Resourcefullness", width = 30, hideLabel = true),
		@Display(name = "crFinal", enabled = false, addInfoOnly = true, label = "Creativity and Resourcefullness", width = 30, hideLabel = true),
		@Display(name = "cws", addInfoOnly = true, label = "Completion of Work Started", width = 30),
		@Display(name = "cws2", addInfoOnly = true, label = "Completion of Work Started", width = 30, hideLabel = true),
		@Display(name = "cws3", addInfoOnly = true, label = "Completion of Work Started", width = 30, hideLabel = true),
		@Display(name = "cws4", addInfoOnly = true, label = "Completion of Work Started", width = 30, hideLabel = true),
		@Display(name = "cwsFinal", enabled = false, addInfoOnly = true, label = "Completion of Work Started", width = 30, hideLabel = true),

		// ZL2 components
		@Display(name = "pfe", addInfoOnly = true, leftLabel = "Program for Exceptionality                       ", labelTop = true, label = "1st", width = 30),
		@Display(name = "pfe2", addInfoOnly = true, labelTop = true, label = "2nd", width = 30),
		@Display(name = "pfe3", addInfoOnly = true, labelTop = true, label = "3rd", width = 30),
		@Display(name = "pfe4", addInfoOnly = true, labelTop = true, label = "4th", width = 30),
		@Display(name = "pfeFinal", enabled = false, addInfoOnly = true, labelTop = true, label = "Final", width = 30),
		@Display(name = "cra", addInfoOnly = true, label = "Career-related Activities", width = 30),
		@Display(name = "cra2", addInfoOnly = true, label = "Career-related Activities", width = 30, hideLabel = true),
		@Display(name = "cra3", addInfoOnly = true, label = "Career-related Activities", width = 30, hideLabel = true),
		@Display(name = "cra4", addInfoOnly = true, label = "Career-related Activities", width = 30, hideLabel = true),
		@Display(name = "craFinal", enabled = false, addInfoOnly = true, label = "Career-related Activities", width = 30, hideLabel = true),
		@Display(name = "ca", addInfoOnly = true, label = "Creative Activities", width = 30),
		@Display(name = "ca2", addInfoOnly = true, label = "Creative Activities", width = 30, hideLabel = true),
		@Display(name = "ca3", addInfoOnly = true, label = "Creative Activities", width = 30, hideLabel = true),
		@Display(name = "ca4", addInfoOnly = true, label = "Creative Activities", width = 30, hideLabel = true),
		@Display(name = "caFinal", enabled = false, addInfoOnly = true, label = "Creative Activities", width = 30, hideLabel = true),
		@Display(name = "kin", addInfoOnly = true, label = "Kinesthetic", width = 30),
		@Display(name = "kin2", addInfoOnly = true, label = "Kinesthetic", width = 30, hideLabel = true),
		@Display(name = "kin3", addInfoOnly = true, label = "Kinesthetic", width = 30, hideLabel = true),
		@Display(name = "kin4", addInfoOnly = true, label = "Kinesthetic", width = 30, hideLabel = true),
		@Display(name = "kinFinal", enabled = false, addInfoOnly = true, label = "Kinesthetic", width = 30, hideLabel = true),
		@Display(name = "ec1", addInfoOnly = true, label = "Extra Curricular 1", width = 30),
		@Display(name = "ec12", addInfoOnly = true, label = "Extra Curricular 1", width = 30, hideLabel = true),
		@Display(name = "ec13", addInfoOnly = true, label = "Extra Curricular 1", width = 30, hideLabel = true),
		@Display(name = "ec14", addInfoOnly = true, label = "Extra Curricular 1", width = 30, hideLabel = true),
		@Display(name = "ec1Final", enabled = false, addInfoOnly = true, label = "Extra Curricular 1", width = 30, hideLabel = true),
		@Display(name = "ec2", addInfoOnly = true, label = "Extra Curricular 2", width = 30),
		@Display(name = "ec22", addInfoOnly = true, label = "Extra Curricular 2", width = 30, hideLabel = true),
		@Display(name = "ec23", addInfoOnly = true, label = "Extra Curricular 2", width = 30, hideLabel = true),
		@Display(name = "ec24", addInfoOnly = true, label = "Extra Curricular 2", width = 30, hideLabel = true),
		@Display(name = "ec2Final", enabled = false, addInfoOnly = true, label = "Extra Curricular 2", width = 30, hideLabel = true),

		@Display(name = "jan", width = 30),
		@Display(name = "feb", width = 30),
		@Display(name = "mar", width = 30),
		@Display(name = "apr", width = 30),
		@Display(name = "may", width = 30),
		@Display(name = "jun", width = 30),
		@Display(name = "jul", width = 30),
		@Display(name = "aug", width = 30),
		@Display(name = "sep", width = 30),
		@Display(name = "oct", width = 30),
		@Display(name = "nov", width = 30),
		@Display(name = "dece", width = 30)
})
public class StudentValuesGradingOverrideExt extends StudentValuesGrading {
	public static void main(String[] args) {
		view(StudentValuesGradingOverrideExt.class);
	}

	@Override
	public void save() {
		String r = PanelUtil.showPromptDefaultMessage(null, "Please type your reason for changing grade of student?", "");
		if (r!=null && !r.isEmpty()) {
			AuditTrail.addTrail(this, "Change values grade of ["+this.student+"-"+this.gradeLevel+"]", r);
			super.save();
			LockGrading lock = LockGrading.extractGrading(schoolYear);
			GradingProcess proc = new GradingProcess(schoolYear, section, lock.useQuarter());
			proc.setHonors();
		}
	}
}
