/*
 * LibraryScanner.java
 *
 * Created on September 18, 2008, 10:26 PM
 */

package ui.action;

import bean.LibraryBooks;
import bean.LibraryBorrowedBooks;
import bean.Person;
import bean.Student;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.List;
import service.util.AbstractIBean;
import service.util.WSPersistenceEntityManager;
import util.DateUtil;
import util.PanelUtil;

/**
 *
 * @author  Entokwaa
 */
public class LibraryAction extends javax.swing.JPanel {
    public static void showBarcode(LibraryBooks book) {
        LibraryAction scanner = new LibraryAction();
        scanner.book = book;
        scanner.dlgBarcodeBorrow.setMinimumSize(Toolkit.getDefaultToolkit().getScreenSize());
        scanner.dlgBarcodeBorrow.setVisible(true);
    }    
    public static void borrowBook(LibraryBooks book) {
        LibraryAction scanner = new LibraryAction();
        scanner.book = book;
        scanner.cboStudentBorrow.lblDisplay.setEnabled(false);
        scanner.dlgBorrowBook.pack();
        scanner.dlgBorrowBook.setVisible(true);
    }
    public static void returnBook(LibraryBooks book) {
        LibraryAction scanner = new LibraryAction();
        scanner.book = book;
        scanner.cboStudentReturn.lblDisplay.setEnabled(false);
        scanner.dlgReturnBook.pack();
        scanner.dlgReturnBook.setVisible(true);
    }
    LibraryBooks book;

    public LibraryBooks getBook() {
        return book;
    }

    public void setBook(LibraryBooks book) {
        this.book = book;
    }
    
    /** Creates new form LibraryScanner */
    public LibraryAction() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dlgBarcodeBorrow = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        imageRendererPallete2 = new component.ImageRendererPallete();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblStudentName = new javax.swing.JLabel();
        lblGradeLevel = new javax.swing.JLabel();
        lblSection = new javax.swing.JLabel();
        lblIDNumber = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtBarcodeValue = new component.JTextFieldPallete();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBorrowedBooks = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        imageRendererPallete3 = new component.ImageRendererPallete();
        jPanel14 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblShelf = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();
        lblISBN = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lblExitBorrowScreen = new javax.swing.JLabel();
        dlgBorrowBook = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBorrowNow = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        calDueDate = new component.JCalendarPallete();
        cboStudentBorrow = new component.LookupTableFieldPallete();
        dlgReturnBook = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnReturnNow = new javax.swing.JButton();
        cboStudentReturn = new component.LookupTableFieldPallete();
        jLabel7 = new javax.swing.JLabel();
        txtPenalty = new component.JTextFieldPallete();
        javax.persistence.EntityManager schoolPUEntityManager = WSPersistenceEntityManager.getInstance();
        personBorrowQuery = java.beans.Beans.isDesignTime() ? null : schoolPUEntityManager.createQuery("SELECT c FROM Student c");
        personBorrowList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : personBorrowQuery.getResultList();
        borrower = new bean.Person();
        borrowedBooksQuery = java.beans.Beans.isDesignTime() ? null : schoolPUEntityManager.createQuery("SELECT b FROM LibraryBorrowedBooks b");
        borrowedBooksList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : borrowedBooksQuery.getResultList();
        personReturnQuery = java.beans.Beans.isDesignTime() ? null : schoolPUEntityManager.createQuery("SELECT c FROM Student c");
        personReturnList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : personReturnQuery.getResultList();

        dlgBarcodeBorrow.setTitle("Borrow Books");
        dlgBarcodeBorrow.setAlwaysOnTop(true);
        dlgBarcodeBorrow.setName("dlgBarcodeBorrow"); // NOI18N
        dlgBarcodeBorrow.setUndecorated(true);

        jPanel10.setName("jPanel10"); // NOI18N

        imageRendererPallete2.setName("imageRendererPallete2"); // NOI18N

        jPanel11.setName("jPanel11"); // NOI18N
        jPanel11.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("ID #:");
        jLabel3.setName("jLabel3"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 0);
        jPanel11.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Name:");
        jLabel4.setName("jLabel4"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 0);
        jPanel11.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Grade Level:");
        jLabel5.setName("jLabel5"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 0);
        jPanel11.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Section:");
        jLabel6.setName("jLabel6"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 0);
        jPanel11.add(jLabel6, gridBagConstraints);

        lblStudentName.setName("lblStudentName"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 0);
        jPanel11.add(lblStudentName, gridBagConstraints);

        lblGradeLevel.setName("lblGradeLevel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 0);
        jPanel11.add(lblGradeLevel, gridBagConstraints);

        lblSection.setName("lblSection"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 0);
        jPanel11.add(lblSection, gridBagConstraints);

        lblIDNumber.setName("lblIDNumber"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 0);
        jPanel11.add(lblIDNumber, gridBagConstraints);

        jPanel15.setName("jPanel15"); // NOI18N

        jLabel14.setText("Barcode:");
        jLabel14.setName("jLabel14"); // NOI18N

        txtBarcodeValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtBarcodeValue.setName("txtBarcodeValue"); // NOI18N
        txtBarcodeValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBarcodeValueKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBarcodeValue, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtBarcodeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageRendererPallete2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imageRendererPallete2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Borrowed Books"));
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblBorrowedBooks.setName("tblBorrowedBooks"); // NOI18N
        tblBorrowedBooks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblBorrowedBooksKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblBorrowedBooks);

        jPanel12.setName("jPanel12"); // NOI18N

        imageRendererPallete3.setName("imageRendererPallete3"); // NOI18N

        jPanel14.setName("jPanel14"); // NOI18N
        jPanel14.setLayout(new java.awt.GridBagLayout());

        jLabel8.setText("ISBN #:");
        jLabel8.setName("jLabel8"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 2, 0);
        jPanel14.add(jLabel8, gridBagConstraints);

        jLabel9.setText("Shelf:");
        jLabel9.setName("jLabel9"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 2, 0);
        jPanel14.add(jLabel9, gridBagConstraints);

        jLabel10.setText("Title:");
        jLabel10.setName("jLabel10"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 2, 0);
        jPanel14.add(jLabel10, gridBagConstraints);

        jLabel11.setText("Author:");
        jLabel11.setName("jLabel11"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 2, 0);
        jPanel14.add(jLabel11, gridBagConstraints);

        lblShelf.setName("lblShelf"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 2, 0);
        jPanel14.add(lblShelf, gridBagConstraints);

        lblTitle.setName("lblTitle"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 2, 0);
        jPanel14.add(lblTitle, gridBagConstraints);

        lblAuthor.setName("lblAuthor"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 2, 0);
        jPanel14.add(lblAuthor, gridBagConstraints);

        lblISBN.setName("lblISBN"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel14.add(lblISBN, gridBagConstraints);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageRendererPallete3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imageRendererPallete3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel13.setName("jPanel13"); // NOI18N

        lblExitBorrowScreen.setText("Exit Screen");
        lblExitBorrowScreen.setName("lblExitBorrowScreen"); // NOI18N
        lblExitBorrowScreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitBorrowScreenMouseClicked(evt);
            }
        });
        jPanel13.add(lblExitBorrowScreen);

        javax.swing.GroupLayout dlgBarcodeBorrowLayout = new javax.swing.GroupLayout(dlgBarcodeBorrow.getContentPane());
        dlgBarcodeBorrow.getContentPane().setLayout(dlgBarcodeBorrowLayout);
        dlgBarcodeBorrowLayout.setHorizontalGroup(
            dlgBarcodeBorrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgBarcodeBorrowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgBarcodeBorrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                .addContainerGap())
        );
        dlgBarcodeBorrowLayout.setVerticalGroup(
            dlgBarcodeBorrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgBarcodeBorrowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        dlgBorrowBook.setTitle("Borrow Book");
        dlgBorrowBook.setAlwaysOnTop(true);
        dlgBorrowBook.setMinimumSize(new java.awt.Dimension(500, 350));
        dlgBorrowBook.setModal(true);
        dlgBorrowBook.setName("dlgBorrowBook"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose student borrowing this book:"));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Student:");
        jLabel1.setName("jLabel1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        btnBorrowNow.setText("Borrow Book Now");
        btnBorrowNow.setName("btnBorrowNow"); // NOI18N
        btnBorrowNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrowNowActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 5, 0);
        jPanel1.add(btnBorrowNow, gridBagConstraints);

        jLabel12.setText("Due Date:");
        jLabel12.setName("jLabel12"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        jPanel1.add(jLabel12, gridBagConstraints);

        calDueDate.setName("calDueDate"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 3, 0);
        jPanel1.add(calDueDate, gridBagConstraints);

        cboStudentBorrow.setBean("Student");
        cboStudentBorrow.setColumns(new String[] {"lastName", "firstName"});
        cboStudentBorrow.setName("cboStudentBorrow"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 400;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 2, 0);
        jPanel1.add(cboStudentBorrow, gridBagConstraints);

        javax.swing.GroupLayout dlgBorrowBookLayout = new javax.swing.GroupLayout(dlgBorrowBook.getContentPane());
        dlgBorrowBook.getContentPane().setLayout(dlgBorrowBookLayout);
        dlgBorrowBookLayout.setHorizontalGroup(
            dlgBorrowBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgBorrowBookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addContainerGap())
        );
        dlgBorrowBookLayout.setVerticalGroup(
            dlgBorrowBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgBorrowBookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );

        dlgReturnBook.setTitle("Return Book");
        dlgReturnBook.setAlwaysOnTop(true);
        dlgReturnBook.setMinimumSize(new java.awt.Dimension(500, 350));
        dlgReturnBook.setModal(true);
        dlgReturnBook.setName("dlgReturnBook"); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose student returning this book:"));
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Student:");
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 0);
        jPanel3.add(jLabel2, gridBagConstraints);

        btnReturnNow.setText("Return Book Now");
        btnReturnNow.setName("btnReturnNow"); // NOI18N
        btnReturnNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnNowActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(8, 2, 2, 0);
        jPanel3.add(btnReturnNow, gridBagConstraints);

        cboStudentReturn.setBean("Student");
        cboStudentReturn.setColumns(new String[] {"lastName", "firstName"});
        cboStudentReturn.setName("cboStudentReturn"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 400;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 1, 0);
        jPanel3.add(cboStudentReturn, gridBagConstraints);

        jLabel7.setText("Penalty:");
        jLabel7.setName("jLabel7"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 0);
        jPanel3.add(jLabel7, gridBagConstraints);

        txtPenalty.setDataType(3);
        txtPenalty.setName("txtPenalty"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 0);
        jPanel3.add(txtPenalty, gridBagConstraints);

        javax.swing.GroupLayout dlgReturnBookLayout = new javax.swing.GroupLayout(dlgReturnBook.getContentPane());
        dlgReturnBook.getContentPane().setLayout(dlgReturnBookLayout);
        dlgReturnBookLayout.setHorizontalGroup(
            dlgReturnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
            .addGroup(dlgReturnBookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addContainerGap())
        );
        dlgReturnBookLayout.setVerticalGroup(
            dlgReturnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
            .addGroup(dlgReturnBookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

private void txtBarcodeValueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBarcodeValueKeyPressed
if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
        if (borrowedBooksList != null && borrowedBooksList.size() > 0) {
            tblBorrowedBooks.requestFocus();
            tblBorrowedBooks.setRowSelectionInterval(0, 0);
        }
    } else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
        txtBarcodeValue.setText("");
    } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        String str = txtBarcodeValue.getText();
        //check code if person or book
        Person p = (Person) AbstractIBean.firstRecord("SELECT p FROM Student p WHERE p.userid='" + str + "'");
        if (p != null) {
            borrower = p;
        } else {
            if (borrower != null) {
                LibraryBooks bookt = (LibraryBooks) p.firstRecord("SELECT a FROM LibraryBooks a WHERE a.barcode='" + str + "'");
                if (bookt != null) {
                    bookt.borrowBook(borrower.getPersonId(), DateUtil.addDay(constants.Constants.useDate, 3));
                    lblISBN.setText(bookt.getIsbn());
                    lblAuthor.setText(bookt.getAuthor());
                    lblTitle.setText(bookt.getTitle());
                    lblShelf.setText(bookt.getShelfOrGroup());
                    
                } else {
                    txtBarcodeValue.setText("");
                    PanelUtil.showError(txtBarcodeValue, "Barcode not found.");
                    return;
                }
            } else {
                txtBarcodeValue.setText("");
                PanelUtil.showError(txtBarcodeValue, "Please scan ID first.");
                return;
            }
        }
        lblIDNumber.setText(borrower.getUserid());
        lblStudentName.setText(borrower.getLastName() + ", " + borrower.getFirstName());
        if (borrower instanceof Student) {
            lblGradeLevel.setText(((Student) borrower).getGradeLevel());
            lblSection.setText(((Student) borrower).getSection());
        }
        List lst = p.list("SELECT a FROM LibraryBorrowedBooks a WHERE a.personId=" + borrower.getPersonId() + " AND a.isReturned=false");
        PanelUtil.setListData(borrowedBooksList, lst);
        if (borrowedBooksList != null && !borrowedBooksList.isEmpty()) {
            tblBorrowedBooks.setRowSelectionInterval(borrowedBooksList.size() - 1, borrowedBooksList.size() - 1);
        }
        txtBarcodeValue.setText("");
    }
}//GEN-LAST:event_txtBarcodeValueKeyPressed

private void tblBorrowedBooksKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblBorrowedBooksKeyPressed
if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
        txtBarcodeValue.requestFocus();
        txtBarcodeValue.setText("");
    } else if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
        boolean b = PanelUtil.showPrompt(tblBorrowedBooks, "Is student returning the book?");
        if (b) {
            LibraryBorrowedBooks book = borrowedBooksList.get(tblBorrowedBooks.getSelectedRow());
            book.returnBook();
            List lst = book.list("SELECT a FROM LibraryBorrowedBooks a WHERE a.personId=" + borrower.getPersonId() + " AND a.isReturned=false");
            PanelUtil.setListData(borrowedBooksList, lst);
            if (!borrowedBooksList.isEmpty()) {
                tblBorrowedBooks.setRowSelectionInterval(borrowedBooksList.size() - 1, borrowedBooksList.size() - 1);
            } else {
                txtBarcodeValue.requestFocus();
                txtBarcodeValue.setText("");
            }
        }
    }
}//GEN-LAST:event_tblBorrowedBooksKeyPressed

private void lblExitBorrowScreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitBorrowScreenMouseClicked
    dlgBarcodeBorrow.setVisible(false);
}//GEN-LAST:event_lblExitBorrowScreenMouseClicked

private void btnBorrowNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrowNowActionPerformed
    book.borrowBook(cboStudentBorrow.getIntText(), calDueDate.getDate());
    dlgBorrowBook.setVisible(false);
}//GEN-LAST:event_btnBorrowNowActionPerformed

private void btnReturnNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnNowActionPerformed
    book.returnBook(cboStudentReturn.getIntText(), txtPenalty.getDoubleText());
    dlgReturnBook.setVisible(false);
}//GEN-LAST:event_btnReturnNowActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<bean.LibraryBorrowedBooks> borrowedBooksList;
    private javax.persistence.Query borrowedBooksQuery;
    private bean.Person borrower;
    private javax.swing.JButton btnBorrowNow;
    private javax.swing.JButton btnReturnNow;
    private component.JCalendarPallete calDueDate;
    private component.LookupTableFieldPallete cboStudentBorrow;
    private component.LookupTableFieldPallete cboStudentReturn;
    private javax.swing.JDialog dlgBarcodeBorrow;
    private javax.swing.JDialog dlgBorrowBook;
    private javax.swing.JDialog dlgReturnBook;
    private component.ImageRendererPallete imageRendererPallete2;
    private component.ImageRendererPallete imageRendererPallete3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblExitBorrowScreen;
    private javax.swing.JLabel lblGradeLevel;
    private javax.swing.JLabel lblIDNumber;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblSection;
    private javax.swing.JLabel lblShelf;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblTitle;
    private java.util.List<bean.Student> personBorrowList;
    private javax.persistence.Query personBorrowQuery;
    private java.util.List<bean.Student> personReturnList;
    private javax.persistence.Query personReturnQuery;
    private javax.swing.JTable tblBorrowedBooks;
    private component.JTextFieldPallete txtBarcodeValue;
    private component.JTextFieldPallete txtPenalty;
    // End of variables declaration//GEN-END:variables

}
